src/backend/central/central_crud.py
src/backend/debug/debug_routes.py
src/backend/models/enums.py
src/backend/odkconvert/OdkCentral.py
src/backend/odkconvert/make_data_extract.py
src/backend/odkconvert/odk_client.py
src/backend/odkconvert/requirements.txt
src/backend/projects/project_crud.py
src/backend/projects/project_routes.py
src/backend/requirements.txt
traefik/traefik.dev.toml

Incorporating odkconvert required changes to get the current main branch working again with docker-compose. With this patch, docker-compose works again, although still brings up the old Flask UI.

Fix breakage for docker-compose

---

src/backend/odkconvert/OdkCentral.py
src/backend/odkconvert/make_data_extract.py
src/backend/odkconvert/odk_client.py
src/backend/odkconvert/requirements.txt
src/backend/projects/project_crud.py

Get both spreadsheet versions.

Look for both xlsx and xls files

---

src/backend/central/central_crud.py
src/backend/db/db_models.py
src/backend/debug/debug_routes.py
src/backend/models/enums.py
src/backend/odkconvert/OdkCentral.py
src/backend/odkconvert/make_data_extract.py
src/backend/odkconvert/odk_client.py
src/backend/odkconvert/requirements.txt
src/backend/projects/project_crud.py
src/backend/projects/project_routes.py
src/backend/requirements.txt
src/backend/tasks/tasks_crud.py
src/backend/tasks/tasks_schemas.py
traefik/traefik.dev.toml

This was broken due to some database columns that I don't think are actually needed. With this patch it's possible to list projects and tasks again.

List project and task geometries

---

.github/workflows/pytest.yml
src/backend/central/central_routes.py
src/backend/requirements-dev.txt

- Triggers on PR creation & push to main (including PR merge).
- Installs dependencies, then runs PyTest.
- As part of this PR I also removed epdb from requirements (we can use it during development and add manual traces, but I don't think it needs to be in the repo requirements) - apologies for being lazy & not including in another PR.

Add Github workflow for PyTest

---

src/backend/projects/project_crud.py
src/backend/projects/project_routes.py

Until the entire automated process is fully working, it's still necessary to populate the database from a zip file.

Fix populating data from zip file

---

src/backend/central/central_crud.py
src/backend/db/db_models.py
src/backend/projects/project_crud.py
src/backend/projects/project_routes.py
src/backend/tasks/tasks_crud.py
src/backend/tasks/tasks_schemas.py

Closes #111
- The working endpoint to upload ZIP files is **/projects/beta/{project_id}/upload**
- I fixed the database relations during upload for QR codes.
- I also convert the QR image to a base64 string to include in param `qr_code_base64` for endpoint **/projects/{project_id}**:

Fix QR code database insertion and display for tasks on /projects/{id}

---

.all-contributorsrc
README.md

fixes https://github.com/hotosm/fmtm/issues/83
cc @spwoodcock @petya-kangalova @robsavoye

Add allcontributors bot

---

README.md

fix typo in the README.md

---

scripts/odk_fieldmap_original/parse_pip_error.py
scripts/odk_fieldmap_original/setup.sh
scripts/odk_fieldmap_original/utils/aoi2odk.py
scripts/odk_fieldmap_original/utils/dl_submissions.py
scripts/odk_fieldmap_original/utils/example_odk_requests.py
scripts/odk_fieldmap_original/utils/forms2server.py
scripts/odk_fieldmap_original/utils/geo_utils.py
scripts/odk_fieldmap_original/utils/odk_requests.py
scripts/odk_fieldmap_original/utils/old_qr_stuff.py
scripts/odk_fieldmap_original/utils/overpass.py
scripts/odk_fieldmap_original/utils/renamer.py
scripts/odk_fieldmap_original/utils/tasks2forms.py

cc @rsavoye @spwoodcock @petya-kangalova

clean code by removing trails

---

docs/DEV-1.-Getting-Started.md

The url for forking the fmtm repository was corrected

corrected the url

---

src/frontend/main/src/views/Home.tsx

updated pagination flexibility based on number of cards and have placed it on top and bottom of the cards for easiness

Pagination for project summaries #31

---

docs/Mapping-Campaign-Using-FMTM.md
src/backend/db/db_models.py
src/backend/debug/debug_crud.py
src/backend/projects/project_crud.py
src/backend/projects/project_schemas.py

Locale is unnecessary as it's available from the system, and since uses ODK Collect, there is no need for instructions lioke the Tasking Manager uses.

Remove locale and instructions from the database

---

src/frontend/main/src/api/CreateProjectService.ts
src/frontend/main/src/components/createproject/ProjectDetailsForm.tsx
src/frontend/main/src/components/createproject/UploadArea.tsx
src/frontend/main/src/components/home/HomePageFilters.tsx
src/frontend/main/src/models/createproject/createProjectModel.ts
src/frontend/main/src/routes.jsx
src/frontend/main/src/shared/CoreModules.js
src/frontend/main/src/store/Store.js
src/frontend/main/src/store/slices/CreateProjectSlice.ts
src/frontend/main/src/views/CreateProject.tsx

In this pull request i have worked on create project module where we can create project and upload geojson boundary although there is a sanity check remaining on the form which I will finish off later today.

Feat createproject

---

docs/DEV-1.-Getting-Started.md

Fixed a typo in Getting Started Documentation for the issue #164 .
@robsavoye and @petya-kangalova please review.

Fixed typos in Getting Started Documentation

---

docs/Mapping-Campaign-Using-FMTM.md

fixed typo

---

src/frontend/main/src/routes.jsx
src/frontend/main/src/utilities/CustomDrawer.tsx

Fixed the Navigation routing -Issue #214

---

docs/DEV-2.-Backend.md
docs/DEV-5.-Docker-Tips.md

I have fixed typos in docs of FMTM wrt #164 . @rsavoye and @petya-kangalova please review it.

Fixed errors in DEV-2.-Backend.md

---

docs/DEV-1.-Getting-Started.md

#84  #164 
Made an update on what the .env file now looks like

Updated documentation

---

docs/Guide-On-Improving-Documentation.md
docs/Mapping-Campaign-Using-FMTM.md

Wrt #164 . @rsavoye and @petya-kangalova please review it.

Improved docs 

---

.all-contributorsrc
README.md
docs/Mapping-Campaign-Using-FMTM.md

I updated the getting started documentation file Dev-1-Getting-Started.

Updated the documentation

---

docs/Contribution.md

I made a minor change to make it look nice.@robsavoye and @petya-kangalova please review it.

Updated Contribution.md

---

docs/Home.md

Improved Home.md

---

docs/Mapping-Campaign-Using-FMTM.md

Fixed a typo in Mapping-Campaign-Using-FMTM.md. @robsavoye and @petya-kangalova please review it.

Fixed a typo in Mapping-Campaign-Using-FMTM.md

---

CODE_OF_CONDUCT.md

Restructured the bullet system of Code of Conduct as per #164  . @robsavoye and @petya-kangalova please review it.

Restructured the bullet system

---

docs/DEV-4.-Database-Tips.md

Improve DEV-4-Database-Tips.md

Improve DEV-4-Database-Tips.md

---

docs/Code-of-Conduct.md

Updated Code-of-Conduct.md according to #271 . @robsavoye and @petya-kangalova please review it.

Updated Code-of-Conduct.md 

---

docs/Mapping-Campaign-Using-FMTM.md

Restructured Mapping-Campaign-Using-FMTM.md

---

docs/About.md

Added some more details to the documentation.

Redefining About.md

---

docs/DEV-6.-Production-Deployment.md

Restructured DEV-6.-Production-Deployment.md

---

.github/workflows/prod_deploy.yml

Fixed issue #206 
Updated prod_deploy.yml to only trigger when file change in `src/`

Fixed issue #206

---

docs/Contribution.md

improved Contribution.md

---

docs/Home.md

Adding more details to the Home.md

Improve Home.md

---

src/frontend/main/src/api/CreateProjectService.ts
src/frontend/main/src/components/createproject/CreateProjectValidation.tsx
src/frontend/main/src/components/createproject/ProjectDetailsForm.tsx
src/frontend/main/src/components/createproject/UploadArea.tsx
src/frontend/main/src/hooks/useForm.tsx
src/frontend/main/src/models/createproject/createProjectModel.ts
src/frontend/main/src/store/slices/CreateProjectSlice.ts

- Resolve #329 
- Need #337  to be merge inorder to see the organization list

FEATURE: Organization field in create project

---

src/backend/central/central_crud.py
src/frontend/main/src/api/CreateProjectService.ts
src/frontend/main/src/components/createproject/ProjectDetailsForm.tsx
src/frontend/main/src/components/createproject/UploadArea.tsx
src/frontend/main/src/store/slices/CreateProjectSlice.ts
src/frontend/main/src/store/slices/ThemeSlice.ts

- Resolve #358 
- Resolve #360 
- Resolve #346

Fix uploadarea dropdown

---

.github/workflows/dev_deploy.yml
.github/workflows/prod_deploy.yml

Fix GitHub action syntax / auto-deploy

---

scripts/odk_fieldmap_original/utils/aoi2odk.py

As suggested by @robsavoye and @spwoodcock , I have started the work for adding the docstrings . @robsavoye , @petya-kangalova and @spwoodcock please review it.

Updated the docstrings

---

src/frontend/fmtm_openlayer_map/src/api/SubmissionService.ts
src/frontend/fmtm_openlayer_map/src/components/MapComponent/OpenLayersComponent/LayerSwitcher/index.js
src/frontend/fmtm_openlayer_map/src/components/MapComponent/OpenLayersComponent/helpers/styleUtils.js
src/frontend/fmtm_openlayer_map/src/components/SubmissionMap/SubmissionMap.jsx
src/frontend/fmtm_openlayer_map/src/components/SubmissionMap/SubmissionMap.tsx
src/frontend/fmtm_openlayer_map/src/views/Home.jsx
src/frontend/fmtm_openlayer_map/src/views/Submissions.jsx
src/frontend/fmtm_openlayer_map/src/views/Submissions.tsx
src/frontend/fmtm_openlayer_map/webpack.config.js
src/frontend/main/src/api/CreateProjectService.ts
src/frontend/main/src/api/LoginService.ts
src/frontend/main/src/api/OrganizationService.ts
src/frontend/main/src/components/createproject/FormSelection.tsx
src/frontend/main/src/components/createproject/ProjectDetailsForm.tsx
src/frontend/main/src/components/createproject/UploadArea.tsx
src/frontend/main/src/components/organization/OrganizationAddForm.tsx
src/frontend/main/src/components/organization/Validation/OrganizationAddValidation.tsx
src/frontend/main/src/models/organization/organizationModal.ts
src/frontend/main/src/store/slices/CommonSlice.ts
src/frontend/main/src/store/slices/CreateProjectSlice.ts
src/frontend/main/src/store/slices/ProjectSlice.ts
src/frontend/main/src/utilities/CustomizedModal.tsx

Building Geojson is added on Project Details and Submission Page and usage of centroid of building is done

Feat building

---

src/backend/projects/project_crud.py
src/backend/projects/project_routes.py
src/backend/requirements.txt
src/frontend/fmtm_openlayer_map/src/views/Submissions.jsx
src/frontend/main/src/api/CreateProjectService.ts
src/frontend/main/src/components/createproject/FormSelection.tsx
src/frontend/main/src/components/createproject/UploadArea.tsx
src/frontend/main/src/utilities/PrimaryAppBar.tsx

Feature/Extract Polygon or Centroid

---

.github/workflows/deploy_template.yml
.github/workflows/image_build.yml
docker-compose.noodk.yml
src/backend/app/submission/submission_crud.py
src/backend/tests/conftest.py

Fix CI workflows after PR #372

---

docs/FAQ.md

Just changed the structure of FAQs to separate each pair of question and answer. @robsavoye and @petya-kangalova please review it.

Updated FAQ.md

---

src/frontend/main/package-lock.json
src/frontend/main/src/shared/CoreModules.js
src/frontend/main/src/store/slices/ThemeSlice.ts
src/frontend/main/src/utilities/MappingHeader.tsx
src/frontend/main/src/utilities/PrimaryAppBar.tsx
src/frontend/main/src/views/MainView.jsx
src/frontend/main/src/views/Organization.tsx

Mappong header component created and organization ui created and style fixing.
#434

Feature oragnization UI

---

docs/Home.md

Updated Home.md

---

README.md

@robsavoye and @petya-kangalova  please review it.

Does not require a bullet

---

docs/About.md

Updated About.md

---

src/frontend/main/src/components/createproject/ProjectDetailsForm.tsx
src/frontend/main/src/components/home/HomePageFilters.tsx
src/frontend/main/src/views/Home.jsx
src/frontend/main/src/views/SubmissionDetails.tsx

Feature submission detail

---

src/frontend/fmtm_openlayer_map/src/api/task.ts
src/frontend/fmtm_openlayer_map/src/components/ProjectInfo/ProjectInfoSidebar.jsx
src/frontend/fmtm_openlayer_map/src/views/ProjectInfo.jsx
src/frontend/main/src/components/home/HomePageFilters.tsx
src/frontend/main/src/shared/CoreModules.js
src/frontend/main/src/store/Store.js
src/frontend/main/src/store/slices/TaskSlice.ts
src/frontend/main/src/views/Organization.tsx

Multiple search bar and filter removed in small screens .
#477

Fix searchbar

---

src/frontend/fmtm_openlayer_map/src/api/task.ts
src/frontend/fmtm_openlayer_map/src/components/ProjectInfo/ProjectInfoSidebar.jsx
src/frontend/fmtm_openlayer_map/src/views/ProjectInfo.jsx
src/frontend/main/src/shared/CoreModules.js
src/frontend/main/src/store/Store.js
src/frontend/main/src/store/slices/TaskSlice.ts
src/frontend/main/src/views/Organization.tsx

Task api fetched in projectInfo page .
#480

Feature task fetch

---

src/frontend/main/src/components/createproject/UploadArea.tsx

fix: Fixes Create Project Section : The input file name has design issues. #452

---

src/backend/app/central/central_crud.py
src/backend/app/db/db_models.py
src/backend/app/main.py
src/backend/app/projects/project_crud.py
src/backend/app/projects/project_routes.py
src/frontend/fmtm_openlayer_map/src/api/task.ts
src/frontend/fmtm_openlayer_map/src/components/ProjectInfo/ProjectInfomap.jsx
src/frontend/fmtm_openlayer_map/src/views/Home.jsx
src/frontend/main/src/api/CreateProjectService.ts
src/frontend/main/src/components/createproject/DefineTasks.tsx
src/frontend/main/src/views/Home.jsx

We have added a new Page for Project Info Visualization to list down tasks and on map interaction but has still some things remaining to do

Feat-alogrithm-createproject

---

src/frontend/fmtm_openlayer_map/src/components/ActivitiesPanel.jsx
src/frontend/fmtm_openlayer_map/src/components/MapDescriptionComponents.jsx
src/frontend/main/src/utilities/PrimaryAppBar.tsx

- Resolve Search by Tasks or Username : Add a description "No results found" if the search parameters do not match.  #464
- Resolve Project Details Page : Nothing pops up in Instructions page, Where does the user entry the instructions? #463

Fix: Github Issues

---

src/frontend/main/src/components/createproject/ProjectDetailsForm.tsx
src/frontend/main/src/components/home/ExploreProjectCard.tsx
src/frontend/main/src/store/slices/ThemeSlice.ts
src/frontend/main/src/views/CreateProject.tsx

feat : Font family changed at all pages and project details responsive

---

src/frontend/fmtm_openlayer_map/src/views/DefineAreaMap.jsx
src/frontend/main/src/components/createproject/DefineTasks.tsx
src/frontend/main/src/components/createproject/FormSelection.tsx
src/frontend/main/src/components/createproject/UploadArea.tsx

feat : map height chnaged and create project form responsive

---

src/frontend/main/src/components/createproject/FormSelection.tsx

fix : form selection responsive style fixed

---

src/frontend/fmtm_openlayer_map/src/views/DefineAreaMap.jsx
src/frontend/fmtm_openlayer_map/src/views/Home.jsx

- Create Project : Initially the global map should be displayed by default. resolve#461

fix: Global View of map

---

src/backend/app/organization/organization_crud.py

Feat organizations

---

src/frontend/main/src/components/createproject/ProjectDetailsForm.tsx

feat: create organization button on create project

---

src/backend/app/projects/project_routes.py
src/frontend/fmtm_openlayer_map/src/components/TasksMap/TasksMap.jsx
src/frontend/fmtm_openlayer_map/src/views/DefineAreaMap.jsx
src/frontend/fmtm_openlayer_map/src/views/Home.jsx
src/frontend/fmtm_openlayer_map/src/views/ProjectInfo.jsx
src/frontend/main/src/api/CreateProjectService.ts
src/frontend/main/src/components/createproject/ProjectDetailsForm.tsx
src/frontend/main/src/components/editproject/EditProjectDetails.tsx
src/frontend/main/src/components/editproject/UpdateForm.tsx
src/frontend/main/src/components/editproject/validation/EditProjectDetailsValidation.ts
src/frontend/main/src/constants/EditProjectSidebarContent.ts
src/frontend/main/src/environment.ts
src/frontend/main/src/models/createproject/createProjectModel.ts
src/frontend/main/src/routes.jsx
src/frontend/main/src/shared/AssetModules.js
src/frontend/main/src/store/slices/CreateProjectSlice.ts
src/frontend/main/src/utilities/MappingHeader.tsx
src/frontend/main/src/views/EditProject.tsx

Feat-edit-project

---

src/backend/app/projects/project_routes.py

* API projects/download_template/ returns form.xls template of a given category query parameter.

feature: new api /download_template/ that returns xls form template based on category

---

src/backend/app/projects/project_crud.py

* project_curd.py:generate_appuser_files():1295 uses json.loads(one.outline) instead of eval(one.outline)

fix: generate_appuser_files json loads the one.outline instead of eval

---

src/backend/app/projects/project_crud.py
src/backend/app/projects/project_routes.py

* api /projects/<project:id>/download provides geojson file of project outline

api to download project_outline

---

src/backend/app/projects/project_crud.py

Fix/task spliting polygon task spliting algorithm works for geojson with Polygons instead of features

---

src/frontend/main/src/components/createproject/ProjectDetailsForm.tsx
src/frontend/main/src/utilfunctions/createPopup.ts
src/frontend/main/src/utilfunctions/login.ts
src/frontend/main/src/views/CreateOrganization.tsx
src/frontend/main/src/views/CreateProject.tsx

Fix create organization

---

src/backend/app/submission/submission_crud.py
src/backend/app/submission/submission_routes.py

Fix: json download in project detail page

---

src/backend/app/projects/project_crud.py

fix: upload geojson type Polygon

---

src/frontend/fmtm_openlayer_map/src/components/ProjectInfo/ProjectInfomap.jsx
src/frontend/fmtm_openlayer_map/src/views/Tasks.jsx
src/frontend/main/src/components/createproject/FormSelection.tsx
src/frontend/main/src/components/createproject/ProjectDetailsForm.tsx

Revert "Feat hashtag"

---

docs/DEV-4.-Database-Tips.md

Some basic info to stash these doc updates.
Can be merged and continued later, or left and updated as we go.

Docs on db debugging + project backup/restore

---

src/backend/app/submission/submission_crud.py

List submission returns only basic info. We will merge this only after a new release of osm-fieldwork.

fetch submission basic info

---

src/backend/app/central/central_crud.py
src/backend/app/db/db_models.py
src/backend/app/projects/project_crud.py
src/backend/app/projects/project_routes.py
src/backend/app/projects/utils.py

Here I have solved the questions order issue in odk.
xmltodict package have created an issue in questions order, So to fix this, instead of converting an xml to dictionary, I have edited the xml to keep the form id and data extract file name.
Please have a look, If I have missed anything.

fix: questions order in odk collect

---

src/backend/app/users/user_crud.py
src/backend/app/users/user_routes.py
src/backend/app/users/user_schemas.py

Changes made  : 
Wrote doctrings for the files of user directory .
@robsavoye please review this .

Docstrings for User directory

---

INSTALL.md
docs/DEV-2.-Backend.md
src/backend/app/central/central_crud.py
src/backend/app/projects/project_crud.py
src/backend/app/projects/project_routes.py
src/backend/app/tasks/tasks_crud.py

Small unhandled exception when the ODKCentral address cannot be contacted.
Added additional logging to the project creation stages (3 endpoints) for debugging.
(I managed to complete the full project and task creation workflow successfully 🎉)

Project creation: handle odkcentral failure, additional logs

---

src/backend/app/models/enums.py
src/backend/app/models/languages_and_countries.py
src/backend/app/organization/organization_crud.py
src/backend/app/organization/organization_routes.py
src/backend/app/organization/organization_schemas.py
src/backend/app/pagination/pagination.py
src/backend/app/projects/project_crud.py
src/backend/app/projects/project_routes.py
src/backend/app/projects/project_schemas.py
src/backend/app/projects/utils.py

I have added docstrings to the files of the following directories in the backend/app directory :
- projects
- pagination
- oganisation
- models
@robsavoye please review this .

Added Docstrings

---

src/backend/app/projects/project_crud.py

Multithreading

---

src/backend/app/projects/project_crud.py
src/backend/app/projects/project_routes.py

Updated task split for multipolygon, geometrycollection

---

src/frontend/fmtm_openlayer_map/src/api/Project.js
src/frontend/fmtm_openlayer_map/src/views/Home.jsx
src/frontend/main/src/store/slices/ProjectSlice.ts

fix Add option to download the data extract fix #779

Feat-download-dataextract

---

src/backend/app/central/central_crud.py
src/backend/app/projects/project_crud.py
src/backend/app/projects/project_routes.py

We needed to upload two different geojson files in th odk for the Janakpur. 
To adjust this, I have created a seperate api through which we can upload two seperate data extracts files for buildings and roads. We did not want to make changes  in the workflowin the frontend. So, we will be doing this via api.

Upload multiple geojson for janakpur

---

src/backend/app/projects/project_crud.py
src/backend/app/tasks/tasks_crud.py

Replace make_data_extract PostgresClient with osm-rawdata

---

src/frontend/src/components/common/Select.tsx
src/frontend/src/components/createnewproject/ProjectDetailsForm.tsx
src/frontend/src/components/createnewproject/SelectForm.tsx
src/frontend/src/components/home/HomePageFilters.tsx

This PR solves issue #946 and starts #944.
1. #944:
2. #946:

Align new organization button, replace total projects text

---

src/backend/app/projects/project_routes.py
src/backend/app/projects/project_schemas.py

fixes #944 
This pull requests adds new pagination info in project summary.

Added Pagination info in the project summary

---

src/frontend/src/components/MapComponent/OpenLayersComponent/Layers/VectorLayer.js
src/frontend/src/components/createnewproject/UploadArea.tsx
src/frontend/src/views/NewDefineAreaMap.tsx

feat: edit draw AOI in create project

---

src/backend/app/central/central_schemas.py
src/backend/app/main.py
src/backend/app/projects/project_routes.py

Minor PR to refactor:
```python
obj = BytesIO()
obj.seek(0)
obj.read()
```
with
```python
obj = BytesIO()
obj.getvalue()
```
The `.getvalue` method reads the entire content of the buffer, so no seek required.
@nrjadkry @Sujanadh useful to know 👍

Refactor bytesio .seek(0) & .read() methods with .getvalue()

---

src/frontend/src/components/createnewproject/SplitTasks.tsx
src/frontend/src/components/home/ProjectListMap.tsx
src/frontend/src/utilities/PrimaryAppBar.tsx
src/frontend/src/views/CreateOrganization.tsx
src/frontend/src/views/Home.jsx

This PR contains workdone on following things:
1. homepage UI content height issue on some large device solved
2. createNewProject - (splitTasks) - `generateTasks` button disabled on `divideOnSquare` selection issue solved
3. toggle dark/light mode button hidden(commented)
4. createOrganization - content centered to the screen

Fix homepage UI ref

---

src/backend/app/auth/auth_routes.py
src/backend/app/db/db_models.py
src/backend/app/tasks/tasks_crud.py
src/backend/app/tasks/tasks_routes.py
src/backend/app/tasks/tasks_schemas.py
src/backend/migrations/002-add-profile-img.sql
src/backend/migrations/revert/002-add-profile-img.sql

1. New DbUser field `profile_img` is created to store logged in user 's profile image.
2. Updated auth_routes so as to save it in the database. Here, i have added portion of code to save image in existing users(already logged-in users) too which might be removed later.
3. Created a function `update_task_history` to populate `task_history` with `username`, `status`(extracted from the action_text to keep track of task status history) and `profile_img` .

Add image to user profile

---

src/backend/app/projects/project_schemas.py

There was minor issue for the custom date format for the dates over 7 days and Timezone issue.
It has been solved now.

fix: Issue of Custom date format for over 7days

---

src/backend/app/projects/project_schemas.py
src/backend/app/tasks/tasks_schemas.py

Pytest seems working fine. Depends on PR #1073

Update pydantic v2 validator deprecations 

---

src/frontend/src/components/ProjectDetails/ProjectOptions.tsx
src/frontend/src/components/createnewproject/ProjectDetailsForm.tsx
src/frontend/src/components/createnewproject/SelectForm.tsx

This PR addresses following issues: 
- Fix #1065 
- Fix #1064 
- Fix #1055 
Note: although the search works for the `select` already, a more user-friendly search for the `select` will be added further

Create & edit project UI fixes

---

src/backend/app/projects/project_schemas.py

Ticket number, link, or description.
Example: Fixes #123

hotfix: location_str made optional in ReadProject Schema

---

src/backend/app/models/enums.py
src/backend/app/organization/organization_crud.py
src/backend/app/organization/organization_deps.py
src/backend/app/organization/organization_routes.py
src/backend/app/organization/organization_schemas.py

Based on a discussion today about FastAPI/Pydantic best practices, from: https://docs.hotosm.org/dev-guide/web-apis/#best-practices
Updated the organization dir to follow this, as a rough template going forward.
(of course, it's not perfect, but it's a good starting point)
Main takeaways:
- Putting validation logic in Pydantic models.
- Recurring logic to e.g. fetch an organization or project can be dependencies (Depends).
- Putting status codes for responses in an enum.
- Most logic for an endpoint is in the `xxx_crud.py` file, making `xxx_routes.py` just a wrapper.
- Cases where we need to use a pydantic model for input validation, but also upload a file, aren't handled perfectly by FastAPI. We can solve it like this: https://github.com/hotosm/fmtm/blob/bfbbaa4933ab77bb28316669e14d453849 …

Refactor organization routes/crud/schemas to use best practice

---

src/frontend/src/components/ProjectDetailsV2/ActivitiesPanel.tsx

- Fixes #1105
Increased search input width in task activity sidebar.

Fix search input width

---

src/backend/app/projects/project_crud.py

Fix condition in elif statement for Feature type detection

---

src/backend/pdm.lock
src/backend/pyproject.toml

- Upgrades to latest versions of dependent packages osm-fieldwork & fmtm-splitter.
- Incorporates changes by @Sujanadh (fmtm-splitter) and @nrjadkry (osm-fieldwork).

Upgrade osm-fieldwork --> 0.4.1 & fmtm-splitter --> 0.2.6

---

src/backend/app/submissions/submission_crud.py
src/backend/app/submissions/submission_routes.py
src/backend/app/submissions/submission_schemas.py

Submissions by project are organized in paginated form for the submission table.
```
{
"results": [
{
"start": "2023-12-28T14:14:15.400+05:45",
"end": "2023-12-28T14:15:04.773+05:45",
"today": "2023-12-28",
.
.
.
"deviceId": "collect:qKQrgKKs1LrYoFoC",
"edits": 0,
"formVersion": "2023-12-28T08:25:29Z"
}
],
"pagination": {
"has_next": false,
"has_prev": false,
"next_num": null,
"page": 1,
"pages": 1,
"prev_num": null,
"per_page": 13,
"total": 3
}
}
```
- 📗 Update …

Paginated submissions by project

---

src/backend/app/projects/project_crud.py

There was an issue while splitting multipolygon type geometry. Previously only geometry was passed to algorithm instead of geojson which caused an error while splitting which looks like this:
`ValueError: The specified AOI is not valid (must be geojson or str)`
This PR addresses this issue by properly populating features in geojson and passing entire geojson to the algorithm.

Fix divide by square on multipolygon geojson

---

src/backend/app/submissions/submission_crud.py
src/backend/app/submissions/submission_routes.py

This PR introduces new end point `/task_submissions `where paginated submissions of respective task of the project is returned.
Here, `listSubmissions` from the `OdkForm` is used to retrieve submissions which accepts dict parameter `filters` which allows to retrieve the limited submissions using skip and limit directly from the odk central.
```
{
"results": [
{
"start": "2023-12-28T14:14:15.400+05:45",
"end": "2023-12-28T14:15:04.773+05:45",
"today": "2023-12-28",
"phonenumber": null,
"deviceid": "collect:qKQrgKKs1LrYoFoC",
"username": null,
"email": null,
"instructions": null,
"warmup": "POINT (85.3284743 27.7303606 1278.9000244140625)",
"all": {
"model": "basic",
"existing": "44549",
"xid": "44549",
"xlocation": "27.704872 85.321303 0 0; 27.704846 85.321349 0 0; 27.704844 85.321613 0 0; …
```

Paginated task wise submissions

---

src/backend/app/auth/roles.py

`AttributeError: 'AuthUser' object has no attribute 'get'`
In the roles.py file, there was an issue where the `get` method was incorrectly used on an 'AuthUser' object. This resulted in an AttributeError since 'AuthUser' does not have a 'get' attribute. The problem was fixed by accessing the 'id' and 'username' attribute directly. 

hotfix: retrieve id and username directly instead of using .get

---

src/frontend/src/components/MapComponent/OpenLayersComponent/Layers/VectorLayer.js
src/frontend/src/components/common/StepSwitcher.tsx
src/frontend/src/components/createnewproject/ProjectDetailsForm.tsx
src/frontend/src/components/createnewproject/UploadArea.tsx
src/frontend/src/views/NewDefineAreaMap.tsx

- Fix #1147
- Fix #1084
This PR solves following bug/issues: 
1. **Area validation** check on `uploadAreaSelection` -> `upload_file`
2. Draw functionality **hidden** on map for `uploadAreaSelection` -> `upload_file`
3. Draw functionality **hidden** on map if **AOI** already exists for `uploadAreaSelection` -> `draw`
4. `cursorPointer` removed on stepForm step `hover`
5. Step 1: redirectionLink to odk server setup added to `Here` text
5.

Fix project creation issues

---

src/backend/app/projects/project_crud.py

Fixes https://github.com/hotosm/fmtm/issues/1156
- I think this could have been a temporary issue with raw-data-api?
- Either way, I added extra error handling, so we get a more informative error for the devs if it fails.

Add extra error handling if data extract download fails

---

src/frontend/src/components/ProjectSubmissions/ProjectInfo.tsx

Display project creation date in clear and readable way
Before:
After:

Project submission date and time formatting

---

src/frontend/src/utilfunctions/login.ts

Fixes #834
- Safari does not allow popups to be created within an async request context.
- The popup must be created first, then the location changed to the required URL.

Fix iOS Safari popup-based login

---

src/frontend/src/components/ProjectDetailsV2/ProjectOptions.tsx
src/frontend/src/components/common/Button.tsx
src/frontend/src/hooks/useOutsideClick.ts
src/frontend/src/views/ProjectDetailsV2.tsx

- Fix #1107
This PR updates project details page by adding button for manage-project, view-infographics, & download options.

Fix project details UI additions

---

INSTALL.md
src/backend/app/projects/project_routes.py
src/frontend/src/api/CreateProjectService.ts
src/frontend/src/components/MapDescriptionComponents.jsx
src/frontend/src/components/editproject/DeleteProject.tsx
src/frontend/src/constants/EditProjectSidebarContent.ts
src/frontend/src/routes.jsx
src/frontend/src/views/EditProject.tsx

Fixes #545
- Added project deletion to a tab in the edit project page.
- Endpoint requires org_admin permission.
- Could probably do with some more descriptive messages if the user does not have permission.

Project deletion via frontend

---

src/backend/app/auth/roles.py
src/backend/app/organisations/organisation_crud.py
src/backend/app/organisations/organisation_routes.py
src/backend/app/projects/project_routes.py
src/backend/app/submissions/submission_routes.py
src/backend/app/tasks/tasks_routes.py

Fixes #1153 
This PR adds mapper role as a dependency.

Implement Mapper role

---

src/backend/app/config.py
src/backend/app/db/db_models.py
src/backend/app/db/postgis_utils.py
src/backend/app/main.py
src/backend/app/projects/project_crud.py

- Pyright shows a lot of errors because SQLAlchemy columns cannot be assigned Python variable types.
- A fix is to manually cast the columns: https://github.com/microsoft/pylance-release/issues/837#issuecomment-778873048

Cast all fields for sqlalchemy with python types

---

src/backend/app/config.py
src/frontend/src/components/createnewproject/ProjectDetailsForm.tsx
src/frontend/src/components/createnewproject/validation/CreateProjectValidation.tsx
src/frontend/src/components/editproject/validation/EditProjectDetailsValidation.ts
src/frontend/src/store/slices/CreateProjectSlice.ts
src/frontend/src/store/types/ICreateProject.ts
src/frontend/src/views/CreateOrganisation.tsx

Related to #966
- The backend to use organisation ODK credentials was in place.
- I added the frontend part.
- This PR also includes some tweaks to the organisation creation form.
Notes:
- The org creation form isn't perfect & probably needs a tweak at some point.
**Default**:
**Use custom credentials checked**:
**Invalid url check**:
**Updated organisation creation form**:
**Error if the user does not provide creds & the org does not have default creds configured**:
- 📝 Use descriptive commit …

Use default organisation credentials frontend implementation 

---

src/backend/app/tasks/tasks_routes.py

We're encountering an issue with updating the task status following the implementation of the mapper role in this endpoint. In this PR, I've made adjustments by removing the 'user' from User Schema from requests and instead utilizing current_user, which invokes the mapper dependency to retrieve the user_id.

update: task status update endpoint to adjust mapper role

---

src/backend/app/db/db_models.py
src/backend/app/s3.py
src/backend/app/submissions/submission_crud.py

- Fixes #1170 
This PR solves the issue of submissions not being update to s3. while checking last submission there needs to be object created in s3 fmtm-data bucket. But if there are not any submissions in s3 the ValueError was raised from s3 which didn't allow to add obj to s3 further. So instead of raising error 'None' is returned.

Fix update submissions in s3

---

src/frontend/src/components/createnewproject/UploadArea.tsx

- Fix #1175 
This PR adds validation to uploaded file on uploadArea step of create project where error is shown in case of invalid geojson.

Fix aoi file upload

---

src/frontend/src/components/ProjectSubmissions/ProjectInfo.tsx
src/frontend/src/components/ProjectSubmissions/SubmissionsInfographics.tsx
src/frontend/src/shared/AssetModules.js
src/frontend/src/views/ProjectSubmissions.tsx

-
UI enhancements for card section of  project submission page.
Before: 
After:

Fix project submission card UI

---

src/backend/app/db/postgis_utils.py

input_geojson_type was saved with value 'True' or 'False' instead of geojson type.
This PR addresses this issue ensuring feature type is properly saved.
N/A

Fix: Ensure GeoJSON Feature Type is Properly Saved

---

src/backend/app/auth/roles.py
src/backend/app/projects/project_deps.py
src/backend/app/tasks/tasks_routes.py
src/frontend/src/api/ProjectTaskStatus.js
src/frontend/src/components/DialogTaskActions.jsx

- Fixes #1207 
This PR addresses the issue of updating task status, passed project_id as a query from frontend.
Fixed some linting errors related to roles.
N/A

refactor: Update task status (hot fix)

---

src/frontend/src/components/ManageProject/EditTab/FormUpdateTab.tsx
src/frontend/src/components/ManageProject/EditTab/index.tsx
src/frontend/src/components/ProjectSubmissions/TaskSubmissions.tsx
src/frontend/src/models/submission/submissionModel.ts

- Fix #1202
- Fix #1203 
This PR covers following works: 
1. Remove Select Dropdown of form-category in order to restrict user to edit form-category
2. Search functionality add to search task from list of tasks.

Fix minor project issues

---

src/backend/app/organisations/organisation_crud.py
src/backend/app/organisations/organisation_routes.py

- #1215 
This PR includes a new end point that returns details of unapproved organizations so that the super admin can view the details of them and decide whether to accept or reject the organisation.
N/A
Check Checklist before requesting a review
✅ Provide tests for your changes.

Api returning details of unapproved organisation.

---

src/backend/app/projects/project_crud.py
src/backend/pdm.lock
src/backend/pyproject.toml

Fixes #1187
@manjitapandey 
- Data extracts were being generated using ST_Within for linestrings, so they were omitted.
- Disabling that uses ST_Intersects instead, which is what we want.
- The parsing was improved and fixed in the latest osm-rawdata release.
- The task splitting was improved to include all required tags in the latest fmtm-splitter release.
Highway extract:
Religious sites extract:
Waterway extract:
(note because clipping is no longer active - we use ST_Intersects - the entire river is provided, extending outside the AOI)
Health centre extract:
(note there are no health centers, so nothing is displayed. In this case we should display an error to the user @manjitapandey, something like:
'There is no data of that type within the provided area').
- 📖 Read the FMTM …

Fix data extract generation and task splitting with polylines

---

src/backend/app/projects/project_schemas.py

- Fixes #1201 
The project update schema is changed to `BaseModel` instead of inheriting the `ProjectIn` model.
N/A
✅ Provide tests for your changes.

Update project schema to allow edit only required fields

---

src/backend/app/organisations/organisation_schemas.py

- Fixes #1214 
This change adds approve details to the organizations list to allow super admins to review them from all organisations.
N/A
Check Checklist before requesting a review

Added approve detail in get organisation response

---

src/backend/app/organisations/organisation_routes.py

Unapproved organizations were unable to delete.
This PR fixes this issue. `Deps` is removed where the organization is checked to see if it exists or not and if it is approved or not.
N/A

Endpoint to delete unapproved organisation

---

src/backend/app/db/postgis_utils.py
src/backend/app/projects/project_routes.py

- Better handling of flatgeobuf to geojson generation in the database.
- Improves filename of extracted geojson.
- Create fgb with spatial index by default.
- Does NOT fix #1221 however, as an upstream issue with geometry type identification was discovered.

Improve flatgeobuf loading and generation

---

src/frontend/package.json
src/frontend/pnpm-lock.yaml
src/frontend/src/api/task.ts
src/frontend/src/components/ManageProject/EditTab/FormUpdateTab.tsx
src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx
src/frontend/src/components/common/Dropdown.tsx
src/frontend/src/components/common/Modal.tsx
src/frontend/src/components/common/Select.tsx
src/frontend/src/shared/AssetModules.js
src/frontend/src/utilities/PrimaryAppBar.tsx

- Fix #1228
This PR contains following works: 
1. Fix file extension on form update
2. Fix navbar tab selection: Explore Project & Manage Organization 
3. Submission Page crash due to dynamic header/data fix

Fix project org UI issues

---

src/backend/app/projects/project_schemas.py

Bbox is required to operate in JOSM, which was missing.
This PR adds the bbox to read_project
N/A

Add bbox in read project's outline

---

src/backend/app/projects/project_crud.py
src/backend/app/projects/project_deps.py
src/backend/app/projects/project_routes.py
src/backend/app/submissions/submission_crud.py
src/backend/app/submissions/submission_routes.py
src/backend/app/tasks/tasks_routes.py

There was an issue where task_ids weren't being saved to the features table, due to which features were not found in the task boundary, resulting in upload_media being false.
Data extracts not seen in: 
- project_info page while selecting a task.
- odk_collect 
This PR addresses this issue by adding db commit just after bulk inserting features into the database.
It also includes the refactoring of repeated odk_credentials into a single function.
N/A
- 📗 Update any …

Fix generate app user, media upload to odk central

---

src/backend/app/submissions/submission_crud.py
src/backend/app/submissions/submission_routes.py

`You cannot use AsyncToSync in the same thread as an async event loop - just await the async function directly.`
async_to_sync is not working in this specific function.
I think its better to use the async function rather than the sync function, so I just changed sync to the async function, which works as expected. 
N/A

Fix download submissions in csvs

---

src/frontend/src/components/organisation/OrganizationCardSkeleton.tsx
src/frontend/src/views/Home.jsx
src/frontend/src/views/Organisation.tsx

- fixes #1257 
This PR implements a skeleton loader in manage organizations page when organizations are being fetched.

Feat(manage organizations)/implement skeleton while loading

---

src/backend/app/db/postgis_utils.py
src/backend/app/projects/project_routes.py

Fixes #1145
- Handle parsing geojson with nested GeometryCollection.
- If the users uploads a valid geojson **with road/waterway/aeroway/railway linestring features**, task splitting will work.

Fix task splitting with custom data extract

---

src/backend/app/auth/roles.py

- We need to allow users to test FMTM during the public beta, which normally requires org admin permission.
- Bypass that for one specific organisation.

Allow public project creation during public beta

---

src/frontend/src/api/Project.js
src/frontend/src/components/MapComponent/OpenLayersComponent/LayerSwitcher/index.js
src/frontend/src/components/ProjectDetailsV2/MapControlComponent.tsx
src/frontend/src/components/common/PieChart.tsx
src/frontend/src/views/ProjectDetailsV2.tsx

This PR comprises the following works done: 
1. Generate mbtiles button add on `projectDetails` map
2. Loading state to `false` on `getProjectById` error & display toast
3. Piechart progress percentage shown on legend

Feat add mbtiles btn, UI enhancements

---

src/backend/app/tasks/tasks_routes.py

- Updating the xmlFormId (i.e. odk form id) in ODK Central caused a bug in extracting task feature counts.
- Hotfix direct merge to main. Will cherry-pick into staging/dev.

HOTFIX task features-count endpoint

---

src/frontend/src/components/createnewproject/SplitTasks.tsx
src/frontend/src/store/types/ICreateProject.ts

Use of useAppSelector from `reduxTypes` rather than `CoreModules` to enforce TS types.

fix splitTasks: TS types add

---

src/backend/app/submissions/submission_crud.py

The submissions were not updated in submissions table.
`xform` is updated to correctly match with odk-central. It solves the issue for new projects. Old projects with an old xform format fail to update the submissions.
N/A

Update xform to fetch submissions

---

src/frontend/src/components/MapComponent/OpenLayersComponent/Layers/VectorLayer.js
src/frontend/src/components/ProjectDetailsV2/ProjectInfo.tsx
src/frontend/src/components/ProjectSubmissions/TaskSubmissionsMap.tsx

This PR covers the following things:
1. ProjectDetailsPage - height of the container fix to avoid scrollbar
2. Map Feature - cursor-pointer on feature hover
3. TaskSubmissionsMap - don't show popup if tasks length is zero
1.

Project details improve UI responsiveness

---

README.md

Updated project creation workflow
Updated the documentation on project creation workflow

Update project creation workflow on README.md

---

src/frontend/src/components/ProjectDetailsV2/TaskSectionPopup.tsx
src/frontend/src/components/ProjectSubmissions/ProjectInfo.tsx
src/frontend/src/components/createnewproject/ProjectDetailsForm.tsx
src/frontend/src/models/project/projectModel.ts
src/frontend/src/views/SubmissionDetails.tsx

Ticket number, link, or description.
This PR fixes / adds the following things: 
1. On file btn click on tasksPopup, redirect to submissions-table with filters applied
2. Remove organizations add button besides organizations list on step 1 of project creation
3. Nav Links(routes) add to submission instance page

Fix project buttons

---

src/frontend/src/components/MapComponent/OpenLayersComponent/Layers/VectorLayer.js

This PR removes the layer hover effect code leading blank map issue.

fix vectorLayer: remove hover effect code leading screen blank issue

---

src/frontend/src/components/createnewproject/SplitTasks.tsx
src/frontend/src/components/createnewproject/UploadArea.tsx

This PR adds an edit AOI button to the MapControlComponent of uploadArea section on project creation to toggle  modify AOI.

feat uploadArea: edit AOI btn add

---

src/backend/pdm.lock
src/backend/pyproject.toml

- Related to issue #1351 
This PR updates the latest version of fmtm splitter, which is version 1.2.1, fixing the issue of splitting by square.

Updated the version of fmtm-splitter -> 1.2.1

---

src/frontend/src/components/ManageProject/EditTab/FormUpdateTab.tsx

- Related to #1308
This PR adds validation to the form update section.

Fix update form validation

---

src/frontend/src/api/Project.js
src/frontend/src/api/ProjectTaskStatus.js
src/frontend/src/utilities/CustomDrawer.jsx
src/frontend/src/utilities/DebugConsole.tsx
src/frontend/src/views/ProjectDetailsV2.tsx

This PR separates the debug console to a separate component and makes it accessible to `project-details` page as well.
Since task is not being updated in mobile UI and mbtiles is also not being generated. @spwoodcock, for testing purpose I am merging this PR. 

Test project details mobile

---

src/frontend/src/components/Activities.jsx
src/frontend/src/components/ActivitiesPanel.jsx
src/frontend/src/components/DialogTaskActions.jsx
src/frontend/src/components/GenerateBasemap.jsx
src/frontend/src/components/ProjectDetailsV2/ActivitiesPanel.tsx
src/frontend/src/components/ProjectDetailsV2/Comments.tsx
src/frontend/src/components/ProjectDetailsV2/ProjectOptions.tsx
src/frontend/src/components/ProjectDetailsV2/TaskSectionPopup.tsx
src/frontend/src/components/ProjectSubmissions/ProjectInfo.tsx
src/frontend/src/components/ProjectSubmissions/SubmissionsInfographics.tsx
src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx
src/frontend/src/components/createnewproject/SplitTasks.tsx
src/frontend/src/components/home/ExploreProjectCard.tsx
src/frontend/src/components/home/ProjectListMap.tsx
src/frontend/src/views/ManageProject.tsx
src/frontend/src/views/ProjectDetailsV2.tsx
src/frontend/src/views/ProjectSubmissions.tsx
src/frontend/src/views/SubmissionDetails.tsx
src/frontend/src/views/Submissions.tsx
src/frontend/src/views/Tasks.tsx

- Related to #1386
This PR removes the encoded Id from the URL of the pathname.  

Fix remove encoded url

---

src/frontend/src/api/CreateProjectService.ts
src/frontend/src/api/Project.js
src/frontend/src/api/ProjectTaskStatus.js
src/frontend/src/components/ManageProject/EditTab/FormUpdateTab.tsx
src/frontend/src/views/ProjectDetailsV2.tsx

- Ready for #1308
This PR adds api fetch for project-form validation.

Fix formvalidation UI enhance

---

src/frontend/src/components/ManageProject/EditTab/ProjectDescriptionTab.tsx
src/frontend/src/components/common/Select.tsx
src/frontend/src/components/common/TextArea.tsx
src/frontend/src/components/createnewproject/ProjectDetailsForm.tsx

- Related to #1400
- Related to #1402
- Related to #1403
This PR covers the following works done:
1. Add asterisk (required) to orgazation name select field
2. Add word limit of 200 characters to short-description text area on create/manage-project
3. ODK credential field not displaying issue fix
1. 
2. 
3.
- 📗 Update any related documentation and include any relevant …

Fix minor frontend bugs

---

src/backend/app/tasks/tasks_crud.py
src/backend/app/tasks/tasks_routes.py

There were missing arguments in get_project_task_history.
This PR updates the endpoint by adding necessary arguments.

Update task activity endpoint

---

src/backend/app/projects/project_crud.py

- Issue #1424
This PR addresses the issue where there was an extra `for` loop stacking the merged polygon, which was unnecessary. This change refactors the code using `mapping` instead of a loop, which is more efficient.
N/A

Refactor: merged multi polygon to single polygon

---

src/backend/app/tasks/tasks_crud.py
src/backend/app/tasks/tasks_routes.py
src/backend/app/tasks/tasks_schemas.py

The latest updated task status was at the bottom of the list in the response.
This PR removes the param project_id and uses task_id in the path, which directly fetches the task history of that particular task, returning a response in the order of the latest update, which is descending order by id of taskhistory.
```
[
{
"id": 151,
"action_text": "Status changed from MAPPED to LOCKED_FOR_VALIDATION by: svcfmtm",
"action_date": "2024-04-10T04:00:12.248890",
"username": "svcfmtm",
"profile_img": null,
"status": "LOCKED_FOR_VALIDATION"
},
{
"id": 150,
"action_text": "Status changed from LOCKED_FOR_MAPPING to MAPPED by: svcfmtm",
"action_date": "2024-04-10T03:59:22.988060",
"username": "svcfmtm",
"profile_img": null,
"status": "MAPPED"
},
{
"id": 134,
"action_text": "Status changed from READY …
```

Use task_id to get task_history

---

src/backend/app/db/postgis_utils.py
src/backend/app/projects/project_crud.py
src/backend/app/projects/project_routes.py
src/backend/app/tasks/tasks_routes.py
src/frontend/src/components/MapComponent/OpenLayersComponent/LayerSwitcher/index.js
src/frontend/src/components/ProjectDetailsV2/MapControlComponent.tsx
src/frontend/src/components/ProjectSubmissions/ProjectInfo.tsx
src/frontend/src/components/createnewproject/SplitTasks.tsx
src/frontend/src/components/home/ExploreProjectCard.tsx
src/frontend/src/components/home/ProjectListMap.tsx
src/frontend/src/routes.jsx
src/frontend/src/views/MainView.jsx
src/frontend/src/views/ManageProject.tsx
src/frontend/src/views/ProjectSubmissions.tsx
src/frontend/src/views/SubmissionDetails.tsx

- Fixes the `/projects/` endpoint that was not working.
- Add `/projects/features` that returns a feature collection for a specified BBOX (following OGC API Feature spec).
- Allows for integration with services like disaster.ninja by Kontur.
- Also refactored the frontend route `project_details` --> `project`.
- This was required to provide a link to external services such as `https://fmtm.hotosm.org/project/1`.
- Also updates endpoints to hide projects if visibility != 'PUBLIC'.
```json
{
"type": "FeatureCollection",
"features": [
{
"type": "Feature",
"geometry": {
"type": "Polygon",
"coordinates": [
[
[
85.299989,
27.714008
],
[
85.299989,
27.710892
],
[
85.304783,
27.710892
],
[
85.304783,
27.714008
],
[
85.299989,
27.714008
]
]
]
},
"properties": {
"link": …
```

Add /projects/features endpoint for project FeatureCollection (disaster.ninja integration)

---

src/backend/app/db/db_models.py
src/backend/app/projects/project_schemas.py
src/backend/migrations/003-add-tms-url.sql
src/backend/migrations/revert/003-add-tms-url.sql

- Feature #1429 
This PR adds a column `custom_tms_url` in the project table, further adding to the project creation workflow and project details.
N/A

Add custom TMS url in the project

---

src/frontend/src/api/ProjectTaskStatus.js
src/frontend/src/components/MapComponent/OpenLayersComponent/AsyncPopup/AsyncPopup.tsx
src/frontend/src/hooks/MapStyles.js
src/frontend/src/utilfunctions/getTaskStatusStyle.js
src/frontend/src/views/ProjectDetailsV2.tsx

- Related to #1453
This PR contains the following works: 
1. Display a dark black border if the user locks the task by themself.
2. Display a popup stating "_This task was locked by you_" if the task has been locked by themself.

Distinguish between tasks locked by the current user and tasks locked by others

---

src/backend/app/tasks/tasks_crud.py
src/backend/app/tasks/tasks_routes.py

- Issue #1482
This PR updates the endpoint `activity` using `task_ids` instead of `project_id`.

Use task ids to count validated and mapped status

---

.all-contributorsrc
src/frontend/src/components/DialogTaskActions.jsx
src/frontend/src/components/common/Modal.tsx
src/frontend/src/views/ProjectDetailsV2.tsx

- Related to #1476 
This PR adds a modal when the user clicks `Mark as fully mapped` in the tasks popup if all features are not mapped.

Prompt user if task area is not fully mapped on mark complete 

---

src/frontend/src/components/DialogTaskActions.jsx

This PR solves the same variable name conflict was raised resulting issue in task status update in dialogTaskActions.jsx.

fix(dialogTaskActions): same name variable conflict solve

---

src/backend/app/submissions/submission_routes.py

- Issue #1452 
This PR adds a new feature to download submissions from Odk Central in geojson file format.
N/A

Download submissions in geojson

---

src/backend/app/submissions/submission_crud.py
src/backend/app/submissions/submission_routes.py

- Issue #1502
- Issue #894 
- This PR updates and fixes the issue related to download submissions in csv or json file format
- Major refactoring is done removing redundant functions and endpoints
- Download submissions in csv and json need frontend works too(Dependent to frontend)
N/A

Download submissions(csv,json) and refactor all related submission endpoints

---

src/frontend/src/api/task.ts
src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx

- Related to #1521
This PR resolves the download of project submissions JSON and CSV according to the changes made on the backend.

Fix submission download

---

src/frontend/package.json
src/frontend/pnpm-lock.yaml
src/frontend/src/App.tsx

Related #942
- Built on React v19 PR #1545, so required that to be merged first (actually only 2 lines of new code in this PR).
- Updated the Matomo code to use a @hotosm/ui web component instead.
- Also includes a user accept/disagree notice, which is required by law.

Use Matomo tracking web component, with accept/disagree prompt

---

.pre-commit-config.yaml
src/backend/tests/test_projects_routes.py

This PR introduces a `test_update_project` test to confirm that project metadata can be updated successfully.
[](url)

Test coverage for update project route

---

src/frontend/src/views/ProjectDetailsV2.tsx

- Related to #1568
This PR contains work to solve the issue of task layer color not being updated on updating the task.
[Screencast from 13-6-24 09:43:18 पूर्वाह्न +0545.webm](https://github.com/hotosm/fmtm/assets/81785002/1d95095b-4afe-40b5-88be-2b950192a8be)

fix(projectDetailsV2): taskLayer color not update issue solve

---

src/frontend/src/components/ProjectSubmissions/TaskSubmissions.tsx

- Related to #1520
This PR fix task not being displayed in the task card list.

Display task card even if no features in a task

---

src/frontend/package.json
src/frontend/src/components/common/CustomTable.tsx

- Related to #1566
This PR fix the table header actions not being fixed.

fix(customTable): classname add

---

src/frontend/src/api/CreateProjectService.ts
src/frontend/src/components/createnewproject/SplitTasks.tsx

- Related to #1577
This PR fix create project submit btn issue by disabling the button until page redirection to project details page.
--

fix(createProject): disable submit btn until redirection to details page

---

src/frontend/src/views/SubmissionDetails.tsx

- Related to #1581
This PR fix issue on not able to update review state.
[Screencast from 21-6-24 02:33:41 अपराह्न +0545.webm](https://github.com/hotosm/fmtm/assets/81785002/8b618115-1cf5-4396-b3a9-5b430d7b805a)

fix(submissionDetails): retrieve task_id directly from submissionDetails

---

src/backend/app/central/central_crud.py
src/backend/app/central/central_routes.py
src/backend/app/projects/project_crud.py

- Issue No. #1461 
- This PR creates a new endpoint `refresh_appuser_token` which allows to create an app user if it has not created already , if it exists then it deletes it and creates again and updates the `odk_token` in the database.
- refactors existing code to create app user during project file generation to use this new function.
N/A
- 📗 Update any related …

Added new endpoint to refresh the app user token

---

src/backend/tests/test_projects_routes.py

This PR covers `project/summaries` and `projects/project_id` endpoints with tests by comparing response data with project fixture data.
Mock larger data to test pagination

Test coverage of read project summaries and read project by id endpoints

---

src/backend/app/projects/project_crud.py
src/backend/app/projects/project_routes.py
src/backend/app/projects/project_schemas.py
src/backend/tests/conftest.py
src/backend/tests/test_projects_routes.py
src/frontend/src/components/createnewproject/ProjectDetailsForm.tsx
src/frontend/src/components/createnewproject/SplitTasks.tsx
src/frontend/src/store/types/ICreateProject.ts

Fix parsing of hashtags (allow separation by comma, space, or semicolon)

---

src/frontend/src/components/ProjectDetailsV2/FeatureSelectionPopup.tsx

- Related to #1587 
This PR contains works to allow any user to map a feature even if the task is locked by anyone.

fix(featureSelectionPopup): allow any users to map feature

---

src/backend/app/auth/osm.py
src/backend/app/projects/project_schemas.py

N/A
This PR updates 
- the project detail response adding project created date
- the expiry set for access token to 1 hour (3600 seconds)
N/A

Added created date on the project response

---

src/frontend/src/components/MapLegends.tsx
src/frontend/src/components/common/Accordion.tsx
src/frontend/src/views/ProjectDetailsV2.tsx

- Related to #1590
This PR fix the map legend of project details page according to the reduced map legend design.

fix(frontend): avoid map legend overlay on small screens (dynamic size)

---

src/backend/app/auth/auth_routes.py
src/backend/app/auth/osm.py

- Issue #1652
This PR updates the expiry of access token to 1 day for smooth user experience.
N/A

Increased expiry of access token to 1 day

---

docs/manuals/Load_tiles_on_ODK.md
src/backend/app/submissions/submission_routes.py

- Issue #1676 
This PR fix the mentioned issue where there was an extra param task id which is not necessary now to get the project submissions and filter it.
N/A

Fix submssions not loaded in the submission table

---

src/backend/app/central/central_crud.py
src/backend/pdm.lock
src/backend/pyproject.toml

Related to https://github.com/hotosm/fmtm/issues/1668
- Upgrade osm-fieldwork, including fix to mbtile generation.
- Commented out usage of CSVDump until replaced by ODKParsers: https://github.com/hotosm/fmtm/issues/1646

Upgrade osm-fieldwork --> 0.13.0 for mbtile fix

---

src/frontend/src/components/ManageProject/EditTab/FormUpdateTab.tsx

- Related to #1536
This PR fix the loading state not being shown on form update submit button click.

Button click feedback on form update

---

src/frontend/src/api/Project.js

- Related to #1582
This PR contains work to display dynamic error message generated by the backend.

fix(project): display error generated on the backend

---

src/backend/app/central/central_crud.py
src/backend/app/projects/project_routes.py
src/backend/tests/test_projects_routes.py
src/frontend/src/components/createnewproject/SplitTasks.tsx

To be merged along with https://github.com/hotosm/fmtm/pull/1693
- Added better error message for user if no submissions available on download.
- Updated `create_project` endpoint --> `create-project`

Improve error message if no project submissions present

---

src/backend/app/db/postgis_utils.py
src/backend/app/submissions/submission_routes.py

- Issue #1648
This PR determines the overlap_percentage and returns tags and both geometries (osm and data extract submission) if overlap is less than 90% else returns data extracts only with tags from osm.
```
{
"type": "FeatureCollection",
"features": [
{
"type": "Feature",
"id": 649473870,
"geometry": {
"type": "Polygon",
"coordinates": [
[
[
85.2967728,
27.7231252
],
[
85.2968913,
27.7230746
],
[
85.2968826,
27.7230544
],
[
85.2969189,
27.7230362
],
[
85.2969548,
27.7231095
],
[
85.2968588,
27.7231569
],
[
85.2968724,
27.7232016
],
[
85.2968109,
27.723207
],
[
85.2967728,
27.7231252
]
]
]
},
"properties": {
"osm_type": "ways_poly",
"version": 5,
"tags": {
"source": "METEOR Kathmandu Field Survey 2019",
"building": "mixed_use",
"roof:shape": "monopitch",
"building:age": "post_2000", …
```

Determine overlap percentage for the conflation

---

src/backend/tests/test_task_routes.py

Related to Issue #1614 
Added a test to verify that the task status can be updated correctly and that the 
`POST /tasks/{task_id}/new-status/{status} endpoint` returns the expected results.

Test coverage for updating the task status endpoint

---

src/frontend/src/api/SubmissionService.ts
src/frontend/src/components/ProjectDetailsV2/Comments.tsx
src/frontend/src/components/ProjectSubmissions/ProjectInfo.tsx
src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx
src/frontend/src/components/ProjectSubmissions/UpdateReviewStatusModal.tsx
src/frontend/src/components/SubmissionInstance/SubmissionComments.tsx
src/frontend/src/components/common/Accordion.tsx
src/frontend/src/shared/AssetModules.js
src/frontend/src/store/slices/SubmissionSlice.ts
src/frontend/src/store/types/ISubmissions.ts
src/frontend/src/views/SubmissionDetails.tsx

- Related to #1617
This PR contains the following works:
1. Project Submissions UI enhancement
2. Submission comment integration

Add working submission comments to submission page 

---

src/frontend/src/api/ProjectTaskStatus.ts
src/frontend/src/store/slices/ProjectSlice.ts

- Related to #1605
This PR fix the dialog task task_status text not being updated.
[Screencast from 29-7-24 03:29:23 अपराह्न +0545.webm](https://github.com/user-attachments/assets/5ccc6d2a-6a22-45f8-8857-5c995966116d)

Update task dialog task_status text on task update

---

src/backend/app/projects/project_crud.py
src/backend/app/projects/project_routes.py
src/backend/app/s3.py

Delete s3 objects on project deletion

---

src/backend/app/projects/project_crud.py
src/backend/pdm.lock
src/backend/pyproject.toml

Fixes #1697
- Also fixes PMTile generation when using custom TMS provider, which didn't work always previously.
- Now we use the `oam` provider for osm_fieldwork.basemapper.
- Generate pmtiles + mbtiles with various providers.
- A custom TMS should be tested for both pmtiles + mbtiles too.

Fix xlsform question ordering + pmtile generation when custom TMS

---

src/backend/pdm.lock
src/backend/pyproject.toml

Update osm-fieldwork --> v0.14.2 for TMS URL validator

---

src/frontend/e2e/createproject.spec.ts
src/frontend/src/components/MapComponent/OpenLayersComponent/LayerSwitcher/index.js
src/frontend/src/components/ProjectDetailsV2/ProjectOptions.tsx
src/frontend/src/components/createnewproject/DataExtract.tsx
src/frontend/src/components/createnewproject/SelectForm.tsx
src/frontend/src/components/createnewproject/SplitTasks.tsx
src/frontend/src/components/createnewproject/validation/DataExtractValidation.tsx
src/frontend/src/constants/StepFormConstants.ts
src/frontend/src/constants/blockerUrl.ts
src/frontend/src/routes.jsx
src/frontend/src/views/CreateNewProject.tsx

- Related to #1723
This PR rewords `Data Extract` to `Map Features`.

Reword Data Extract to Map Features 

---

src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx
src/frontend/src/environment.ts

- Related to #1654
- Update Texts

Correct text in validation table to show the marked as validated

---

src/frontend/src/views/SubmissionDetails.tsx

- Related to #1791
If new map feature added, zooms the map to that newly added geopoint.

feat(submissionDetails): if new feature point add then zoom to the point

---

src/frontend/e2e/01-create-new-project.spec.ts
src/frontend/e2e/02-mapper-flow.spec.ts

Frontend test case fail on CI
CI:
Test case pass on local:
The frontend test case on the CI seems to fail and desired changes are not up on the staging. 
Temporarily commenting out the frontend test cases to get changes up on stage. 
NOTE: The test case seems to work on local perfectly.

fix(e2e): comment out test until CI fixed

---

src/frontend/src/api/Files.ts
src/frontend/src/components/QrcodeComponent.tsx

- Related to #1812
This PR contains the following fix: 
- Reduce QR code skeleton loader size
- Remove Generate QR code cleanup function to make QR code visible on initial render after project creation redirection

Fix QR code issue

---

src/backend/pdm.lock
src/backend/pyproject.toml

- Issue: #1809 
This PR updates the version of `osm-fieldwork` from `0.16.7` to `0.16.8` with fixes of multiple duplicates of same choice fields such `yes_no` choices.
N/A

Update osm-fieldwork  -> 0.16.8

---

src/frontend/src/api/Project.ts
src/frontend/src/api/SubmissionService.ts
src/frontend/src/components/DialogTaskActions.tsx
src/frontend/src/components/ProjectDetailsV2/FeatureSelectionPopup.tsx
src/frontend/src/components/ProjectSubmissions/SubmissionsInfographics.tsx
src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx
src/frontend/src/store/slices/SubmissionSlice.ts
src/frontend/src/store/types/ISubmissions.ts
src/frontend/src/views/ProjectSubmissions.tsx

- Related to #1843
This PR contains the following fixes: 
1. Redirect the user to the submissions page on the Lock for Validation button is click.
2. On the task marked validated from the submission table page, the task status changed to validated.
3. Parent task style changed immediately on the Map feature in ODK is click.
4. API should be integrated for Mapped vs Validated Task chart

Frontend Fixes after Backend Changes

---

src/mapper/src/lib/components/bottom-sheet.svelte
src/mapper/src/lib/components/event-card.svelte
src/mapper/src/lib/components/map/flatgeobuf-layer.svelte
src/mapper/src/lib/components/map/main.svelte
src/mapper/src/lib/utils/flatgeobuf.ts
src/mapper/src/routes/[projectId]/+page.svelte
src/mapper/src/store/tasks.svelte.ts
src/mapper/svelte.config.js
src/mapper/vite.config.ts

Extended the GeoJSON component from svelte-maplibre to create a FlatGeobuf component that can load from S3.
It deserialised to an GeoJSON in the end.
Now we can view the data extract on mapper frontend page load. The loading is constrained to a bbox, then geoms clipped down to the task area on click:

Add flatgeobuf maplibre component for loading features in mapper frontend

---

src/mapper/src/constants/enums.ts
src/mapper/src/lib/components/dialog-task-actions.svelte
src/mapper/src/lib/components/map/main.svelte
src/mapper/src/routes/[projectId]/+page.svelte
src/mapper/src/store/common.svelte.ts
src/mapper/src/store/tasks.svelte.ts
src/mapper/src/styles/button.css
src/mapper/static/assets/icons/three-dots.svg
src/mapper/vite.config.ts

- Related to #1853
This PR contains the following works done: 
- UI fix
- Task actions button requiring reload to sync with the task fix
- Code refactor
- Mapper Frontend: Build a mapper flow for first-time project load
[Screencast from 5-11-24 05:36:49 अपराह्न +0545.webm](https://github.com/user-attachments/assets/485825a9-8bc8-4c02-9574-f09536dc70f9)

Mapper frontend mapper flow

---

src/frontend/src/api/Submission.ts
src/frontend/src/components/common/ImageSlider.tsx
src/frontend/src/components/common/Modal.tsx
src/frontend/src/shared/AssetModules.js
src/frontend/src/store/slices/SubmissionSlice.ts
src/frontend/src/store/types/ISubmissions.ts
src/frontend/src/views/SubmissionDetails.tsx

- Related to  #1706
This PR contains API integration of `submission photos` API & `image-slider` component to visualize submission photos on the frontend.

Visualize submission photos on frontend

---

src/frontend/src/api/CreateProjectService.ts

- Related to #1859 
Fix replacing all additional entity geojson filename spaces with an underscore.

Replace all additional entity filename spaces with an underscore

---

src/frontend/src/components/ManageProject/EditTab/FormUpdateTab.tsx

- Related to #1798
Fix `xFormId` `undefined` on post `/projects/update-form`.

Fix xFormId undefined payload issue on form update

---

src/frontend/src/components/ProjectDetailsV2/ProjectOptions.tsx
src/frontend/src/components/ProjectDetailsV2/TaskSelectionPopup.tsx
src/frontend/src/components/QrcodeComponent.tsx
src/frontend/src/views/ProjectDetailsV2.tsx

- Related to #1818
QR code download option add to download options.

 Qr code download option add to download options

---

src/frontend/src/components/createnewproject/SplitTasks.tsx

- Related to #1782
This PR displays the total feature count that includes map feature + additional features on the split tasks section of the create project.

Display total number of features on split tasks section

---

src/backend/app/projects/project_routes.py

Fixes #1900
allow users to view project cards without logging in

fixes:  Projects aren't accessible to users without logging in #1900

---

src/frontend/src/components/createnewproject/SplitTasks.tsx

- Related to #1782
Display feature count of uploaded additional entity geojson.

Visualize additional entities feature counts

---

src/frontend/src/views/ProjectSubmissions.tsx

- Issue: #1923 
Removed the trailing slash from `activity` endpoint which was not exactly matching with backend endpoint.

Remove trailing slash from activity endpoint

---

src/backend/app/projects/project_schemas.py

Add organization_logo field to summaries API #1941
the logo field was missing in summary pydantic model.

feat(projects): add organisation_logo field to ProjectSummary model

---

src/mapper/src/routes/[projectId]/+page.ts

- Related to #1962
Clear user details from local storage if the user session expires
N/A

Clear local storage on user session expiration

---

src/frontend/src/components/home/ExploreProjectCard.tsx
src/frontend/src/store/slices/ThemeSlice.ts

Fixes #1942
- By no means a perfect solution, but getting this into the next release for easier access to the mapper frontend.
- It can be refined on by the design team / frontend refactoring later 👍 

Add 'Start Mapping' call to action button on homepage cards

---

src/mapper/src/lib/components/more/activities.svelte
src/mapper/src/routes/[projectId]/+page.svelte
src/mapper/src/store/tasks.svelte.ts

- Related to #1982 
- Replace task id with index in activities panel

Mapper: Replace task id with index on activities panel

---

src/backend/migrations/init/fmtm_base_schema.sql

- The fresh database creation during the test run was failing all the time due to improper configuration of the base schema blocking entire deployment of changes in fmtm dev server.
This PR updates the fmtm_base_schema migrations, adding public schema and handling already existing schema creation.
N/A

Refactor the fmtm_base_schema migrations file

---

src/backend/pyproject.toml
src/backend/uv.lock

- Issue: #1946 
This PR updates the version of osm-fieldwork to v0.17.0
N/A

Update the version of osm-fieldwork -> 0.17.0

---

src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx
src/frontend/src/components/home/ExploreProjectCard.tsx
src/frontend/src/models/home/homeModel.ts
src/mapper/package.json
src/mapper/pnpm-lock.yaml
src/mapper/src/lib/components/map/geolocation.svelte
src/mapper/src/lib/components/map/main.svelte
src/mapper/src/store/entities.svelte.ts

- Enhancement
- Spelling fix
- Replace short description with of description on home page
- Enhancement: use of polygon centroid instead of event coordinate for entities, handle geolocation state in store
- Spelling fix
- Use of short description instead of description on the home page

Minor frontend fix & enhancement

---

src/backend/app/central/central_crud.py

- Not an issue; initially submission_ids was added to `entity/status` endpoint only but later realised it also needed to be added to `entities/statuses` endpoint as per @NSUWAL123
- Added submission_ids in the fields while fetching entities data from odk.
N/A

Submission ids in entities statuses endpoint

---

src/frontend/src/store/slices/CreateProjectSlice.ts

- Additional feature geojson state of previously created project persists on project creation
- Clear additional feature geojson state after successful project creation
N/A

Clear additionalFeatureGeojson state after project creation

---

src/mapper/src/lib/components/dialog-entities-actions.svelte
src/mapper/src/routes/[projectId]/+page.svelte

- Related to #2044
- Task ID shown instead of task index on the latest task log
- Update the latest event log time every minute
- Auto lock task if the feature within the task is triggered to map
- Display Task index instead of task ID
- Update the latest event log time every minute

Automatic task lock on feature map & minor mapper frontend improvements

---

src/backend/app/db/enums.py
src/backend/app/db/models.py
src/backend/app/projects/project_routes.py
src/backend/app/projects/project_schemas.py
src/backend/migrations/002-create-geometry-log.sql
src/backend/migrations/init/fmtm_base_schema.sql
src/backend/migrations/revert/002-create-geometry-log.sql

- Migration of previous PR #2046 was failing due to missing migration file of geomstatus
This PR updates the migration 002 adding migration of geomstatus enum type. In addition, a delete api of geometry log is also created.
N/A

Create migration of geomstatus enum, delete geometries api

---

CONTRIBUTING.md
README.md

None
Fixes two very minor typos in the documentation
Not Applicable
Nope
I'd check to make sure no other files were accidentally changed through the Github PR interface.  I'd also recommend checking that automated tests pass.

Very minor typo fixes for documentation

---

src/backend/app/db/models.py
src/backend/app/submissions/submission_crud.py

- Related to: #1912 
Fixed numerous bugs. Refer to the linked issue for more details.

Sentry fixes

---

docs/manuals/mapping.md

added more screenshots on mapper guide
Example: Issue #921 
Added screenshots for mapping new feature and mapping existing feature in mapper's guide.

added more screenshots on mapper guide

---

src/backend/app/submissions/submission_crud.py
src/backend/app/submissions/submission_routes.py
src/backend/tests/test_submission_routes.py

- Related to: #1884 
also fixed username filter in submission table
add date range filter to submission table and download (json and zip)
refactor username filter in submission table

feat: add filters for submission date in submission table and downloads

---

src/backend/app/db/models.py
src/backend/tests/conftest.py
src/backend/tests/test_organisation_routes.py

- Related to: #2062 
Added pytest cases for organisation module:

Test cases for organisation

---

src/Dockerfile.ui.debug
src/Dockerfile.ui.prod
src/frontend/package.json
src/mapper/package.json

Hopefully fixes #2087
- Updated pnpm version to latest stable, in an attempt to fix segfault issue in linked PR.
- If this doesn't solve it, then we need to dig into dependencies.
- The default version of pnpm used is now **9.15.4** and probably mandatory due to corepack and `packageManager` in package.json. (cc @NSUWAL123)

Update pnpm version to latest stable 9.15.4

---

src/frontend/src/api/task.ts
src/frontend/src/components/ProjectSubmissions/ProjectSubmissionsSkeletonLoader.tsx
src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx
src/frontend/src/components/common/CustomDatePicker.tsx
src/frontend/src/components/common/DateRangePicker.tsx
src/frontend/src/components/common/Select.tsx
src/frontend/src/index.css
src/frontend/src/store/types/ISubmissions.ts

- Related to #1884
Date range filter add to submissions table

Submissions date range filter

---

docs/dev/Backend.md

docker-compose was replaced by "docker compose"
N/A
Updates one place in docs showing newer way of using docker compose to pull 
N/A
N/A
Follow new step in Backend dev guide

Update Backend.md documentation

---

src/mapper/src/lib/components/bottom-sheet.svelte
src/mapper/src/lib/components/map/layer-switcher.svelte
src/mapper/src/lib/components/map/legend.svelte
src/mapper/src/lib/components/map/main.svelte

- Related to #2048
- Update legend & layer-switcher UI
- Show feature-level legend
- Refactor legend & layer-switcher component

Refactor mapper legend & layer-switcher

---

src/mapper/src/lib/components/map/main.svelte
src/mapper/src/lib/odk/collect.ts
src/mapper/src/routes/[projectId]/+page.svelte

- Related to #1979 & #2105
This PR contains the following works: 
- solve previous flaky polygon drawing
- allow to modify the drawn polygon
- provide options to discard and proceed to ODK after drawing the feature
- add `task_id` param to ODK intent URL
[Screencast from 27-1-25 05:19:52 अपराह्न +0545.webm](https://github.com/user-attachments/assets/01e8db4c-d824-4547-ac3f-85c0d0b07e7b)
[Screencast from 27-1-25 05:21:20 अपराह्न +0545.webm](https://github.com/user-attachments/assets/33a03eac-bfb5-4246-97cb-26ad2dd95ef5)

Fix new feature polygon draw

---

src/frontend/src/views/SubmissionDetails.tsx

- Related to #2105
- Fix missing bracket on warmup
- Not showing new_feature object making UI cluttered and already present on xLocation

Refactor submission details page

---

src/backend/app/db/models.py
src/backend/app/users/user_routes.py
src/backend/app/users/user_schemas.py

- Related to: #2093 
Allow admins to change the global role of a user

Add endpoint to change global user roles

---

src/backend/app/db/models.py
src/backend/app/users/user_crud.py
src/backend/app/users/user_routes.py
src/backend/app/users/user_schemas.py

- Related to: #2123 
Added pagination and search functionality to existing user list api

Add pagination and search functionality to user list api

---

src/frontend/package.json
src/frontend/pnpm-lock.yaml

Fixes #2111 
- Info in related issue.
- Also took the opportunity to move React v19 from RC to stable release version.

Upgrade react to latest v19 stable + mui icons fixing frontend build

---

src/frontend/src/components/createnewproject/ProjectDetailsForm.tsx

… create
Fixes #2128
- Also updated the code with some comments and separated the odk creds component for clarity.

Fix logic allowing for custom odk server creds during project creation

---

.all-contributorsrc
src/frontend/src/utilfunctions/getTaskStatusStyle.ts

- locked for mapping task color fix

Fix locked for mapping task color

---

src/frontend/src/components/createnewproject/ProjectDetailsForm.tsx
src/frontend/src/components/createnewproject/validation/CreateProjectValidation.tsx

- Related to #2137
- Update ODK credentials validation (revert to the previous approach until new approach finalized)
N/A

Update setting ODK credentials logic 

---

src/backend/app/central/central_crud.py
src/backend/app/projects/project_routes.py
src/frontend/src/components/createnewproject/ProjectDetailsForm.tsx

- Later realised that it will be better to provide response with newly created entity_id from create-entity api so that the frontend can use that entity_id to redirect to odk collect.
This PR updates the 200 response to :
```json
{
"uuid": "c3d19418-e08d-4bd2-8188-e2d0e59e7479",
"creatorId": 13,
"conflict": null,
"createdAt": "2025-02-05T07:27:43.447Z",
"updatedAt": null,
"deletedAt": null,
"currentVersion": {
"current": true,
"label": "Task 1 Feature 364736488",
"creatorId": 13,
"userAgent": "Python/3.12 aiohttp/3.11.2",
"data": {
"tags": "",
"osm_id": "364736488",
"status": "0",
"task_id": "1",
"version": "1",
"geometry": "27.740007615 85.318219362 0.0 0.0;27.740007615 85.31816176 0.0 0.0;27.739819376 85.31816176 0.0 0.0;27.739819376 85.318219362 0.0 0.0;27.740007615 85.318219362 0.0 …
```

Update entity creation response

---

src/frontend/src/api/SubmissionService.ts
src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx
src/frontend/src/store/slices/SubmissionSlice.ts
src/frontend/src/store/types/ISubmissions.ts

- Related to #2165
- Download submission as GeoJson option add
[Screencast from 12-2-25 05:56:53 अपराह्न +0545.webm](https://github.com/user-attachments/assets/fb89ef1e-66f4-42e5-9822-4b5715ecedf8)

Submission GeoJson download

---

src/mapper/src/routes/[projectId]/+page.svelte

- Related to #2182
- Close confirmation dialog on proceed click
[Screencast from 13-2-25 09:24:32 पूर्वाह्न +0545.webm](https://github.com/user-attachments/assets/bfcbf04f-8072-4f1f-adef-0ba1df4d649f)

Confirmation dialog close on redirection to ODK

---

src/frontend/src/components/createnewproject/SplitTasks.tsx

Task splitted geojson download

---

src/frontend/src/components/MapComponent/OpenLayersComponent/AsyncPopup/AsyncPopup.tsx
src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx
src/frontend/src/components/SubmissionMap/SubmissionInstanceMap.tsx
src/frontend/src/utilfunctions/extractGeojsonFromObject.ts
src/frontend/src/views/SubmissionDetails.tsx

- Related to #2180
- Display popup showing geometry label on feature click

Popup showing geometry label on submission details page

---

src/frontend/src/api/CreateProjectService.ts
src/frontend/src/api/OrganisationService.ts
src/frontend/src/api/Project.ts
src/frontend/src/api/SubmissionService.ts
src/frontend/src/api/TaskEvent.ts
src/frontend/src/api/User.ts
src/frontend/src/components/CreateEditOrganization/CreateEditOrganizationForm.tsx
src/frontend/src/components/DialogTaskActions.tsx
src/frontend/src/components/GenerateBasemap.tsx
src/frontend/src/components/ManageProject/EditTab/ProjectDescriptionTab.tsx
src/frontend/src/components/ProjectDetailsV2/Comments.tsx
src/frontend/src/components/common/UploadArea.tsx
src/frontend/src/components/createnewproject/DataExtract.tsx
src/frontend/src/components/createnewproject/SelectForm.tsx
src/frontend/src/components/createnewproject/SplitTasks.tsx
src/frontend/src/components/createnewproject/UploadArea.tsx
src/frontend/src/models/home/homeModel.ts
src/frontend/src/store/slices/CommonSlice.ts
src/frontend/src/store/slices/HomeSlice.ts
src/frontend/src/store/types/IHome.ts
src/frontend/src/utilfunctions/Geolocation.ts
src/frontend/src/utilities/CustomDrawer.tsx
src/frontend/src/utilities/PrimaryAppBar.tsx
src/frontend/src/views/ManageUsers.tsx
src/frontend/src/views/PlaywrightTempLogin.tsx
src/frontend/src/views/ProjectDetailsV2.tsx

- Related to #2191
- Refactor CommonSlice.SetSnackBar action
- Remove HomeSlice.SetSnackBar action and its related call, type, state
N/A

Refactor SetSnackBar action

---

src/frontend/src/utilfunctions/extractGeojsonFromObject.ts

- Related to #2195
- Differentiate between a Polygon & LineString during JavaRosa string conversion to a feature

Fix: Submission feature visualization

---

nginx/templates/dev/minio.conf.template
src/backend/app/db/models.py
src/backend/app/db/postgis_utils.py
src/backend/app/submissions/submission_crud.py
src/backend/migrations/003-remove-submission-photos.sql
src/backend/migrations/init/fmtm_base_schema.sql
src/frontend/src/components/common/ImageSlider.tsx
src/frontend/src/utilities/CustomDrawer.tsx
src/frontend/src/views/SubmissionDetails.tsx
src/mapper/src/constants/drawerItems.ts

Follow on from https://github.com/hotosm/fmtm/pull/1894
Related to https://github.com/hotosm/fmtm/issues/1875
Related to https://github.com/hotosm/fmtm/issues/1701
Related to https://github.com/hotosm/fmtm/issues/1706
- Working return of S3 submission photos via API (pre-signed URLs - works for both public and private buckets).
- Finalise with a little tweak to the local dev minio proxy config - allowing testing locally without invalid signatures on pre-sign.
- Tweak frontend component to accept new dict response.
- Create submissions with photos
- View on the submission detail page
- 👷‍♀️ Create small PRs. In most …

Finalise S3 submission photos on backend + frontend

---

src/frontend/src/components/ProjectDetailsV2/TaskSelectionPopup.tsx

- Related to #2213
- Update task state label on task popup

Update task popup task state label

---

src/mapper/src/lib/components/dialog-entities-actions.svelte

- Related to #2179 
Update submission length check condition
N/A

Fix submission comments not visible

---

src/frontend/src/components/common/UploadArea.tsx
src/frontend/src/components/createnewproject/DataExtract.tsx
src/frontend/src/components/createnewproject/UploadArea.tsx
src/frontend/src/store/types/ICommon.ts
src/frontend/src/utilfunctions/convertFileToGeojson.ts
src/frontend/src/utilities/CustomizedSnackbar.tsx

- Related to ##2114
Show geojson validation errors on toast if geojson contains validation errors

Geojson validation on project creation

---

src/backend/app/db/postgis_utils.py
src/backend/app/projects/project_routes.py

- Issue: #2271
- Pass empty task id if the feature lies outside the task boundary
- Simplify the endpoint, removed use of func `split_geojson_by_task_areas`
- Fixed issue of populating `None` in `submission_ids` for newly created entity

Allow entity creation outside task boundary

---

src/backend/app/projects/project_routes.py

- Issue: #2271
There was an unnecessary execute command inside execute; removing it fixed the problem.

Remove unintended extra execute command

---

src/mapper/src/lib/components/dialog-entities-actions.svelte
src/mapper/src/lib/components/map/main.svelte
src/mapper/src/store/entities.svelte.ts

- Related to #2286
- Convert `entity list` array to Map for faster retrieval of entity
N/A

Optimize entity lookup performance using Map for quick entity retrieval

---

src/backend/app/submissions/submission_crud.py

- Issue: #2266 
- Hashtags provided during project creation are added in project features while converting them into fgb data
- Added hashtags are also used in dataset and entity creation
- Added calculated field to add hashtags of corresponding selected feature in submission data, it is also included in submission downloads
**Entities**
**Submissions**

Add hashtags to entity properties, data extracts and submissions

---

src/backend/app/db/models.py
src/backend/app/organisations/organisation_routes.py
src/backend/app/organisations/organisation_schemas.py
src/backend/app/projects/project_crud.py
src/backend/app/projects/project_routes.py
src/backend/app/projects/project_schemas.py

- Issue: #1572 
- Created new endpoint to list organisation admins of the organisaition
- Added organisation id param to filter the project summary
- Calculated total submissions, total mapped tasks, total bad tasks and total validated tasks from task event
N/A
`/projects/summaries?org_id=1`
`/organisation/org-admins?org_id=1`
- 📗 Update any related documentation and …

Filter project summary by org, calculate total submission, total bad, validated and mapped tasks

---

compose.yaml
deploy/compose.development.yaml

- Issue: #2299
- Updated to version of `electric/electric` docker image to `1.0.0-beta.23`
N/A

Update the electric sql -> v 1.0.0-beta.23

---

src/mapper/package.json
src/mapper/pnpm-lock.yaml

- Issue: #2299 
- Updated the version of` @electric-sql/client -> "1.0.0"`

Update the version of typescript client to 1.0.0

---

src/backend/app/db/models.py
src/backend/app/projects/project_crud.py
src/backend/app/projects/project_routes.py
src/backend/app/projects/project_schemas.py

- Related to: #2307 
Added minimal param for the mapper frontend project summary
Fix the issue of total tasks being calculated incorrectly

Add minimal query option for mapper frontend project summary

---

src/frontend/src/components/DialogTaskActions.tsx
src/frontend/src/components/ProjectDetails/ProjectDetailsMap.tsx
src/frontend/src/store/types/ILogin.ts
src/frontend/src/utilfunctions/login.ts
src/frontend/src/views/OsmAuth.tsx
src/mapper/src/lib/utils/login.ts

- Related to #2153
This PR contains the frontend fixes related to auth details & login via OSM after the breaking changes of the google sign-in merge on the backend
**Note: This PR is only for the current fixes, I'll work & make a separate PR on google sign-in.**
N/A

Fix auth details

---

src/frontend/src/views/ProjectDetails.tsx

- Related to #2037
- Project Details: Update hide/unhide tab & buttons logic
N/A

Update hide/unhide tab & buttons logic

---

compose.yaml
src/backend/app/db/models.py
src/backend/app/organisations/organisation_schemas.py
src/backend/app/projects/project_schemas.py
src/backend/migrations/init/fmtm_base_schema.sql
src/backend/scheduler/project_stats.py

- Issue: #2321
- organisation admin api crashing with no profile image
- Removed project outline from summary api
- Created separate materialized view for project stats (5 secs to 50 ms) performance boost
- fixed lagging issue of summary api
N/A

Create materialized view of project stats for summary api

---

.github/workflows/build_and_deploy.yml
.github/workflows/build_ci_img.yml
.github/workflows/build_odk_imgs.yml
.github/workflows/docs.yml
.github/workflows/pr_test_backend.yml
.github/workflows/pr_test_frontend.yml
.github/workflows/tag_build.yml
.github/workflows/wiki.yml
compose.yaml
contrib/just/start/Justfile
deploy/compose.development.yaml
deploy/compose.main.yaml
deploy/compose.staging.yaml
deploy/compose.sub.yaml
src/Dockerfile.ui.prod
src/backend/migrate-entrypoint.sh
src/mapper/package.json
src/mapper/src/lib/components/map/geolocation.svelte
src/mapper/src/lib/components/map/layer-switcher.svelte
src/mapper/src/routes/+layout.svelte
src/mapper/src/routes/+layout.ts
src/mapper/src/routes/[projectId]/+page.svelte
src/mapper/src/routes/[projectId]/+page.ts

- A few PRs ago I added the ability to load the mapper frontend config from config.json file.
- I updated so it is loaded from bundled S3/Minio first, with fallback to /config.json.
- This way we can easily modify the config inside the S3 bucket to change styling and logos.

Load mapper frontend config from bundled S3, with default fallback

---

src/backend/app/central/central_crud.py
src/backend/app/projects/project_crud.py
src/backend/app/projects/project_routes.py
src/frontend/src/api/CreateProjectService.ts
src/frontend/src/components/createnewproject/DataExtract.tsx
src/frontend/src/components/createnewproject/SplitTasks.tsx

Fixes #2270
- Added extra option to create a project with no geometries.
- For projects when only new geom needs to be collected.
- It's a bit messy / not perfect - I did this in a rush - but project creation works.
- Needs to be tested thoroughly.

Allow config to create projects with no existing geoms (new geom only)

---

src/backend/pyproject.toml
src/frontend/src/components/QrcodeComponent.tsx
src/mapper/messages/en.json
src/mapper/messages/pt-BR.json
src/mapper/src/lib/components/dialog-entities-actions.svelte
src/mapper/src/lib/components/dialog-task-actions.svelte
src/mapper/src/lib/components/map/geolocation.svelte
src/mapper/src/lib/components/map/legend.svelte
src/mapper/src/lib/components/more/activities.svelte
src/mapper/src/lib/components/more/comment.svelte
src/mapper/src/lib/components/more/index.svelte
src/mapper/src/lib/components/more/project-info.svelte
src/mapper/src/lib/components/offline/basemaps.svelte
src/mapper/src/lib/components/pagination.svelte
src/mapper/src/lib/components/qrcode.svelte
src/mapper/src/routes/[projectId]/+page.svelte

https://github.com/hotosm/fmtm/issues/2249
It replaces English texts with callings to the function for internationalization, depending on the selected language.
All texts are available in English And Portuguese now. A translator was used for Portuguese, human review and validation is still needed.

+ Translations for all texts in the mapper app

---

src/mapper/static/web-forms.html

Use stepper layout in webforms
Use paginated web form experience
nope
- load up fmtm locally
- create a project in manager
- go to mapper at http://mapper.fmtm.localhost:7050/1?webforms=true
- click on a task
- click on a building
- click MAP IN ODK WEB FORMS
- see stepper layout experience

updated stepperLayout to true

---

src/mapper/messages/en.json
src/mapper/messages/ne.json
src/mapper/messages/pt-BR.json
src/mapper/src/lib/components/dialog-entities-actions.svelte
src/mapper/src/routes/+layout.svelte
src/mapper/src/store/common.svelte.ts
src/mapper/static/config.json
src/mapper/static/web-forms.html

Example: Fixes #2333 
Replace URL param with config.json for enabling web forms
none
- Go to mapper frontend (like http://mapper.fmtm.localhost:7050/1)
- Click on the map
- Click on a building
- See that only one red button appears (depending on whether enableWebforms is true or false in config.json)

web forms enable config

---

src/frontend/src/components/ManageProject/EditTab/ProjectDescriptionTab.tsx
src/frontend/src/components/common/Chips.tsx
src/frontend/src/components/createnewproject/ProjectDetailsForm.tsx
src/frontend/src/store/slices/CreateProjectSlice.ts
src/frontend/src/store/types/ICreateProject.ts

- Related to #2266
- Replace input with input with chips in create project (proj details form) & edit project details section

Default Hashtags

---

src/mapper/src/lib/components/forms/wrapper.svelte

Example: Fixes #2336
- set geometry question answer
- hides the question
- makes sure the answer is in the payload

hide feature selection in web forms

---

compose.yaml
deploy/compose.development.yaml
deploy/compose.sub.yaml
odkcentral/ui/Dockerfile

Fixes #2198
- NOTE this means all users MUST upgrade to ODK Collect version 2024.3.0 or higher.
- It's only on dev for now, but will matter once a release is made and we upgrade prod.
- (we could actually defer the upgrade on prod despite making a release if needed, but we would get errors regarding form attachments).
We need this change for https://github.com/hotosm/fmtm/issues/2337 else we get issues with Content-Type not set for media uploads (fixed by ODK team).
- 📗 Update any …

Update to latest ODK Central v2024.3.1

---

src/backend/app/auth/auth_deps.py
src/backend/app/db/models.py
src/backend/app/projects/project_crud.py
src/backend/app/projects/project_routes.py
src/mapper/src/lib/components/auth.svelte

- Issue: #2311
- osm login issue in mapper page
- Create a `public_view` dependency to allow public users without login to view the project summaries. The main goal of introducing it is to get the user information if they are logged in so that we can check if the user has access to the private projects or not. If `login_required` is used here user won't be able to view project cards without logging in.
- Check if the user is `superadmin`; if he is `superadmin`, he can view every project.
- Check if the user is `org_admin`; then he can view all the projects within the organisation, whether the projects are private or public, along with the other public projects from other organisations.
- Check if the user is a mapper and he has access to private projects; otherwise, he will only view …

Implement role wise access to project summaries

---

src/mapper/messages/ne.json
src/mapper/project.inlang/settings.json
src/mapper/src/lib/components/more/index.svelte

Nepali language translation & More section contents blank issue on other languages

---

src/backend/app/central/central_crud.py
src/backend/app/central/central_routes.py
src/backend/packages/osm-fieldwork/osm_fieldwork/OdkCentralAsync.py

- Related to: #2337 
Allow form attachment retrieval

Allow for download of form media/attachments as list of URLs pt2

---

src/backend/app/db/models.py
src/backend/app/projects/project_crud.py
src/backend/app/projects/project_routes.py
src/backend/app/users/user_crud.py
src/backend/app/users/user_routes.py
src/backend/app/users/user_schemas.py
src/backend/migrations/11-user-invites.sql
src/backend/migrations/init/fmtm_base_schema.sql
src/backend/tests/test_projects_routes.py

Related to #2377
- Add a new db table `user_invites`.
- Records when a manager adds a user to a project and provides an invite URL to them.
- Optionally OSM message or email the user.
- Adds a router for creating and consuming user invite tokens.
- Token is included in frontend URL:
- Saved to sessionStorage
- User prompted to log in
- After log in and user created in db, the role from the invite is set for the project/user
@Anuj-Gupta4 it would be awesome if you get a chance to check this over and push it forward tomorrow 🙏 
Once the backend is fully in place, @NSUWAL123 we also need a small frontend page to do the token handling via sessionStorage, login redirect, then calling the invite API, as described above 😄 
- Create private project
- Ensure standard user can't access project
- …

Add user invites via URL

---

src/mapper/src/lib/components/forms/wrapper.svelte

Adds xid and xlocation to the webforms submission by directly setting the values on the xforms engine instance.
Also sets accuracy of warmup geopoint to 0.0 to maintain consistency throughout application
Sets xid and xlocation values in the xforms engine instance, so the values get serialized by odk's web forms.
Supersedes https://github.com/hotosm/fmtm/pull/2379
- Enable GeoLocation on the map
- Click a map feature
- Fill out a web form
- Open Network Tab
- Send/submit web form
- Inspect Results
- …

xid and xlocation (2025-04-15)

---

src/mapper/src/lib/components/map/main.svelte

- Related to #2392
Fix task lock icon repeat by calculating task polygon centroid and placing the lock icons based on the centroids
Before: 
After:

Fix multiple task lock icon on map zoom

---

src/backend/app/db/models.py
src/backend/app/users/user_crud.py
src/backend/app/users/user_routes.py

- Related to: #2390 
Made the invite links generated during user invitation process user specific so only the intended users can use the link along with other minor changes.

Enhance user invitation process with user wise invite URL validation

---

src/backend/app/projects/project_schemas.py
src/frontend/pnpm-lock.yaml
src/frontend/src/api/Project.ts
src/frontend/src/components/createnewproject/Description.tsx
src/frontend/src/components/createnewproject/ProjectDetailsForm.tsx
src/frontend/src/components/createnewproject/SplitTasks.tsx
src/frontend/src/components/home/ExploreProjectCard.tsx
src/frontend/src/models/home/homeModel.ts
src/frontend/src/shared/AssetModules.js
src/frontend/src/store/slices/CreateProjectSlice.ts
src/frontend/src/store/types/ICreateProject.ts
src/frontend/src/types/enums.ts
src/frontend/src/views/ProjectDetails.tsx

- Related to #2311
- Project visibility type selection radio button add

Project visibility implementation

---

src/backend/app/db/models.py
src/mapper/src/lib/components/dialog-task-actions.svelte
src/mapper/src/lib/components/map/main.svelte
src/mapper/src/lib/types.ts
src/mapper/src/store/login.svelte.ts
src/mapper/src/store/tasks.svelte.ts

- Related to #2395
- Allow users (who have locked the task) to revert the mapped task to ready state

Allow users to revert mapped task to ready state

---

src/backend/app/db/models.py
src/mapper/src/lib/components/dialog-task-actions.svelte
src/mapper/src/lib/components/map/main.svelte
src/mapper/src/lib/types.ts
src/mapper/src/store/login.svelte.ts
src/mapper/src/store/tasks.svelte.ts

Revert "Allow users to revert mapped task to ready state"

---

src/mapper/src/lib/components/more/index.svelte
src/mapper/src/routes/[projectId]/+page.svelte
src/mapper/src/routes/[projectId]/page.css

- Related to #2415
- Hide basemaps tab on webforms enable
- Show project info & instructions tab on webforms enable & hide project info & instructions tab from more section on webforms enable

Hide basemaps & show info, instructions tab on webforms enable

---

src/mapper/src/lib/components/forms/wrapper.svelte

Fixes #2412
Basically sends an entity status of 6 if there's a problem, 3 if it's a new geom, and 2 otherwise.
I don't check if there's a missing `<feature>` tag, because the form wouldn't be open nor submitted if that is missing.
I had originally checked if a `<feature>UUID here</feature>` existed, but that would always return true because we add that in earlier in the same function call.
- Create a new feature and submit that (status sent should be 3)
- Create a submission where the building or feature doesn't exist (status sent should be 6)
- Create a submission where the feature isn't digitized correctly(status sent should be 6)
- Create a submission where everything is good (status sent should be 2)
- 📖 Read the Field-TM Contributing Guide: …

send correct entity status when submitting

---

src/backend/packages/osm-fieldwork/osm_fieldwork/form_components/mandatory_fields.py
src/backend/packages/osm-fieldwork/osm_fieldwork/update_xlsform.py

- Follow up  PR: #2396 
- Added label to the field new_feature if it is present when using odk collect
- Fixed calculation error of digitisation_correct adding missing enclosing bracket in the logic
- Rename instanceId to instanceID as instanceId is not recognized since xml uses instanceID in odk which solves the issue of calculation of submission_ids
```json
{
"start": "2025-04-28T15:27:37.681+05:45",
"end": "2025-04-28T15:27:52.765+05:45",
"today": "2025-04-28",
"phonenumber": null,
"deviceid": "collect:rBi4x3WyPlARUPeK",
"username": "localadmin",
"email": "NOT IMPLEMENTED",
"warmup": "POINT (85.3285296 27.730375 1277.800048828125)",
"feature": "cc4feee7-5388-4603-999a-6fe3bf4d3a2f",
"new_feature": null,
"xid": "1100829",
"xlocation": null,
"task_id": "3",
"status": "2", …
```

Calculate submission ids using instanceID

---

src/mapper/static/web-forms.html

fix images not appearing

---

src/backend/app/projects/project_routes.py
src/mapper/src/routes/+page.svelte

- Issue:  #2311
- implement mapper role in minimal project detail to avoid access through url
- added credentials in svelte frontend when the api is hit to get user details in order to check their access
N/A

Role wise project visibility in mapper frontend

---

src/mapper/src/lib/components/forms/wrapper.svelte
src/mapper/src/lib/components/map/legend.svelte
src/mapper/src/lib/components/map/main.svelte
src/mapper/src/routes/[projectId]/page.css
src/mapper/src/styles/dialog-task-actions.css
src/mapper/src/styles/map-legend.css
src/mapper/src/styles/map.css

Fixes #2419
Fixes icon button background color and buttons spacing.

Fix button backround color, spacing

---

docs/manuals/mapping.md
docs/manuals/project-managers.md

Updated managerial user manual
Fixes #2486 
Updated manager's user manual

Update project-manager User manual.md

---

src/mapper/src/lib/api/fetch.ts
src/mapper/src/lib/components/forms/wrapper.svelte
src/mapper/static/config.json

Example: Fixes #2439
Basically uses [CacheStorage](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage) to cache responses.
You can configure a cacheName in the config.json.  Changing the cacheName will mean a new cache will be created and any old fetches will be ignored.
no visible changes
I tried local storage first but the script was too large
Open up dev tools
Submit a web form!
Refresh your page
Open another web form!
You should not see the script loaded again
- 📗 …

added caching of odk web forms script

---

src/mapper/src/routes/project/[projectId]/+page.svelte

Fixes web form not loading
Convert formXml to blob url, so pass url to iframe.  Iframe then fetches that url.  We do this instead of trying to put the whole xml in the iframe src url

fix webform loading issue

---

src/mapper/src/lib/components/forms/wrapper.svelte
src/mapper/src/routes/project/[projectId]/+page.svelte
src/mapper/static/web-forms.html

Example: Fixes #2531 https://github.com/hotosm/fmtm/issues/2531
Change way we pass data to iframe, so iframe src can be cached.
Pass data through data- attributes.  Store cached response to CacheStorage and load as blob url.
considered postMessage for passing data, but it would be asynchronous which could lead to a lot of complications
instead of iframe.getAttribute("data-..."), I considered doing iframe.dataset.projectId, but the dataset property is somewhat new, so I'm not sure how widely supported it is.
- 👷‍♀️ Create …

Fix web forms offline

---

src/backend/packages/osm-fieldwork/osm_fieldwork/update_xlsform.py

- Related to: #2510 
Auto apply settings of a form without settings tab is uploaded by the user.

Auto add form settings configuration if not present

---

src/mapper/src/routes/+page.svelte

- Search project not working on mapper frontend
- Pagination change not working on mapper frontend
- Fix pagination & search functionality on mapper frontend
https://github.com/user-attachments/assets/998c76fc-9bf8-4b55-a865-f37a5764e1d9

Fix pagination on mapper frontend

---

src/mapper/src/lib/components/forms/wrapper.svelte

Addresses the load spinner styling issue mentioned in #2477
There was a typo in the css style that has been fixed

Fixes load spinner issue

---

src/frontend/src/utilfunctions/urlChecker.ts

- Related to #2139
Check if a URL is valid or not based on URL protocol as well

Update URL validation logic

---

src/backend/packages/osm-fieldwork/osm_fieldwork/update_xlsform.py

- Related to: #2510 
Form ID is now properly returned after being generated.

Ensure form_id generated is returned

---

src/backend/app/db/enums.py
src/frontend/src/components/createnewproject/DataExtract.tsx
src/frontend/src/store/slices/ThemeSlice.ts
src/frontend/src/types/enums.ts
src/frontend/src/utilfunctions/getTaskStatusStyle.ts
src/mapper/src/constants/enums.ts
src/mapper/src/lib/components/map/main.svelte

- Related to Issue #2561 & Continuation of PR #2571
https://github.com/user-attachments/assets/c2fa9ea9-251d-457b-abb9-99fbbd22fe67

Line Geometry Visualization

---

src/mapper/src/lib/components/forms/wrapper.svelte

Per https://github.com/hotosm/fmtm/issues/2433, adds today to XML submission
Basically take Year-Month-Day of ISOString

add today to odk xml submission

---

src/mapper/src/lib/components/forms/wrapper.svelte

https://github.com/hotosm/fmtm/issues/2433
Add domain to device id
Supsersedes https://github.com/hotosm/fmtm/pull/2590

add domain to device id

---

src/backend/app/central/central_crud.py
src/backend/app/central/central_schemas.py
src/backend/app/projects/project_routes.py
src/backend/packages/osm-fieldwork/osm_fieldwork/form_components/mandatory_fields.py
src/mapper/src/lib/components/forms/wrapper.svelte
src/mapper/src/lib/types.ts

- Issue: #2493
- Extract submission_ids from submission_xml
- Append existing submission_ids if found in the selected entity
- Pass the final `submission_ids` while updating the entity status
- Add submission_ids in the payload in backend and pass the data along with the submission_ids using schema and
- Update the entity
N/A

Update submission_ids of the entity after submission

---

src/frontend/src/utilfunctions/extractGeojsonFromObject.ts
src/mapper/src/lib/components/forms/wrapper.svelte
src/mapper/src/lib/components/map/main.svelte
src/mapper/src/store/entities.svelte.ts

- Related to #2508
- Related to #2586
- Pass the clicked entities javaRosa converted geometry as xlocation when making submission

Pass xlocation to submission xml

---

src/mapper/static/web-forms.html

Example: Fixes #2559
Attempts to solve issue with #2559, by basically not displaying the image that a user captures and uploads to the web form.
Considered using css, which maybe could help, but it wouldn't prevent the JavaScript code from that might be leading to memory issues.  I thought it would be more comprehensive to just avoid even running the JavaScript code to render the html for the image.
Create a submission in web forms!
- 📗 Update any related documentation and include …

disable upload image preview

---

src/backend/app/projects/project_routes.py
src/backend/scheduler/project_stats.py

- Related to: #2603 
Count validated and marked bad submission as a submission as well.

Fix submission count in project card and detail page.

---

src/frontend/src/api/User.ts
src/frontend/src/components/ManageProject/User/Invite.tsx

- Related to #2619
Invite multiple OSM users by inserting comma separated OSM usernames
https://github.com/user-attachments/assets/cc62eb3f-b105-400c-97a5-7542bf151e2e

Invite multiple OSM user by comma separated value

---

src/mapper/messages/en.json
src/mapper/messages/ne.json
src/mapper/messages/pt-BR.json
src/mapper/src/lib/components/offline/index.svelte
src/mapper/src/lib/components/offline/offline-data.svelte
src/mapper/src/styles/offline.css

Fixes #2536
- Table to display offline submissions
- Buttons to download queued submissions and failed submissions as CSV.

feat: display offline submissions in offline tab for debugging (+csv)

---

src/backend/app/auth/roles.py
src/backend/app/db/enums.py
src/migrations/002-add-sensitive-project-visibility.sql
src/migrations/init/shared/1-enums.sql

- Related to: #2647 
Added 'SENSITIVE' visibility option to project enum and update submission download permission to allow free access t o public and invite only projects

feat: add 'SENSITIVE' project and allow public access to public and invite only projects

---

src/backend/app/db/models.py

[Example: Fixes #123](https://github.com/hotosm/fmtm/issues/2647#issuecomment-3008025589)
- Related to: #2647 
Update project display logic on project card page.
All users see public, sensitive, and invite-only projects.
Private projects are only visible to users who have access.
- 📗 Update any related documentation and …

Update visibility logic for project access permissions

---

src/frontend/src/views/OsmAuth.tsx

- Related to #2685
- Fix twice the OSM auth api call due to rerender
- Remove condition for checking the mapper frontend URL 
for redirection since the OSM login has itself been handled on the mapper frontend

Fix management frontend login

---

src/frontend/src/components/ProjectDetails/ProjectDetailsMap.tsx
src/mapper/src/lib/components/map/main.svelte

- Related to #2682
- Add buffer around the line string to ease feature selection (mapper)
- Add hitTolerance to ease feature selection (management)

Ease feature selection

---

src/backend/app/db/models.py
src/backend/app/helpers/helper_crud.py
src/backend/app/helpers/helper_routes.py
src/backend/app/projects/project_crud.py
src/backend/app/projects/project_routes.py
src/backend/tests/test_helper_routes.py

- #2693
- #2672
- enhance project user role management with new methods and ODK Central credential testing
- Added optional role filtering to fetch all project user roles.
- Implemented methods to delete a user's role from a project.
- Introduced a new endpoint to test ODK Central credentials.
- Updated project routes to support unassigning users from projects.
- 📗 Update any related …

Role unassign from project and odk cred check endpoint

---

src/frontend/src/components/CreateProject/validation.ts

- [] 🐛 Bug Fix
- When AOI is reset and Save and Continue button is clicked, then the validation doesn't work and the UI crashes
- Update AOI validation

UI crash on AOI reset & continue next

---

docs/manuals/Mapping Usecases.md

Documented step by step road mapping project creation workflow
Example: Fixes #2629 

Documentation of highway mapping project creation workflow

---

src/backend/app/submissions/submission_crud.py
src/backend/app/submissions/submission_schemas.py

- #2724 
- Updated the ReviewStateOut Pydantic response model to allow deviceId: Optional[str] = None.
- The ODK submission may not include deviceid metadata if it wasn't declared in the XLSForm

Fixed false error on submission status update.

---

src/migrations/001-refactor-project-visibility-enum.sql

- #2722 
This PR fixes the CI crash that occurred during the merge of [#2772](https://github.com/hotosm/field-tm/pull/2772), which was caused by a faulty migration script.
- Fixed issues in the migration script that caused migration unsuccessful during CI runs.

Fix broken migration of project visibility.

---

src/frontend/src/api/task/index.ts
src/frontend/src/api/task/types.ts
src/frontend/src/api/user/index.ts
src/frontend/src/api/user/types.ts
src/frontend/src/components/DialogTaskActions.tsx
src/frontend/src/components/ProjectDetails/FeatureSelectionPopup.tsx
src/frontend/src/components/ProjectDetails/TaskSelectionPopup.tsx
src/frontend/src/components/common/Button.tsx
src/frontend/src/environment.ts
src/frontend/src/services/task.ts
src/frontend/src/services/user.ts
src/frontend/src/views/ProjectDetails.tsx

- Related to #35
- User assignment to a specific task via the task pop-up
- Refactor code

Task User Assignment

---

src/frontend/src/components/DialogTaskActions.tsx

- Mappers able to assign, validate, or trigger task actions via management frontend
- Only allow project managers or organization admins to trigger task actions via management frontend

Restrict mappers to update task 

---

src/mapper/src/routes/+layout.svelte

- Related to #2554
- hotosm-ui component matomo tracking add

HOTOSM Matomo tracking component integration on mapper frontend

---

src/backend/app/tasks/task_routes.py

Fix task assingment
Correctly assign the assignee instead of the logged in user.

fix(tasks): Correctly assign the assignee in add_new_task_event function (#2802)

---

src/frontend/src/components/ProjectDetails/ProjectOptions.tsx
src/mapper/src/lib/odk/qrcode.ts

- Related to #2808
- Related to #2809
- Fix QR code download issue on mapper
- Download QR code in PGN format in management
https://github.com/user-attachments/assets/453b0264-9989-4015-b682-4e91fbe5e98a

Fix QR download on mapper & download QR in PNG format in management

---

docs/manuals/xlsform-design.md
src/backend/packages/osm-fieldwork/osm_fieldwork/form_components/choice_fields.py
src/backend/packages/osm-fieldwork/osm_fieldwork/form_components/digitisation_fields.py
src/backend/packages/osm-fieldwork/osm_fieldwork/form_components/mandatory_fields.py
src/backend/packages/osm-fieldwork/osm_fieldwork/form_components/translations/__init__.py
src/backend/packages/osm-fieldwork/osm_fieldwork/update_xlsform.py
src/backend/packages/osm-fieldwork/tests/test_update_xlsform.py

- https://github.com/hotosm/field-tm/issues/2627
- https://github.com/hotosm/field-tm/issues/2374
- Only add relevant translations using label field for mandatory fields.
- In case of bare label, don't add translations of other languages and use English label for injected fields.
- Update translation check test case.
- Check if we have the translation for all labels present and raise an error if not present.
- Update the xlsform documentation.

Only add translation for the set language in mandatory fields

---

src/frontend/src/api/CreateProjectService.ts
src/frontend/src/components/Landing/Banner.tsx

- Project creation error
- Related to #1329
- Remove unused action dispatch
- Fix non-clickable login dropdown issue on homepage

Fix frontend issues

---

src/backend/app/projects/project_schemas.py
src/frontend/src/components/CreateProject/00-ProjectTypeSelector.tsx
src/frontend/src/components/CreateProject/02-ProjectDetails.tsx
src/frontend/src/views/CreateProject.tsx

- During project creation, when ODK is selected as the project type, `use_odk_collect=True` is not passed as the project stub and to the upload-xlsform endpoint as well
- Pass `use_odk_collect` value during stub project creation

Update use_odk_collect value during stub project creation
