hotosm/field-tm

src/backend/central/central_crud.py, src/backend/debug/debug_routes.py, src/backend/models/enums.py, src/backend/odkconvert/OdkCentral.py, src/backend/odkconvert/make_data_extract.py, src/backend/odkconvert/odk_client.py, src/backend/odkconvert/requirements.txt, src/backend/projects/project_crud.py, src/backend/projects/project_routes.py, src/backend/requirements.txt, traefik/traefik.dev.toml
This patch allows for the download of both the project boundary polygon, as well as all the task boundaries as GeoJson. This can be used for display, or with frontend support, downloaded to disk. This patch also support upload a custom XLSForm to the database, adding it to the XLSForm library. If the name matches an existing XLSForm, then it gets updated instead.
=> Add support for file I/O from database

.env.example, central.dockerfile, docker-compose.prod.yml, docker-compose.yml, docs/DEV-1.-Getting-Started.md, src/backend/Dockerfile, src/backend/main.py
Updated to match dev docker-compose, except:
- Includes traefik for routing / the web server:
- The frontend will be accessible on fmtm.hotosm.org
- The API will be accessible on fmtm.hotosm.org/api
- I kept ports 5432 (db) and 8383 (central) bound to localhost, for ssh debugging.
- The ports should be blocked publicly by the Azure firewall settings.
- I also added in an additional optional production env variable API_PREFIX, linked to the root_path in FastAPI. This allows serving behind a proxy subpath, such as /api.
=> Update production docker-compose config

src/backend/main.py
This adds 8081 to allowed origins so that react openlayers can be run locally and talk to a remote instance of the fmtm api.
=> Add 8081 to allowed origins

.github/workflows/wiki.yml
- Triggers when there is a push to main (i.e. merged PR) and the `/docs` dir is changed.
- Syncs content of /docs with wiki, then pushes to wiki using service user access token.
**Note**: for this to work, we need to create a service user for the repo.
I propose a user `svcfmtm` with an email `fmtm@hotosm.org` (does this email exist?).
Then we need to create an access token for that user, and place it in repository secret variable `SVC_ACCESS_TOKEN`.
=> Add Github workflow to deploy /docs --> wiki

.github/workflows/wiki.yml
Fixes #101
I added a token called WIKI_DEPLOY_TOKEN, but the token is owned by me for now:
The token expires at the end of the year, so we have until then to update the token to a service account user.
=> Update deploy token secret for wiki workflow

.env.example, docker-compose.prod.yml, docker-compose.yml, docs/DEV-1.-Getting-Started.md, docs/DEV-5:-Production-Deployment.md, src/frontend/Dockerfile, src/frontend/fmtm_openlayer_map/webpack.config.js, src/frontend/main/webpack.config.js
Fixes #103
There have been some changes to the .env variables.
Replacing:
```dotenv
FRONTEND_SCHEME
FRONTEND_DOMAIN
API_DOMAIN
```
With:
```dotenv
FRONTEND_MAIN_URL
FRONTEND_MAP_URL
```
=> Update docker config for microfrontend subdomains

.env.example, docker-compose.prod.yml, docker-compose.yml, docs/DEV-5:-Production-Deployment.md
As we now have variables `FRONTEND_MAIN_URL` and `FRONTEND_MAP_URL`, we can set the BACKEND_CORS_ORIGINS in the docker-compose file, instead of having the user set it manually.
=> Remove BACKEND_CORS_ORIGINS, set automatically

src/backend/tasks/tasks_schemas.py
Fixes #126
Added `task_status_str` to the response for `/tasks/{task_id}/new_status/`
In the long run the schemas need to be refactored, possibly renamed for clarity, and updated for other endpoints.
=> Include task_status_str in status update response

docs/DEV-2.-Backend.md
This PR fixes some of the minor typos on the [DEV-2.-Backend Deployment](https://github.com/hotosm/fmtm/blob/main/docs/DEV-2.-Backend.md) page.
=> Fixing typos in backend deployment documentation

.github/workflows/prod_deploy.yml, .github/workflows/pytest.yml, .pre-commit-config.yaml, docker-compose.prod.yml, docker-compose.yml, src/backend/config.py
First attempt at docker compose based deploy to fmtm.hotosm.org.
- Checks out repo.
- Creates a .env using repo secrets for the `prod` environment.
- Uses SSH key for service account user.
- Uses a --build deploy, to prevent deployment prior to quay.io build (i.e. builds locally instead).
I also refined the BACKEND_CORS_ORIGIN validator. The variable should no longer be required as default (it will include the frontend origins). The variable may still be included to override default values.
=> Create auto-deploy docker-compose action for prod

docs/DEV-1.-Getting-Started.md
=> Added more details to Getting-Started.md

.env.example, docker-compose.prod.yml, docker-compose.yml, docs/DEV-1.-Getting-Started.md, docs/DEV-2.-Backend.md, docs/DEV-6.-Production-Deployment.md, odkcentral/api/.dockerignore, odkcentral/api/Dockerfile, odkcentral/api/init-user-and-start.sh, src/backend/config.py, src/backend/main.py
Fixes #163
Changes:
- ODKCentral now supports database credential injection (https://github.com/getodk/central/pull/389), so I removed the `jq` hack in our API dockerfile.
- Added environment variables to the development docker-compose.yml.
- Automatically init the admin user for ODK Central, using provided credentials in the `.env` (created via terminal no longer required).
- Remove ODKCentral containers from docker-compose.prod.yml. We will run a standalone ODKCentral in production (odk.fmtm.hotosm.org, or odk.hotosm.org).
I thought I would also take the opportunity to make some minor tweaks to the backend:
- Fix issues with BACKEND_CORS_ORIGINS variable. It is now optional and has been renamed to EXTRA_CORS_ORIGINS.
- Automatically redirect root path for https://fmtm-api.hotosm.org to …
=> Update ODK Central API config for development, remove from prod

src/frontend/main/src/api/CreateProjectService.ts
Update custom form API changes and handled success and error messages 
This commit updates the success message in the CreateProjectService to include a notification that QR code generation has started. Additionally, the duration of the success message has been increased to two seconds.
The error message in the CreateProjectService has also been updated to display "Something Went Wrong" as a fallback if there is no response data detail available.
In the GenerateProjectQRService, the success message has been changed to "QR Generation Completed," and dispatched through the common action.
Finally, in the UploadCustomXLSFormService, the error message now displays "Something Went Wrong" as a fallback if there is no response data detail available.
=> ✨ feat: Update form API changes and handled success and error messages 

src/backend/projects/project_crud.py, src/backend/projects/project_routes.py, src/backend/requirements.txt
This pull request addresses the issue of default data extract generation in the geojson format containing only nodes or building centroids. With this update, users can select either nodes or polygons as the output geometry for data extraction. The fmtm backend now supports both options, allowing users to extract the data in the format that best suits their needs.
To make use of this feature, users can now select the output geometry option when specifying the category for the data extract on the create project page. This update provides users with greater flexibility and control over the data extraction process.
- Closes #374
=> Select nodes or polygons for data extract

docker-compose.deploy.yml, docker-compose.noodk.yml, docker-compose.yml, src/backend/Dockerfile, src/backend/pdm.lock, src/backend/pyproject.toml
PR to move osm-fieldwork back to pyproject.toml and to create a docker volume for /app/images path in the API container.
This allows for persistent images across restarts, without file permission errors.
=> Add fmtm images to docker volume, osm-fieldwork to pyproject

README.md
Currently the readme has the Quay.io build statuses.
We no longer use this and have changed to Github Container Registry.
I updated the README to include the `pytest` and `Build and Deploy` actions for both **development** and **main** (production).
=> Update README with github action statuses

docker-compose.yml, odkcentral/proxy/Dockerfile, src/backend/Dockerfile
Reverts accidental additions to docker-compose.yml breaking osm-fieldwork.
I also added two bugfixes:
- After updating the odkcentral cert chain in the proxy, I hadn't updated it in the api dockerfile. Connections to central now work again if using it locally.
- The pre-compile for python modules needs to be done by the root user, prior to changing to appuser. Fixed.
=> Fix osm-fieldwork package override, use correct central cert

docker-compose.deploy.yml, docker-compose.noodk.yml, docker-compose.yml
- Many systems already have port 5432 mapped for a local postgres instance.
- Default port mapping for postgres container: host:container --> 5433:5432.
=> Update default postgres port binds from 5432 --> 5433

docker-compose.josm.yml, docker-compose.yml, docs/DEV-2.-Backend.md, josm/Dockerfile, josm/container-entrypoint.sh, josm/nginx-josm.conf, josm/novnc/Dockerfile, josm/novnc/index.html, josm/preferences.xml
Part misunderstanding, part fun little project.
I originally containerised JOSM in the hope to make the API accessible.
**Two Issues**
- JOSM is useless without the GUI component.
- JOSM has very strict and non-configurable remote access settings. It's accessible on 127.0.0.1:8111, which doesn't work with Docker (uses localhost).
**Solution**
- I made the JOSM GUI accessible via noVNC. This way we don't need to install Java or JOSM on our local machine for development. It runs entirely in a container, the GUI accessible on `localhost:8112`.
- I added nginx to the JOSM container, which is against the one-service-per-container ethos, but necessary in this case. Nginx reverse-proxies 127.0.0.1:8111 to localhost:80, making the JOSM API accessible by port mapping the container 8111:8111. Now …
=> Add JOSM API to docker compose dev stack

.github/workflows/pytest.yml, build_ci_imgs.sh, odkcentral/api/Dockerfile, src/backend/.dockerignore, src/backend/Dockerfile, src/backend/app/config.py, src/backend/container-entrypoint.sh, src/backend/tests/test_users.py
- PyTest fails currently due to commented out tests - I added a dummy test to prevent this.
- Add helper script for building backend CI img, including test code.
- Add services to the pytest action (fmtm db, central db, central, central-proxy), so we can test all endpoints with proper responses.
- Moved all entrypoint script into files, instead of hacky dockerfile setup.
=> Update pytest CI action, tweak

docker-compose.deploy.yml
@spwoodcock  I found that .deploy.yaml file was used for deployment and I did not update this file for tiles volumes in my previous pull request.
=> tiles volumes mount for deploy docker yaml file

docker-compose.deploy.yml, docker-compose.noodk.yml, docker-compose.yml, src/backend/Dockerfile, src/backend/app/auth/auth_routes.py, src/backend/app/central/central_crud.py, src/backend/app/central/central_routes.py, src/backend/app/central/central_schemas.py, src/backend/app/config.py, src/backend/app/main.py, src/backend/app/organization/organization_crud.py, src/backend/app/organization/organization_routes.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/utils.py, src/backend/app/submission/submission_crud.py, src/backend/app/submission/submission_routes.py, src/backend/app/tasks/tasks_crud.py, src/backend/pdm.lock, src/backend/pyproject.toml
(new PR as I updated my Git origin to HOTOSM)
- Currently we use logging.basicConfig, which is fine, but not very configurable.
- Logs also don't currently persist after container restarts, which doesn't help debugging if multiple PRs and merged in succession (redeploy).
I updated to use the loguru library, which is very feature rich and easy to use.
The setup:
- Log to terminal in a standardised way, hooking all downstream loggers.
- Add colour to logs if your terminal supports it.
- All log calls are non-blocking, using multithreading.
- Backtracing for more detailed logs on traceback.
- Generic error catching, so if an unhandled exception occurs, the server doesn't go down.
- Logging to rotating files in JSON format, located in a docker volume (these logs could be synced to S3 in the …
=> Update logging to be more feature rich, persist logs, JSON logs 

src/backend/app/main.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py
Follow on from #785
Minor tweak to:
- Set log file rotation.
- Instantiate the log with `project_id=project_id and task="create_project"`
(we don't need to pass the logger between functions, as it uses a bind to differentiate it from the standard logs)
This will generate logs to terminal, `fmtm.log` (all logs), and then create_project specific logs to `create_project.json`.
=> Project specific logging to additional separate file

.github/workflows/pytest.yml
Closes #797
I had to set github.head_ref instead of github.ref_name, as during PRs ref_name is set to the PR branch name (when we want the target branch).
The syntax `${{ github.head_ref || github.ref_name }}` works, as head_ref is only available if a PR.
=> Fix pytest during PRs

src/backend/Dockerfile, src/backend/app/config.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_schemas.py, src/backend/app/submission/submission_crud.py, src/backend/app/tasks/tasks_schemas.py, src/backend/app/users/user_schemas.py, src/backend/pdm.lock, src/backend/pyproject.toml
- Pydantic v2 is a major breaking change, required for later versions of FastAPI.
- I updated syntax to be in line with v2.
- Also updated all other dependencies to latest.
- As a consequence of the Pydantic v2 upgrade, locking dependencies with the `osm-login-python` package breaks.
- It is pinned to Pydantic v1 currently. I made a PR to fix this / allow a v1 or v2 install https://github.com/kshitijrajsharma/osm-login-python/pull/1.
=> Upgrade dependencies, Pydantic v2

docs/dev/Backend.md, src/backend/pdm.lock, src/backend/pyproject.toml
Fixes submissions.
- Bump v0.3.6rc0 --> v0.3.6rc1.
- Use pypi version of osm-login-python (now it's updated to 1.0.0).
- Update dev docs on bind mounting osm-fieldwork.
=> Bump osm fieldwork --> v0.3.6rc1

src/backend/app/config.py
The Pydantic Url type is a pain to work with. It doesn't work in place of where a str should be.
Removed all instances of AnyUrl to prevent issues parsing as str type.
In the future when Pydantic docs are improved & usage of AnyUrl is clearer, we should change back (as it does helpful config validation checking that URLs are valid.
=> Remove pydantic Url in favour of str

src/backend/Dockerfile
Useful to have PYTHONPATH pre set to /opt, allowing import of app.xxx from code outside of the directory.
=> build: set PYTHONPATH to /opt, for ci img

docker-compose.noodk.yml, docker-compose.yml, docs/dev/Backend.md, docs/dev/Troubleshooting.md, josm/docker-compose.yml, mkdocs.yml, src/backend/app/main.py, src/backend/pdm.lock, src/backend/pyproject.toml
- Added troubleshooting page for devs.
- Temp use forked osm-login-python to bundle all deps.
- Move josm docker-compose into dir.
- More descriptive names to docker compose networks.
=> Add osm login deps, minor restructure, dev troubleshooting

src/backend/app/central/central_crud.py
In this commit , the existing validate form api scouts the media present in the xml file and the api returns the required media file names in a list as a response.
=> feat: returned required media name in a response of form validity

src/backend/migrate-entrypoint.sh
- I merged the migration script PR without testing thoroughly enough.
- psql sometimes returns additional whitespace from it's queries, so the check if tables/schema existed, prior to applying the schema didn't work correctly.
- This PR adds a trim to the database check for the `projects` table, correctly identifying that data already exists.
=> Fix migration schema init (trim whitespace)

src/backend/pdm.lock, src/backend/pyproject.toml
osm-login-python was fixed to be installable in our environment (without using a Git repo branch).
=> Re-add fixed pypi osm-login-python pkg

src/backend/app/central/central_crud.py, src/backend/app/tasks/tasks_routes.py
This pull request requires new release of osm-fieldwork. So, let's not merge it right now. We can merge it whenever we have new release of osm-fieldwork.
=> updated task wise submission api for project info

src/backend/app/projects/project_crud.py
This PR accepts even if single polygon feature is uploaded to upload_multi_polygon endpoint.
=> Fix task split issue

src/backend/app/projects/project_crud.py, src/backend/tests/test_projects_routes.py
fixes #833 
This new addition generates location of project using centroid of respective AOI. I tried to generate the location for every existing project and return location as a summary of project. But it took long time to load. 
So i added feature to save location while creating project.
Instead of using a Python module, we're using the Nominatim URL for location retrieval. This change allows us to get project locations faster because the Nominatim URL is quick and responsive.
=> Addressing of project using Nominatim.

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py
1. The response from `get_project_features_geojson` has many redundant keys, increasing the data transfer size when displaying the data extract.
2. We currently request for a data extract from raw-data-api, then download the resulting zipped geojson to /tmp, extract, and return the data. In the long run there is no need for this step. We can request a flatgeobuf file from raw-data-api, then either access directly from the S3 url (store the link in db), or upload the flatgeobuf to our own S3 for access.
1. Simplify the returned JSON response when getting data extracts, removing keys:
```
task_id
project_id
geometry.properties.label
geometry.properties.title
geometry.properties.version
geometry.properties.changeset
geometry.properties.timestamp
```
from each JSON object in the array.
2. …
=> Simplify project features response & prep for flatgeobuf osm extracts

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py
Added the simplification code for PR #932 to the download geojson endpoint, instead of the one used by the frontend. Fixed.
=> Move simplify features to get_project_features endpoint

src/frontend/src/components/ProjectDetails/ProjectOptions.tsx, src/frontend/src/views/NewProjectDetails.jsx
This PR fixes the issue #936 where bottom sheet(bottom menu) is closed when "Generate mbtiles" button is clicked in mobile view.
=> Fix bottom menu

src/frontend/src/utilities/CustomDrawer.jsx, src/frontend/src/utilities/PrimaryAppBar.tsx
This PR fixes issue #929 where now SignIn/SignOut is added to the Sidebar when breakpoint is activated. Additionally, 'Explore Project' & 'Manage Organizations' have been removed from the sidebar for large screens.
1. Removed  'Explore Project' & 'Manage Organizations' from large screen sidebar
2. Added SignIn/SignOut in sidebar for small screen
=> Fix signinout issue

src/frontend/src/components/GenerateBasemap.jsx, src/frontend/src/components/ProjectDetails/MobileFooter.tsx, src/frontend/src/components/common/BottomSheet.tsx, src/frontend/src/shared/AssetModules.js
This PR contains some refinements on generate mbtiles modal design as suggested by @spwoodcock in issue #937.
=> Fix refine mbtiles modal design

src/frontend/src/components/MapComponent/OpenLayersComponent/LayerSwitcher/index.js, src/frontend/src/components/common/Button.tsx, src/frontend/src/components/common/FileInputComponent.tsx, src/frontend/src/components/common/RadioButton.tsx, src/frontend/src/components/createnewproject/SelectForm.tsx, src/frontend/src/components/createnewproject/UploadArea.tsx
This PR solves issues #948 , #949 , #951 , #952.  
1. #948 
Both AOI and Uploaded Geojson now retains when proceeded to other steps of the step form.
2. #949 
The Click to Reset button is set to inactive if there is no AOI drawn on map and the reset icon is not visible until a geojson is uploaded.
3. #951 
When radiobutton is switched, the AOI and Uploaded Geojson will not disappear.
4. #952 
Now only geojson's and json formats are accepted.
Additional Issues Solved:
1. CreateNewProject(Upload Area): Validation issue solved.
2. LayerSwitcher button icon UI alignment with the button.
3. CreateNewProject: FontSize adjusted, UI enhancements
=> Fix create new project

src/frontend/src/api/Project.js, src/frontend/src/components/ProjectDetails/ProjectOptions.tsx, src/frontend/src/components/createnewproject/SplitTasks.tsx
This PR solves issue #962 and #963. 
1. #962 
Now user is redirected to project_details when user clicks the PROCEED button on project creation.
2. #963 
Downloaded files renamed with project_id included as suggeste.
=> Fix create new project issue

src/backend/app/tasks/tasks_routes.py, src/backend/app/tasks/tasks_schemas.py
changed schema to add qr code in response.
=> Qr code in task list

src/backend/app/projects/project_routes.py
I have made an api which returns the data extracts available in the provided AOI( Area of Interest) from osm using raw-data-api.
This api accepts an aoi and the category for which data extracts are required as a parameter.
=> feat: api to get data extracts for the given aoi and category

src/frontend/src/components/GenerateBasemap.jsx
- Fixes #936 
This PR contains the following works:
1. UI enhancements for 'generate project tiles' modal: 
3. Validation for generate project tiles
=> Fix project tiles modal

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py
this pull request addresses issue #983 and allows to search for projects by project name not only within the current page but across the entire page/database..
changes:
- added search parameter in the route
- Applied a query based on the search parameter(project_name_prefix) to filter and retrieve projects from the database.
=> added search field to search projects from the db

src/frontend/src/components/common/StepSwitcher.tsx, src/frontend/src/components/createnewproject/SplitTasks.tsx, src/frontend/src/store/slices/CreateProjectSlice.ts, src/frontend/src/store/types/ICreateProject.ts, src/frontend/src/views/CreateNewProject.tsx
- fix #979 
This PR contains work on Create New Project where now users are not allowed to switch steps from the stepper while creating a project(until submit button is clicked).
=> Fix create new project stepper validation

src/backend/app/projects/project_crud.py, src/backend/app/tasks/tasks_routes.py
fixes #964 
added task_id on the task polygon and feature extracts file.
=> task id on task polygon and feature extracts

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py
added uuid in read project and total task count in generate log
=> uuid in read project and total_task in generate-log

src/frontend/src/components/GenerateBasemap.jsx
- fixes #980 
This PR solves the first part of the issue #980 (not issue 2: generating tiles from custom TMS URL which is under discussion) where input is placed before the output format, and TMS URL texfield label has been renamed.
=> Fix custom tms url

src/frontend/src/components/MapComponent/OpenLayersComponent/Layers/ClusterLayer.js
- Fix #945 
This PR adds a feature where, when a cluster is clicked it expands to multiple points when the cluster point is clicked on the cluster point at maximum zoom level. Also when 'project id' is clicked user is redirected to the specific project's project_detail page.
=> Feat cluster spread

src/backend/app/config.py, src/backend/app/organization/organization_crud.py, src/backend/app/s3.py
1. Added `S3_BUCKET_NAME_BASEMAPS` and `S3_BUCKET_NAME_OVERLAYS` in the config file
2. Upload organisation logo in the `fmtm-data` bucket in the s3.
I have used `S3_DOWNLOAD_ROOT` to get the image path. @spwoodcock is it okay?
1. We might need to migrate existing images of organisation logo which are in the container to the s3 and update the url  path in db.
2. Use this url to display the logo in the frontend.
=> Upload organisation logo in S3.

.gitignore, docker-compose.development.yml, docker-compose.main.yml, docker-compose.yml, src/backend/Dockerfile, src/backend/app/main.py, src/frontend/src/components/home/ExploreProjectCard.tsx, src/frontend/src/views/Organization.tsx
The /images/ endpoint is no longer required.
The org logos are stored in S3 thanks to @nrjadkry.
I removed the endpoint & updated the frontend to load the returned org urls from S3.
Note: currently the dev/staging server logos don't display. This PR will fix it.
=> Remove /images/ endpoint, replaced by s3 logos

src/frontend/src/components/MapComponent/OpenLayersComponent/Layers/VectorLayer.js, src/frontend/src/components/ProjectInfo/ProjectInfoMapLegend.jsx, src/frontend/src/components/ProjectInfo/ProjectInfomap.jsx
- Fix #705 
This PR covers following tasks done: 
1. Map Legend added to project info page map.
2. Fix of bug where `setStyle` props `fillColor` style was overridden by `defaultStyle` in VectorLayer.
=> Feat project info legend

src/backend/app/tasks/tasks_schemas.py
The previous code was using the get method to retrieve the attribute from model_obj, which resulted in an error. To address this issue, I replaced it with the more direct and appropriate attribute access using `model_obj.id.` like this
=> Retriving model attribute directly.

src/backend/app/tasks/tasks_schemas.py
Previously, int value was retruned in the response which created conflicts in the old projects. With these changes , it accepts integer value of enum and saves it in db. But while returning it passes "name" of the corresponding "value" resolving probable conflicts.
=> Returned task status as string

src/frontend/src/components/common/Button.tsx, src/frontend/src/components/createnewproject/SplitTasks.tsx
- Fix #1027 
This PR disables generate buildings per task button until number of buildings is entered
=> Fix generate building task

docker-compose.development.yml, docker-compose.staging.yml, docker-compose.yml
Fixes #1038
- During development release cadence is fast & database backups are not required on each redeploy.
- Moved the backup container to only run in the staging config.
=> Remove database backups from development setup

src/frontend/index.html, src/frontend/src/App.jsx, src/frontend/src/environment.ts, src/frontend/src/views/NewProjectDetails.jsx, src/frontend/src/views/ProjectDetails.jsx, src/frontend/src/views/Submissions.tsx, src/frontend/src/views/Tasks.tsx
Fixes #942
For website analytics.
This only activates on the prod setup (fmtm.hotosm.org).
The approach I settled on:
```js
const MatomoTrackingInit = () => {
useEffect(() => {
if (import.meta.env.MODE !== 'development' && import.meta.env.BASE_URL === 'fmtm.hotosm.org') {
return;
}
// Set matomo tracking id
window.site_id = environment.mamotoTrackingId;
​
// Create optout-form div for banner
const optoutDiv = document.createElement('div');
optoutDiv.id = 'optout-form'; // Set an ID if needed
document.body.appendChild(optoutDiv);
​
// Load CDN script after
const script = document.createElement('script');
script.src = 'https://cdn.hotosm.org/tracking-v3.js';
document.body.appendChild(script);
// Manually trigger DOMContentLoaded, that script hooks
// …
```
=> Add mamoto tracking to frontend

src/backend/app/projects/project_routes.py
Delete project API is public as of now. I have made this endpoint authenticated. 
Now, we need to pass the access-token as well. This adds a small level of security to this endpoint.
We will have to check the user roles and make this endpoint  accessible only by the admin user.
=> delete projects api made authenticated

src/backend/app/db/postgis_utils.py, src/backend/app/projects/project_crud.py, src/backend/app/submission/submission_crud.py, src/backend/app/submission/submission_routes.py, src/backend/pdm.lock, src/backend/pyproject.toml, src/backend/tests/test_projects_routes.py
Now that we have decided to add submission cache in s3, I have created an endpoint that adds the submission json in the s3 bucket. 
Another api to download the submission from cache.
The path in the s3 bucket is like this: `/{organisation_id}/{project_id}/submission.json`
This Pull Request tries to 
- Fix #713
=> Feat cache submissions

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py, src/backend/app/s3.py
This PR introduces the `get_dashboard_detail` async function, which fetches project details for the project dashboard using `project_id`. 
{
"project_name_prefix": "test sujan",
"organization": "naxa",
"organization_logo": "http://s3.fmtm.localhost:7050/fmtm-data/1/logo.png",
"total_tasks": 6,
"total_submission": 0,
"total_contributors": 2,
"created": "06 Dec 2023",
"last_active": "6 days ago"
}
=> Created Project dashboard

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_schemas.py
Handles the exception raised due to no submissions meta.
=> exception handling for no submissions meta

src/backend/app/submission/submission_crud.py, src/backend/app/submission/submission_routes.py
The API fetches submissions from S3, utilizing the `project_id` to construct the relevant paths. Submissions are then processed, and counts are determined based on the specified time range `days`.
=> Endpoint for submission page, return submission count by date

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py
This pull request includes the project wise contributors along with their contribution count. 
[
{
"user": "Sujan Adhikari",
"contributions": 9
},
{
"user": "svcfmtm",
"contributions": 1
}
]
1. Currently, individuals updating the task status are identified as contributors.
2. In the future, those submitting submissions will be recognized as contributors. To facilitate this, it is necessary to retrieve their user details from ODK-Collect, since users may not be logged into FMTM. This information is essential for demographic purposes as well.
=> Get contributors by project

src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py
I had previously uncommented the location string to enable its usage in the `read_project` function. However, the `create_project` also utilizes the same schema. In this case, only the project's general information is created, lacking the boundary data. Consequently, it fails to generate the location string, as these strings are derived from the centroid of the boundary.
This pull request addresses this issue by introducing a separate schema for the `read_project` function, resolving the problem associated with the location string.
=> hotfix: location str in create project

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py
Previously, the `project_dashboard` endpoint was taking longer time to respond since the submission count was done by fetching all submissions from odk-central.
Thought to use similar approach like in `submission_page` endpoint. Here, submissions are fetched directly from s3 which seems faster. If there aren't any submissions in s3, it will run background task to upload the submissions from odk-central to s3 meanwhile it will pass '0' for no submissions.
=> Optimze the performance of project dashboard

src/backend/app/db/postgis_utils.py, src/backend/app/organization/organization_crud.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py, src/backend/pdm.lock, src/backend/pyproject.toml, src/backend/tests/test_projects_routes.py, src/frontend/package.json, src/frontend/pnpm-lock.yaml, src/frontend/src/api/CreateProjectService.ts, src/frontend/src/components/ProjectInfo/ProjectInfomap.jsx, src/frontend/src/components/createnewproject/DataExtract.tsx, src/frontend/src/components/createnewproject/SelectForm.tsx, src/frontend/src/components/createnewproject/SplitTasks.tsx, src/frontend/src/components/createnewproject/validation/DataExtractValidation.tsx, src/frontend/src/components/createproject/DefineTasks.tsx, src/frontend/src/store/slices/CreateProjectSlice.ts, src/frontend/src/store/types/ICreateProject.ts
Fixes #934 and addresses part of #381 and #889
Custom data extract:
- If user uploads a flatgeobuf, this is deserialised as geojson for display on the map. The file is uploaded to our S3.
- If user uploads geojson, this is converted to flatgeobuf on the backend and file uploaded to our S3.
- In either case, a URL to the `.fgb` is stored in `public.projects.data_extract_type` (abusing this param for now, but it should be migrated to `public.projects.data_extract_url` eventually).
> Custom data extracts are stored in the FMTM S3 bucket and managed by us.
OSM data extract:
- When the user continues from the 'Data Extract' page to the 'Split Tasks' page, the endpoint is called to generate a new data extract in the background.
- This same endpoint can also accept a `project_id` param to return …
=> Use flatgeobuf data extracts

src/backend/app/projects/project_schemas.py, src/backend/app/tasks/tasks_schemas.py
Previously, the `created` field in the `ProjectDashboard` model was of type `datetime` and `task_status` field in the `TaskBase` model was of type enum class `TaskStatus`, causing a validation issue. 
This pull request resolves this issue.
=> Serialization for task_status and created project dashboard fields

src/backend/app/auth/auth_routes.py, src/backend/app/auth/osm.py, src/frontend/src/utilfunctions/login.ts, src/frontend/src/utilities/CustomDrawer.jsx, src/frontend/src/utilities/PrimaryAppBar.tsx
As discussed in https://github.com/hotosm/fmtm/discussions/1083
- We had authentication in place to return the OSM user details.
- However the **authentication** details did not persist, so implementing **authorisation** would require reacquiring **authentication** every time.
- This PR adds support for storing the auth token (OSM JWT token) in a secure cookie.
- Cookie details: samesite:lax (for CSRF), httpOnly (for XSS), secure (for MIM).
- For testing the api using auth, we no longer have to pass the access_token manually.
- If you login once via the localhost frontend, then a cookie will be saved in your browser.
- This cookie will be automatically extracted when testing endpoints on the docs page: http://api.fmtm.localhost:7050/docs making development a lot smoother.
fyi @nrjadkry …
=> Cookie based authentication

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/frontend/src/components/createnewproject/DataExtract.tsx
This PR tries to solve the issues in split algorithm, fixes #1090
1.**Frontend:** task_split endpoint did not receive any data extracts, it rather received a file with `null` in it. 
I have awaited setDataExtractGeojson in frontend which in result provide the data extracts obtained from get_data_extracts to this endpoint
```
await dispatch(CreateProjectActions.setDataExtractGeojson(geojsonExtract));
```
2.  **Backend;** After the task_split endpoint received the data extracts, it had the tags in the stringified form. `split_by_sql` required tags in the json format, I needed to update that in the json format.
```
for feature in parsed_extract.get('features', []):
properties = feature.get('properties', {})
tags_value = properties.get('tags', None)
if isinstance(tags_value, str): …
```
=> Minor Fixes in task split process

docs/About.md, src/backend/Dockerfile, src/backend/app/auth/auth_routes.py, src/backend/app/auth/osm.py, src/backend/app/auth/roles.py, src/backend/app/db/db_models.py, src/backend/app/models/enums.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_deps.py, src/backend/app/tasks/tasks_crud.py, src/backend/migrations/003-project-roles.sql, src/backend/migrations/init/fmtm_base_schema.sql, src/backend/migrations/revert/003-project-roles.sql, src/frontend/src/components/createproject/ProjectDetailsForm.tsx
Fixes #243
This PR anticipates the merge of #1091 ✅ as it relies on the auth.
Also anticipates merge of #1096 ✅.
As described in discussion #1083 we are in the process of figuring out user roles.
I have implemented a basic configuration as such (this can change as needed):
```python
class UserRole(IntEnum, Enum):
"""Available roles assigned to a user site-wide in FMTM.
Can be used for global user permissions:
- READ_ONLY = write access blocked (i.e. banned)
- MAPPER = default for all
- ADMIN = super admin with access to everything
"""
READ_ONLY = -1
MAPPER = 0
ADMIN = 1
class ProjectRole(IntEnum, Enum):
"""Available roles assigned to a user for a specific project.
Invitation is required for a MAPPER to join a project.
All roles must be assigned by someone higher in the hierarchy:
- MAPPER …
```
=> Add basic user role support to backend

src/backend/app/auth/roles.py, src/backend/app/models/enums.py, src/backend/migrations/003-project-roles.sql, src/backend/migrations/init/fmtm_base_schema.sql
- We missed that the organisation_managers table already exists in the schema.
- That is the correct place to track org admins, not in user_roles.
- While making this edit I noticed the inconsistency with naming between British and American English.
- The schema was 'inspired' by Tasking Manager, so both use British English in the DB.
- This is hard to change, so we will keep it the same.
- For consistency we will update all code to use British English (organization --> organisation).
- Any user facing text will remain as American English `organization`.
- 👷‍♀️ Create small PRs. In most cases, this …
=> Use organisation manager table for organisation admins

src/backend/pdm.lock, src/backend/pyproject.toml
- Thanks to @Sujanadh for identifying a bug in fmtm-splitter
`fmtm-api  | sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table ways_line because other objects depend on it`
-  This would mostly be an issue only for developers that were using the splitting algorithm prior to moving to a separate repo.
- The dev/staging/prod servers will also be affected during upgrade, so to fix this
- Option 1: connect to the database to each an drop the tables once.
- Option 2: upgrade fmtm-splitter to `DROP CASCADE` the tables.
- As part of the upgrade to fmtm-splitter, SQLAlchemy was removed as a dependency.
- 📖 Read the FMTM Code of Conduct: …
=> Upgrade fmtm-splitter v0.2.6 --> v1.0.0rc0

src/backend/app/projects/project_crud.py
`geom_type` was saving values `True` or `False` instead of feature type. 
This PR addresses the issue and has made minor change where the `geom_type` is saved with the feature types from aoi.
This change in code first assigns the feature type to `geom_type` and compares with `FeatureCollection`.
N/A
=> hotfix: geom type not populated with feature type

src/backend/app/organisations/organisation_deps.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py
There was an issue where `get_organisation_by_id` was not found in `organisation_crud` since it was moved to `organisation_deps` and there was variable conflict `organisation` which is relationship field in the project model but str (name of organisation ) was passed.
This PR addresses the issue and updates the code using deps function and solved the conflicting issue in variable name.
`organisation -> organisation_name`
N/A
- 📝 Use descriptive commit …
=> Refactor: update project dashboard to use deps functions

.github/workflows/build_and_deploy.yml, .github/workflows/build_ci_img.yml, .github/workflows/build_odk_imgs.yml, .github/workflows/build_proxy_imgs.yml, .github/workflows/docs.yml, .github/workflows/pr_test_backend.yml, .github/workflows/pr_test_frontend.yml, .github/workflows/tag_build.yml, .github/workflows/tests/test_ci.sh, .github/workflows/wiki.yml, src/backend/app/db/db_models.py, src/backend/app/models/enums.py, src/backend/migrations/004-organisation-odk-creds.sql, src/backend/migrations/init/fmtm_base_schema.sql, src/backend/migrations/revert/004-organisation-odk-creds.sql
Fixes #902
Partially addresses #1043
- Remove some redundant fields and enums from project table.
- Replace `private` with more flexible `visibility`:
- PUBLIC=0
- PRIVATE=1
- INVITATION_ONLY=2
This adds the database fields and enums via migrations, plus the SQLAlchemy database models.
It **does not** add them to Pydantic schemas, or use them anywhere else in the code (to be utilised later).
=> Replace project.private field with project.visibility enum

INSTALL.md, docker-compose.development.yml, docker-compose.main.yml, docker-compose.staging.yml, docker-compose.yml, docs/dev/Backend.md, src/backend/Dockerfile, src/backend/app/auth/osm.py, src/backend/app/projects/project_routes.py
Fixes #954
- Adds replication to docker compose deployments:
- development/staging default to 2 api replicas.
- main(prod) defaults to 4 api replicas.
- Set api container image to use one uvicorn worker (on process per container, multiple containers). 
- Adds resource constraints for the api container (only):
```yaml
limits:
cpus: "0.9"
memory: 1500M
reservations:
cpus: "0.1"
memory: 100M
```
- 📗 Update any related documentation and include any relevant …
=> Add deployment container replicas and resource constraints

src/frontend/src/components/MapComponent/OpenLayersComponent/LayerSwitcher/index.js, src/frontend/src/components/MapComponent/OpenLayersComponent/Layers/VectorLayer.js, src/frontend/src/components/createnewproject/MapControlComponent.tsx, src/frontend/src/components/createnewproject/SplitTasks.tsx, src/frontend/src/components/createnewproject/validation/DataExtractValidation.tsx, src/frontend/src/hooks/Prompt.tsx, src/frontend/src/shared/AssetModules.js, src/frontend/src/store/slices/CreateProjectSlice.ts, src/frontend/src/store/types/ICreateProject.ts, src/frontend/src/views/NewDefineAreaMap.tsx
- Fix #1118
This PR adds an edit button on the map in the split-tasks step of the create project. With the edit button enabled, the AOI could be edited. Though the issue also mentions an undo button as well, it will be integrated with other features like drag later on as suggested by @varun2948 dai. Also, the UI of the map control has been updated.
=> Add AOI editing to map during project creation

src/backend/app/auth/auth_routes.py, src/backend/app/auth/roles.py, src/frontend/src/utilfunctions/login.ts
Related to #1141
- Using AuthUser pydantic model does not allow .get or ["var"] access.
- Params must be accessed via `.var`.
=> Fix all usage of AuthUser replace .get methods

src/backend/app/auth/osm.py
login_required deorator has this error.
```
File "/opt/app/auth/roles.py", line 41, in get_uid
if user_id := user_data.id:
└ {'id': 18764526, 'username': 'Niraj Adhikari', 'img_url': None}
AttributeError: 'dict' object has no attribute 'id'
```
`osm_auth.deserialize_access_token` function returns dict value. 
This change converts the dict into AuthUser.
- 📗 Update any related documentation and include any relevant …
=> fix: login_required decorator return value converted to AuthUser

contrib/qrcode_util/Dockerfile, contrib/qrcode_util/README.md, contrib/qrcode_util/build.sh, contrib/qrcode_util/qrcode_util.py, src/frontend/package.json, src/frontend/pnpm-lock.yaml, src/frontend/src/api/Files.js
- I updated the QR code generation to the frontend.
- I clearly didn't test well enough, as the QR codes don't work.
- I forgot to zlib encode the QR codes.
Example of how ODK Central frontend does this: https://github.com/getodk/central-frontend/blob/f254a175086b8acd83fd55607fa33b311d8aa6cc/src/components/collect-qr.vue#L43
Central frontend uses pako v1, but pako v2 has since changed it's API.
We are required to pass a `Uint8Array` to the deflate method.
- After zlib encoding incorrectly the QRCodes are much finer grained and cannot be read on the frontend:
- Example ODK Central frontend QR code:
- Correctly zlib encoded QR via pako v2:
- 📖 Read the FMTM Code of Conduct: …
=> ZLib compress dynamic QR codes from frontend

src/frontend/src/components/createnewproject/SplitTasks.tsx, src/frontend/src/components/home/ExploreProjectCard.tsx
- Fix #1104
This PR solves following issues: 
1. Home Page exploreProjectCard organization image crop. 
2. Remove text below progressBar in createProject popup of splitTasks.
Tested for different org logos and it seems to work fine: 
- Removed Text
=> Fix img proj popup

src/backend/app/db/db_models.py, src/backend/app/tasks/tasks_crud.py, src/backend/app/tasks/tasks_routes.py, src/backend/app/tasks/tasks_schemas.py
I tried updating task history in task-list. It was working fine. But to apply sorting and filtering operations for history list, it will be quite hectic since it is inside list of nested json. Using separate endpoint for only task history seems good idea and makes easy to apply filter.
This PR address this feature.
And yes, there are so many schemas with similar name, I will restructure those and use only required schemas.
=> Separate task history end point

src/frontend/src/components/CreateEditOrganization/validation/ConsentDetailsValidation.ts, src/frontend/src/constants/ConsentQuestions.tsx
- Fix #1067
This PR following issue on consent details form: 
1. Required removed from `participated question`
2. Atleast one checkbox to be marked on `log into question`
1. 
2.
=> Fix consent question

src/backend/app/db/postgis_utils.py, src/backend/app/organisations/organisation_schemas.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py, src/backend/app/tasks/tasks_schemas.py, src/backend/tests/conftest.py, src/backend/tests/test_projects_routes.py, src/frontend/src/api/CreateProjectService.ts, src/frontend/src/api/Project.js, src/frontend/src/components/createnewproject/SplitTasks.tsx, src/frontend/src/components/editproject/UpdateProjectArea.tsx, src/frontend/src/models/createproject/createProjectModel.ts, src/frontend/src/store/types/ICreateProject.ts, src/frontend/src/views/NewProjectDetails.jsx, src/frontend/src/views/ProjectDetailsV2.tsx
Fixes #1177
Possibly related to #1188, but untested for now.
- Lots of refactoring introduced a few bugs in project creation.
- This PR should fix various issues.
- TODO: fix extracting geoms from the flatgeobuf generated by raw-data-api (it contains multiple geom types).
```
fmtm-api-1  | 2024-02-12 17:17:51.122 | WARNING  | app.projects.project_crud:generate_appuser_files:1297 | (psycopg2.errors.InternalError_) flatgeobuf: GeometryReader::read: Unknown type 0
fmtm-api-1  |
fmtm-api-1  | [SQL:
fmtm-api-1  |         DROP TABLE IF EXISTS public.temp_fgb CASCADE;
fmtm-api-1  |
fmtm-api-1  |         SELECT ST_FromFlatGeobufToTable('public', 'temp_fgb', %(fgb_bytes)s);
fmtm-api-1  |
fmtm-api-1  |         SELECT jsonb_build_object(
fmtm-api-1  |             'type', 'FeatureCollection', …
```
=> Project creation workflow fixes (task splitting)

src/frontend/src/api/task.ts, src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx
- Fix #1245 
Since the `bbox` is now sent under the `properties` key of `outline_geojson`. The code has been updated accordingly.
=> fix josmUpload: send bbox from geojson properties

src/backend/app/submissions/submission_routes.py
The submission was not loaded into JOSM due to invalid osm file content.
- Fixes #1245 
Previously, the xml file returned from `json2osm` used to lack `</osm>`, because of which it was manually added to the `get_osm_xml` endpoint. Now `json2osm` generates valid OSM files, eliminating the need for manual addition of the tag in the `get_osm_xml` endpoint.
N/A
=> Removing redundant code for removing extra closing </osm> tag

src/backend/app/db/postgis_utils.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py
- The data extract splitting, and hence the ODK Central form media, were generating duplicate geometries.
- Fixed to split the data extract correctly by task boundary.
- Also added the `task_id` param to `/projects/features/download`, so a geojson can be downloaded per project, or per task.
@manjitapandey hopefully the final fix to the project creation workflow 🤞 
=> Fix data extract splitting by task area

src/frontend/src/styles/home.scss
This PR changes the background color of the map to white as the current blue color coincides with the water color that confuses the user in distinguishing between a loading tile and a water area.
=> fix mapBgColor: map background changed to white

src/frontend/src/components/createnewproject/UploadArea.tsx
Fixes #1276 
This PR ensures that the form state is cleared including the data extract when the Geojson is redrawn enabling user to extract data each time the AOI is changed.
-  Able to generate extract for the second time.
=> fix:(create-project): reset data extract when geojson is redrawn

src/backend/app/projects/project_routes.py
- Fixes #1237
This change checks for the project name if it already exists or not. If exists, it returns message `"Project already exists with the name {project_name}"`
N/A
=> Check for existing project name

src/frontend/src/store/slices/CommonSlice.ts, src/frontend/src/store/slices/HomeSlice.ts, src/frontend/src/store/slices/LoginSlice.ts, src/frontend/src/store/slices/ProjectSlice.ts, src/frontend/src/store/slices/TaskSlice.ts, src/frontend/src/store/types/ICommon.ts, src/frontend/src/store/types/IHome.ts, src/frontend/src/store/types/ILogin.ts, src/frontend/src/store/types/IProject.ts, src/frontend/src/store/types/ISubmissions.ts, src/frontend/src/store/types/ITask.ts
This PR adds TypeScript types to the slice state where the TypeScript type was missing.
=> Feat ts type add

src/frontend/src/views/Organisation.tsx
Fixes #1251
- Previously the My Organisations endpoint was called on page load, even if the user does not click the tab.
- This change means the endpoint is not called unless the user clicks the tab.
- The endpoint is only called once despite changing tabs.
=> Only load My Organisations once on tab click

src/frontend/src/components/GenerateBasemap.jsx, src/frontend/src/components/ProjectDetailsV2/ProjectOptions.tsx, src/frontend/src/components/ProjectDetailsV2/TaskSectionPopup.tsx, src/frontend/src/store/slices/ProjectSlice.ts, src/frontend/src/store/types/IProject.ts, src/frontend/src/views/ProjectDetailsV2.tsx
- fixes #1243
This PR adds a global state to open and close the generate mb tiles modal. And then the functionality is implemented in download icon of `TaskSectionPopup`.
=> Implement download on clicking `download-icon` in `qrpopup` 

src/backend/app/central/central_crud.py, src/backend/app/main.py, src/backend/app/projects/project_routes.py, src/frontend/src/components/createnewproject/SelectForm.tsx
- Improved the form validation logic slightly.
- Option to upload xml xform directly.
@manjitapandey 
=> Allow custom XForm uploads, in addition to XLSForms

src/backend/app/auth/roles.py, src/backend/app/central/central_crud.py, src/backend/app/db/postgis_utils.py, src/backend/app/helpers/__init__.py, src/backend/app/helpers/helper_crud.py, src/backend/app/helpers/helper_routes.py, src/backend/app/main.py, src/backend/app/organisations/__init__.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py, src/backend/app/submissions/submission_crud.py, src/backend/app/submissions/submission_routes.py, src/backend/pdm.lock, src/backend/pyproject.toml, src/backend/tests/test_projects_routes.py, src/frontend/src/components/ManageProject/EditTab/FormUpdateTab.tsx, src/frontend/src/components/createnewproject/SelectForm.tsx, src/frontend/src/store/slices/CreateProjectSlice.ts
Fixes #1275
Fixes #1242
- Updates osm-fieldwork --> 0.5.1. OdkForm.form_fields is now called `formFields` and it returns an error if the request fails @Sujanadh 
- Fixes project creation ODK xform creation with upload media, with caveat #1309
- Fixes form updating in project update tabs on backend and frontend.
- Once this is merged #1308 can be worked on.
- Adds extra UI to update the category during form update (mandatory).
- Removes form categories that either do not work, or are irrelevant to FMTM.
- Updates `project_admin` role to return a dict of both the DbProject and DbUser @Sujanadh FYI
- Added a `helper` router, with routes for simple helper utils. The one endpoint so far is to fix custom data extracts by adding the correct properties tags before project creation.
- The logic to …
=> Fix xform name format for Central + edit form functionality 

src/frontend/src/api/CreateProjectService.ts, src/frontend/src/components/ManageProject/DeleteTab/ProjectDeleteTab.tsx, src/frontend/src/components/ManageProject/DeleteTab/index.tsx, src/frontend/src/utilfunctions/cookieUtils.ts, src/frontend/src/utilities/ProtectedRoute.jsx, src/frontend/src/views/ManageProject.tsx, src/frontend/src/views/Organisation.tsx
- The project deletion UI was removed with the updates.
- I added a basic implementation that can be improved upon.
- I'm not sure if I used the `common/Modal` as intended, but it works for now (perhaps we need an extra field for the footer / to include modal buttons/actions.
=> Add simple ui to delete projects on frontend

src/backend/app/central/central_crud.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/pdm.lock, src/backend/pyproject.toml, src/backend/tests/test_projects_routes.py, src/frontend/src/api/CreateProjectService.ts
- We were parsing XML directly from the user previously.
- This opens up FMTM to a whole host of exploits and is bad security.
- Using the defusedxml package is a drop in replacement for Python standard lib xml.
- It removes potential security threats.
- I also refactored to make the XForm parsing logic more modular.
- We now only parse the XLSForm once during project creation, then pass through the data to the task creation.
- This should hopefully prevent issues of filesystem conflicts between API replicas etc.
Affects the form validity check during project creation, and the file form parsing in `generate-project-files`.
- 📖 Read the FMTM Code of Conduct: …
=> Use defusedxml for xml parsing, only parse one in proj creation

src/backend/app/submissions/submission_crud.py, src/backend/app/submissions/submission_routes.py, src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx, src/frontend/src/views/SubmissionDetails.tsx
- Fixes #1323 
This PR updates the exisiting task_submission endpoint where new param submission_id is added which is used to fetch each submission detail from odk-central.
```
{
"start": "2024-03-04T17:33:42.783+05:45",
"end": "2024-03-04T17:34:31.232+05:45",
"today": "2024-03-04",
"phonenumber": "2312",
"deviceid": "collect:v1M8715bjhnkw5xg",
"username": "svcfmtm",
"email": "NOT IMPLEMENTED",
"instructions": null,
"warmup": null,
"all": {
"model": "basic",
"existing": "802349380",
"xid": "802349380",
"xlocation": "27.714485 85.317777 0 0; 27.714428 85.318276 0 0; 27.714526 85.31829 0 0; 27.714583 85.317792 0 0; 27.714485 85.317777 0 0",
"buildings": {
"category": "housing",
"name": "project_224_task_2313",
"building_material": null,
"building_levels": null,
"religion": null, …
```
=> Submission detail of each task's submission

src/backend/app/central/central_crud.py, src/backend/pdm.lock, src/backend/pyproject.toml
- We need temp files currently to move the XForm around.
- I made a patch to hotosm/pyxform with a PR in that repo.
- Until the PR is merged, we can use the forked repo code.
- Allows using BytesIO objects for XForm reading, conversion, and validation.
=> Use pyxform fork for BytesIO XForm usage

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py
- Fixes #1292 
This PR fixes the issue updating search filter query.
N/A
=> Fix search projects

src/backend/app/auth/auth_routes.py
`user_role` was not updated in `me` endpoint. The default mapper role was passed, irrespective of other roles.
This PR updates `me` endpoint, which returns `dbuser` with respective roles instead of `authuser`, as `authuser` doesn't possess any roles.
N/A
=> Return db user instead of Auth User in me endpoint.

src/backend/app/db/postgis_utils.py
- Data extracts were not correct in ODK Central due to using ST_Within, without first determining the centroid of the polygon.
- If the polygon was not entirely contained within the task area then it was not included.
=> Hotfix use centroids to determine extract tasks split

src/frontend/src/assets/images/navigation.svg, src/frontend/src/components/home/ProjectListMap.tsx
=> feat: navigation WIP

src/backend/app/projects/project_schemas.py, src/frontend/src/components/home/ProjectListMap.tsx
- Fixes #1357 
When the project is created without boundary , it fails the `/summaries` endpoint since it requires centroid for clustering.
This PR handles the null case of centroid in the schema.
N/A
N/A
=> Resolved issues on project summaries with no centroids

src/frontend/src/components/CreateEditOrganization/validation/OrganizationDetailsValidation.ts, src/frontend/src/components/ManageProject/EditTab/validation/EditProjectDetailsValidation.ts, src/frontend/src/components/createnewproject/validation/CreateProjectValidation.tsx, src/frontend/src/utilfunctions/commonUtils.ts
- Fix #1358
This PR adds validation to different form validations to validate input field. Currently the input fields doesn't validate white spaces and doesn't show error. Now before comparing input value with empty string, the input value is first trimmed then compared with empty string.
Validation white spaces also: 
- ✅ Provide tests for your …
=> Fix blank space input validation

src/backend/app/auth/auth_routes.py, src/backend/app/auth/osm.py, src/backend/tests/conftest.py, src/frontend/src/utilfunctions/login.ts
- Fixes #1333 
- This PR adds user roles along with project_roles, associated project, and organisation if created by the user, which means if the user is the org_admin.
- It implements raw SQL in order to check and update the user or create the user.
- Tried to use the CASE statement, but it didn't work as expected since it only allows to return boolean-type results (true, false) but not for update purposes, if I am not wrong.
One problem I encountered while performing the insert action was that I needed to mention all the not null fields even though they have default values, unlike those handled by Alchemy automatically since we do not have the default values set at the database level.
Different Responses: …
=> Implemented raw sql replacing sqlalchemy in me endpoint

src/frontend/src/components/MapComponent/OpenLayersComponent/Layers/VectorLayer.js, src/frontend/src/components/createnewproject/UploadArea.tsx
- Related to #1365 
This PR solves the page crash problem whenever a geojson with empty features is uploaded.
=> fix uploadArea: invalid geojson error handling

src/backend/app/auth/auth_routes.py, src/backend/app/auth/osm.py
- Fixes #1372 
There was a mismatch between the profile image key in the backend with OSM data. This PR solves this, making it consistent with the OSM data resolving issue of images not being saved in the database and not visible in user head after login.
=> Profile Image Not Updating in User Login

src/backend/app/submissions/submission_crud.py
- issue #1378 
Previously, submissions were updated to S3 by checking the last submission date, but if someone changes the review state, it won't change the date due to which submission wasn't updated. This PR adds the review state to the submission meta json in s3, which is compared with the review state obtained from odkcentral. Those obtained lists of review states are converted into hash strings so that they can be compared easily without going through every element of the list.
- …
=> Update submission in s3 even after review state is updated

src/frontend/src/components/ProjectDetailsV2/MapControlComponent.tsx, src/frontend/src/components/home/ProjectListMap.tsx, src/frontend/src/store/slices/ProjectSlice.ts, src/frontend/src/store/types/IProject.ts, src/frontend/src/utilfunctions/Geolocation.ts, src/frontend/src/views/ProjectDetailsV2.tsx
Also solves #1343
This PR covers the following things: 
1. Remove geolocation from projectListMap component(HomePage)
2. Generate Mbtiles btn shift to bottom for mobile view
3. Only ask permissions if the geolocation status is turned on
=> Feat project details geolocation integration

docker-compose.main.yml, src/frontend/prod.dockerfile, src/frontend/src/utilities/CustomDrawer.jsx
- Minor improvement to DX and frontend debugging.
- Add a toggleable debugging console, that displays the output of the console.
- Helpful on mobile, when it's not easy to bring up browser debug tools.
Menu
Console
=> Toggleable debug console on mobile in local/dev/stage

src/backend/app/auth/auth_routes.py
- Fixes #1289 
This PR adds new endpoint that checks for login cookie validity. Returns True if valid and False for the invalid cookie.
=> Separate endpoint to check the validity of login cookies.

src/frontend/src/components/ProjectDetailsV2/Comments.tsx, src/frontend/src/components/ProjectDetailsV2/Instructions.tsx, src/frontend/src/components/common/Editor/Editor.tsx, src/frontend/src/components/common/Editor/editorStyles.scss
Related to #1377
This PR enhances the UI of the comments & instructions section of project-details page according to the provided design.
=> Fix comments intructions UI enhancement

src/frontend/src/components/MapComponent/OpenLayersComponent/AsyncPopup/AsyncPopup.tsx, src/frontend/src/components/ProjectDetailsV2/TaskSectionPopup.tsx, src/frontend/src/views/ProjectDetailsV2.tsx
- Related to #1382 
This PR solvesthe  following issues: 
1. Vertically align QR popup to center
2. Project Details - Building feature info popup render outside viewport fix
=> Fix popup offscreen

src/frontend/src/components/ProjectDetailsV2/TaskSectionPopup.tsx, src/frontend/src/components/createnewproject/UploadArea.tsx
This PR fixes the following thing:
1. Update `TaskSectionPopup` icons
2. Limit upload-area AOI size to 200 sq.km.
3. AOI area size not clearing on AOI clear issue fix
=> Fix taskpopup aoi

src/backend/Dockerfile, src/backend/app/projects/project_crud.py, src/frontend/index.html, src/frontend/package.json, src/frontend/pnpm-lock.yaml, src/frontend/src/App.tsx, src/frontend/src/api/Files.js, src/frontend/src/api/Project.js, src/frontend/src/components/GenerateBasemap.jsx, src/frontend/src/components/MapComponent/OpenLayersComponent/LayerSwitcher/index.js, src/frontend/src/hooks/Prompt.tsx, src/frontend/src/store/slices/ProjectSlice.ts, src/frontend/src/store/types/IProject.ts, src/frontend/src/views/ProjectDetailsV2.tsx
None
- Started work on loading PMTile files into browser OPFS storage, then reading when offline.
- Loading the PMTiles archive into OPFS.
- Reading the PMTiles into OPFS.
- Parsing the PMTiles file as a PMTiles object.
- Assess if the user is offline or not (likely via PWA functionalities).
- If user is offline, load the tiles from OPFS to render.
- Render the PMTiles in OpenLayers.
@varun2948 @NSUWAL123 
- OPFS is unique per domain, so there is no chance of file mixup.
- The pmtile archives are for the entire project area, stored under `PROJECT_ID/all.pmtiles`.
- The lightning bolt icon button will download the tiles to OPFS, instead of download directory on filesystem.
- 📖 Read the FMTM …
=> OPFS-based offline-first PMTile basemaps

src/frontend/src/components/CreateEditOrganization/ConsentDetailsForm.tsx, src/frontend/src/components/CreateEditOrganization/CreateEditOrganizationForm.tsx, src/frontend/src/components/ManageProject/DeleteTab/index.tsx, src/frontend/src/components/ManageProject/EditTab/FormUpdateTab.tsx, src/frontend/src/components/ManageProject/EditTab/ProjectDescriptionTab.tsx, src/frontend/src/components/ManageProject/UserTab/AssignTab.tsx, src/frontend/src/components/ManageProject/UserTab/InviteTab.tsx, src/frontend/src/components/ProjectSubmissions/SubmissionsInfographics.tsx, src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx, src/frontend/src/components/createnewproject/DataExtract.tsx, src/frontend/src/components/createnewproject/ProjectDetailsForm.tsx, src/frontend/src/components/createnewproject/SelectForm.tsx, src/frontend/src/components/createnewproject/SplitTasks.tsx, src/frontend/src/components/createnewproject/UploadArea.tsx, src/frontend/src/utilfunctions/useDocumentTitle.ts, src/frontend/src/views/ApproveOrganization.tsx, src/frontend/src/views/Home.tsx, src/frontend/src/views/Organisation.tsx, src/frontend/src/views/ProjectDetailsV2.tsx, src/frontend/src/views/SubmissionDetails.tsx
- Related to #572
This PR adds document titles for each page across all pages.
=> Feat page documenttitle add

src/frontend/src/api/CreateProjectService.ts
- issue #1308 
This PR addresses the issue by returning the error message returned by the endpoint instead of stringifying it.
=> Return proper error message returned by the validate-form endpoint

src/backend/app/tasks/tasks_crud.py, src/backend/app/tasks/tasks_routes.py
…history
- Issue #1399 
- update task status endpoint was returning whole task response which is not necessary
- username and profile image were not seen in task history
- This PR updates the response of update task status endpoint to return only the updated status of that task
- This will create consistent response type for both updating and getting task history
- adds username and profile image in both response
Response of update task status:
```
{
"task_id": 2422,
"action_text": "Status changed from LOCKED_FOR_MAPPING to MAPPED by: svcfmtm",
"action_date": "2024-04-03T11:57:27.808263",
"status": "MAPPED",
"username": "svcfmtm",
"profile_img": null
}
```
Response of task history
```
[
{
"task_id": 2422,
"action_text": "Status changed from LOCKED_FOR_MAPPING to MAPPED by: svcfmtm", …
```
=> Consistent response for both update task status and task history endpoint

src/backend/app/tasks/tasks_crud.py, src/backend/app/tasks/tasks_routes.py, src/backend/app/tasks/tasks_schemas.py, src/frontend/src/components/ProjectDetailsV2/Comments.tsx
- There was inconsistency in the response for both task comment and task history, even though they have same table and same fields for both
- Profile image was not seen in comment list
This PR refactors the task comment endpoints , adds profile image and updates the schema to use existing schema, which is `TaskHistoryOut`. It now returns responses for both `task-comment` and `task_history` in the same way for both `post` and `get` requests.
In the frontend side , i have updated the endpoint, but further works are still not done, which would be completed by @NSUWAL123 
get task comment
```
[
{
"id": 137,
"task_id": 2430,
"action_text": "<p>testing comment</p>",
"action_date": "2024-04-04T08:55:45.014438",
"username": "Sujan Adhikari",
"profile_img": …
```
=> Refactor task comment response and schema

src/backend/app/central/central_crud.py, src/backend/app/db/db_models.py, src/backend/app/db/postgis_utils.py, src/backend/app/helpers/helper_routes.py, src/backend/app/main.py, src/backend/app/models/enums.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/app/tasks/task_deps.py, src/backend/app/tasks/tasks_routes.py, src/backend/migrations/002-add-xforms-table.sql, src/backend/migrations/init/fmtm_base_schema.sql, src/backend/migrations/qrcode_to_odktoken.py, src/backend/migrations/revert/002-add-xform-table.sql, src/backend/pdm.lock, src/backend/pyproject.toml, src/backend/tests/test_projects_routes.py, src/frontend/src/api/CreateProjectService.ts, src/frontend/src/api/Files.js, src/frontend/src/api/Project.js, src/frontend/src/components/DialogTaskActions.jsx, src/frontend/src/components/ProjectDetailsV2/TaskSectionPopup.tsx, src/frontend/src/components/createnewproject/SplitTasks.tsx, src/frontend/src/store/slices/CreateProjectSlice.ts, src/frontend/src/store/types/ICreateProject.ts
Related to https://github.com/hotosm/fmtm/issues/1356
Linked to https://github.com/hotosm/fmtm/issues/1319
Major update to how FMTM works:
- Instead of one form per task, we only need one form per building.
- An entity list is made per project.
- The entities can be filtered by the task_id field for display in ODK Collect.
- We can also launch a form in ODK Collect with a specific entity prefilled.
- We should be able to use the form to update the entities fields, e.g. a `status` field for when complete.
Things to do:
- Needs testing for project create and form update.
- I haven't updated any of the submissions logic (perhaps in another PR?)
- But now we can update to use the API on the form for the entire project.
- If you could please review & test it would be a great help @Sujanadh 🙏 …
=> Implement ODK Entities for project creation

.env.example, src/backend/app/config.py, src/backend/app/projects/project_crud.py, src/backend/app/s3.py, src/backend/pdm.lock, src/backend/pyproject.toml
Fixes #1398
- Adds environment / config variable `OSM_SVC_ACCOUNT_TOKEN`, which is picked up by `osm-rawdata` and passed as an auth token to `raw-data-api`.
- This authenticates and enables tracking with raw-data-api.
- It also allows for our data extracts to be retained past a 90 day deletion policy.
- The proposed structure is: `fmtm/{domain}/data_extract.fgb`
- Create a new data extract.
- The returned URL should be with the folder structure mentioned.
- 📗 Update any related …
=> Add optional auth to raw-data-api calls, plus folder structure for persistence

src/backend/Dockerfile, src/backend/app/main.py
Partially addresses #1443
(still remaining: add version.json to /app/version.json for both backend and frontend, in CI workflow)
- Adds endpoints:
- /__version__ - CI/build details
- /__heartbeat__ - heartbeat including database connectivity check
- /__lbheartbeat__ - check for API response only, no services
- 📗 Update any …
=> Add Mozilla Dockerflow spec endpoints for devops / healthchecks

src/backend/app/tasks/tasks_schemas.py, src/frontend/src/api/Project.js, src/frontend/src/api/ProjectTaskStatus.js, src/frontend/src/components/Activities.jsx, src/frontend/src/hooks/MapStyles.js, src/frontend/src/models/createproject/createProjectModel.ts, src/frontend/src/models/project/projectModel.ts, src/frontend/src/store/types/ICreateProject.ts, src/frontend/src/utilfunctions/getTaskStatusStyle.js, src/frontend/src/views/ProjectDetailsV2.tsx
- I don't think we need to calculate the task outline centroid in the backend and pass to the frontend.
- We can simply use OpenLayers Extent.getCenter `ol.extent.getCenter` function.
Seems to work fine for displaying the lock icon in the center of the task area:
=> Replace unecessary outline_centroid calculation on backend, replace with ol function

src/backend/app/projects/project_routes.py
In recent changes, we implemented temp login, where we enforced the mapper role. But we cannot use mapper role before project is created, since this role checks if the project is public or not. So, it failed in data extract, since it is independent of project.
This PR changes role of data extract from mapper to login_required.
N/A
- 📗 Update any related documentation …
=> Role mapper to login required in data extract

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_schemas.py
Related to discussion https://github.com/hotosm/fmtm/discussions/1268
- Fixed a bug where no hashtags were appended. Now it always appends the #FMTM tag.
- Added an extra tag {domain}-{project_id}, for pulling into the final OSM submission for easier identification of the FMTM data in OSM.
- 📗 Update any related documentation …
=> Append extra hashtag to projects with domain and project id identifier

src/frontend/src/App.tsx
Related to issue #1289
Follow on from backend PR #1380
- Calls the introspect endpoint on app first mount (i.e. on refresh).
- If the auth fails, then clears the frontend login state.
- If there is a mismatch between the logged in user via the API and login state on the frontend, then also clear the login state.
- This scenario can occur when a user logs in as one user, then logs in as another user.
- The frontend may remember the first user details, but the API is actually authenticated with the new user details.
During development we no longer see a logged in user:
This is because if `DEBUG` is set on the API, then auth is bypassed and the user is always `localadmin`.
I.e. all endpoints can be accessed without requiring auth.
> Note this is because it's not possible to *actually* login …
=> Invalidate login if mismatch between existing and new user

src/backend/app/auth/roles.py, src/backend/app/projects/project_deps.py, src/backend/app/projects/project_routes.py, src/frontend/src/api/Project.js, src/frontend/src/components/GenerateBasemap.jsx
Related to #1463
@manjitapandey , marked QA ready 👍 
- The issue was adding the `mapper` auth requirement to the endpoint.
- It requires the `project_id` to be passed in, otherwise it fails.
- I fixed to do this, but also refactored 3 tile related endpoints to use schema `/{project_id}/thing-to-do`, which is more in line with REST URL standards.
- Click to download mbtiles.
=> Fix basemap mbtile file downloads

docs/dev/Setup.md, src/backend/app/auth/auth_routes.py, src/backend/app/helpers/helper_routes.py, src/frontend/src/App.tsx, src/frontend/src/api/Login.ts, src/frontend/src/components/LoginPopup.tsx, src/frontend/src/utilfunctions/login.ts, src/frontend/src/views/Authorized.tsx
- Improves the logic for frontend login (full async/await).
- Removes all handling of access_token in API JSON and frontend (cookie httpOnly).
- Reuse the same `/auth/me` call logic for temp and OSM auth.
- Simplify LoginPopup slightly to reduce number of clicks required.
- Both login methods work well.
The OSM login tokens should not change, but we have encountered strange behaviour.
If they change again, we should consider other options - using our own JWT auth would be fine.
Try both login methods - they should work.
- …
=> Fix login methods after temp cookie auth

src/frontend/src/components/MapComponent/OpenLayersComponent/AsyncPopup/AsyncPopup.tsx, src/frontend/src/components/common/RadioButton.tsx, src/frontend/src/components/createnewproject/DataExtract.tsx, src/frontend/src/components/createnewproject/SplitTasks.tsx, src/frontend/src/store/slices/CreateProjectSlice.ts, src/frontend/src/store/types/ICreateProject.ts, src/frontend/src/utilfunctions/checkGeomTypeInGeojson.ts, src/frontend/src/views/ProjectDetailsV2.tsx
- Related to #1453 
This PR solves the issue of every task locked showing message  _This task was locked by you._
Now the message is shown if task `locked_by_user` is the signed in user itselft.
Hover shown if signed in use is the one who locked the task
Hover not shown if signed in use is the one who didn't locked the task
- 📗 Update any related documentation and …
=> Fix task hover popup & disable splitting algo without linestring

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py, src/frontend/src/api/Project.js, src/frontend/src/models/project/projectModel.ts
- Issue #1451 
This PR solves the issue and returns the actual contributor count on the project summary page.
- refactored some of the unnecessary code from project schema 
=> Actual contributors count in project summary

src/frontend/src/utilfunctions/getTaskStatusStyle.js, src/frontend/src/views/ProjectDetailsV2.tsx
- Related to #1468
This PR contains work on colorization of feature of each entity based on its mapping status.
When submission is made via ODK the feature status is changed to MAPPED changing feature color to light blue.
=> Colour features based on entity mapping status

src/backend/app/projects/project_deps.py, src/backend/app/submissions/submission_crud.py, src/backend/app/submissions/submission_routes.py, src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx, src/frontend/src/views/SubmissionDetails.tsx
- related issue(milestone) : #1502
This PR refactors the `submission_table`, individual `submission-detail`, and `update_review_state` along with the filter directly to the submission table using task id instead of a separate endpoint for task submission.
- changed the endpoint of `task_submission` to `submission-detail`
- extracted `task_id` from submission as `task_id` is not used as a param anymore
N/A …
=> Refactor submission endpoints backend/frontend

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/app/submissions/submission_crud.py, src/backend/app/submissions/submission_routes.py
- Related Issue #1499
This PR updates the project dashboard endpoint to correctly fetch the submission metadata from odk central which used to depend on the cached submissions in s3 that is not required now onwards as we can directly get it from odk central.
=> Submissions in project dashboard and bar graph.

src/backend/app/db/postgis_utils.py
- Issue #1510 
The issue actually lies on the sql where task_id is populated in each feature(data extracts) where it was done randomly and later on filtered using post gis extension st_within to filter the features based on the task boundary but it failed to update the properties where task_id was randomly populated before filtering them. 
For example:-
here the feature id/osm_id 905893000 actually lies on task 3 but in properties task_id is 2.
The problem with all features not being loaded is because it looks for the task_id from the properties but while selecting task id it actually uses its outline in odk collect, so the filtering is improper here as the match for the same task_id is spread throughout the project AOI irrespective of its task outline meaning the feature can be found on …
=> All features/entities loaded in odk collect

src/backend/app/submissions/submission_routes.py
There was an issue while downloading submissions in geojson due to typo error while assigning filename as project name prefix
This PR addresses the issue by correctly using prefix name as a filename.
=> Typo error in project name prefix in submission-download-geojson

.env.example, src/backend/app/config.py, src/backend/app/helpers/helper_routes.py, src/backend/app/projects/project_crud.py, src/backend/pdm.lock, src/backend/pyproject.toml
Related to #1497
- This is a temp solution.
- Separates service account tokens for raw-data-api data extract generation and FMTM temporary auth.
- Two variables: `RAW_DATA_API_AUTH_TOKEN` and `OSM_SVC_ACCOUNT_TOKEN`.
- In future we may remove the temp auth `OSM_SVC_ACCOUNT_TOKEN` and replace with a JWT-based auth.
=> Separate svc accounts for raw-data-api and fmtm

src/backend/app/config.py, src/backend/app/db/db_models.py, src/backend/app/helpers/helper_routes.py, src/backend/app/main.py, src/backend/app/projects/project_crud.py, src/backend/migrations/init/fmtm_base_schema.sql, src/frontend/src/components/common/Checkbox.tsx, src/frontend/src/components/createnewproject/SelectForm.tsx
**Do not merge this code, as I first need to be granted a license for using the Excel/spreadsheet web component (it is normally commercial, but they can provide an NGO license, tbc)**.
- Updated logic for XLSForm loading at backend startup. Removes old forms that no longer exist.
- Currently only the **buildings** form is available, after the Entity update.
- Added a comment that users should **extend** an existing XLSForm if they want to provide a custom form.
- Added a link during project creation to download the template form.
- Also added a link to an interactive XLSX editor, with the form preloaded (essentially Excel in the browser!).
- I did a lot of research and dug into the XForm editing functionality of KoboToolbox.
- It's quite a convoluted mess, using CoffeeScript - I struggled …
=> Add link for interactive xlsform editing during project creation

src/backend/app/db/postgis_utils.py, src/backend/app/projects/project_schemas.py
Fixes #1388
- We were chaining three computed_field:
outline_geojson --> outline --> centroid --> location_str
- Perhaps this was causing an issue, or there is a bug in Pydantic 🤷 
- Moved the location_str validation to a model_validator, so it runs after all the other fields are computed / validated at the end.
- Should hopefully fix missing location strings.
=> Generate project location string in model_validator

src/backend/app/central/central_crud.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py, src/backend/pdm.lock, src/backend/pyproject.toml, src/frontend/src/api/CreateProjectService.ts, src/frontend/src/api/Project.js, src/frontend/src/components/DialogTaskActions.jsx, src/frontend/src/components/ManageProject/EditTab/FormUpdateTab.tsx, src/frontend/src/components/ProjectDetailsV2/FeatureSelectionPopup.tsx, src/frontend/src/models/project/projectModel.ts
Related to #1356
- There was an issue where the frontend ODK Collect intent URL was using the old `{title}_{category}` XFormID format.
- I updated to pass the XFormID to the frontend for a project, then include in the intent URL.
- I also fixed the form updating via the UI, which also required the XFormID to passed (to know which form to update.
- Finally the script to modify the xform before upload was using the old task ids, and not the task index. Updated too.
- This can be tested either on the development server, or via tunnel: `just start tunnel`.
- A new project should be made with the tunnel ODK Central URL and loading by intent can be tested. …
=> Fix loading entity by intent using uuid xformid

src/backend/app/central/central_crud.py, src/backend/app/helpers/helper_routes.py, src/backend/app/models/enums.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_deps.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py, src/backend/app/submissions/submission_crud.py, src/backend/app/submissions/submission_routes.py, src/backend/pdm.lock, src/backend/pyproject.toml, src/frontend/src/api/CreateProjectService.ts, src/frontend/src/api/Project.js, src/frontend/src/components/createnewproject/SplitTasks.tsx
Work towards #1540
Fixes #1554
- Final piece of work for 2024.3.1 release.
- Added the `healthcare` category back into FMTM.
- Also updated all Entity lists (dataset) to default be named `features`, for consistency.
- It's not perfect, as the splitting algorithm will likely not work with such sparse data, plus point data, but it's a start.
- The likely workflow is users uploading their own task areas for mapping sparse health centers.
Also includes:
- The work on fmtm-splitter (v1.2.2) for #1554
- Adds a 5 second delay after project creation before redirect, to give time for the backend to catchup @manjitapandey 
- Minor improvement to backend: caching of the get_odk_credentials, so it is only called once (previously up to 5 times).
- Using an enum XLSFormType to enable / disable and …
=> Add healthcare form category & minor fixes

src/backend/app/central/central_crud.py, src/backend/pdm.lock, src/backend/pyproject.toml
From osm-fieldwork https://github.com/hotosm/osm-fieldwork/commit/6da506b628efbdb9d485da65f3aa85f919f1ed0b
Fixes #1581
Fixes #1576
- An update to osm-fieldwork included some restructured XLSForms (major overhaul for nicer user experience).
- The ODK Central server has also recently been updated.
- The `save_to` column was missing from the survey sheet (perhaps a new requirement in latest ODK Collect).
- This PR adds the column back in, so the status is updated on form submit.
- There is no guarantee the `task_id` field will be passed to the submission, as it has a `relevant` trigger, meaning if a building is selected then the `task_id` is omitted.
- The `task_id` field in the XLSForm is only there for filtering the features for selection on the map (and map be moved in future releases …
=> Ensure `status` Entity field is updated alongside survey form `status` field

src/backend/app/central/central_crud.py, src/backend/app/submissions/submission_crud.py, src/backend/app/submissions/submission_routes.py, src/backend/pdm.lock, src/backend/pyproject.toml
Related to #1581
- The `task_id` field was not mandatory on the XLSForms, but was required for the submission table filtering in FMTM.
- I updated osm-fieldwork XLSForms to have a mandatory `task_id` field, that is calculated from the Entity task_id.
- The existing `task_id` field was renamed to `task_filter` and is only used to filter features by the task area in ODK Collect (field ignored if a feature is already selected).
- Easiest to test on dev / staging, or using cloudflare tunnels: `just --unstable start tunnel`.
- The entire mapping flow can be complete using the tunnel url for odk central.
- 👷‍♀️ Create small …
=> Ensure task_id field is always included with submissions

src/frontend/src/components/MapComponent/OpenLayersComponent/LayerSwitcher/index.js, src/frontend/src/components/ProjectSubmissions/TaskSubmissionsMap.tsx, src/frontend/src/components/SubmissionMap/SubmissionInstanceMap.jsx, src/frontend/src/components/home/ProjectListMap.tsx, src/frontend/src/views/EditProjectArea.tsx, src/frontend/src/views/NewDefineAreaMap.tsx, src/frontend/src/views/ProjectDetailsV2.tsx
- Related to #1599
This PR replaces the current default baselayer(Mapbox) to OSM to solve the map not visible issue.
=> fix(map): set default baseLayer to OSM

src/backend/app/models/enums.py
- Related to #1605
This PR contains works to fix the `task_history.action` column not being updated in the DB. 
It seems `get_action_for_status_change` was only returning `RELEASED_FOR_MAPPING`.
=> Update task_history.action correctly on db

src/backend/migrations/004-update-default-values.sql, src/backend/migrations/init/fmtm_base_schema.sql, src/backend/migrations/revert/004-update-default-values.sql
- Issue No.  #1337 
This PR updates the fmtm base database schema by adding default values wherever necessary at the database level instead of defining them using sqlalchemy.
SQL query to insert data in the user table without mentioning other fields where default values are set.
Result
Here, `role`, `is_email_verified`, `is_expert` , `mapping_level` , `tasks_mapped`, `tasks_validated` are auto-populated with default values.
- ✅ Provide …
=> Updated default values in the database

src/backend/app/auth/auth_routes.py, src/backend/app/db/db_models.py, src/backend/app/models/enums.py, src/backend/app/projects/project_crud.py, src/backend/migrations/004-update-default-values.sql, src/backend/migrations/005-drop-unnecessary-tables.sql, src/backend/migrations/init/fmtm_base_schema.sql, src/backend/migrations/revert/004-update-default-values.sql
- We had many extra tables and fields we don't use.
- Originally I wasn't sure if we may need them in the future.
- I am more certain that we won't now - deleted.
=> Remove unnecessary tables and field from db schema

.github/workflows/pr_test_frontend.yml, docker-compose.yml, src/frontend/src/api/CreateProjectService.ts, src/frontend/src/components/createnewproject/SplitTasks.tsx, src/frontend/src/store/slices/CreateProjectSlice.ts, src/frontend/src/store/types/ICreateProject.ts, src/frontend/src/utilfunctions/commonUtils.ts
- Currently if there is a failure with of the 4 project creation APIs, the creation will continue, and redirect.
- Instead it should halt creation and display an error to the user.
- I did some refactors here @NSUWAL123 to use a state variables: `generateProjectError` and `generateProjectSuccess`.
- If `generateProjectSuccess` is set to true, then the watcher in `SplitTasks.tsx` will display a success message and do the redirect.
- If `generateProjectError` is set at any stage, then the remaining project creation stages should stop - I didn't get to implement this, could you take a look please?
- It might be a good idea to add the project creation and data extract upload to separate services, for consistency.
- 📖 Read the FMTM Contributing …
=> Prevent project generation if api failure

src/frontend/src/components/SubmissionMap/SubmissionInstanceMap.tsx, src/frontend/src/views/SubmissionDetails.tsx
- Related to #1560 
This PR displays the submission point in case the user uploads their GPS point instead of selecting a feature in submission instance map.
=> fix(frontend): display submission point feature if feature not in extract 

src/backend/tests/conftest.py, src/backend/tests/test_projects_routes.py
Partially closes Issue #1614
This PR covers with tests following endpoints:
- POST projects/{project_id}/entity/status
- GET projects/{project_id}/entity/status
- GET projects/{project_id}/entities/statuses
It verifies that the endpoint correctly returns the entities' mapping statuses by comparing the response data with expected entities data.
To retrieve entities `odk_project` and `entities` fixtures have been created.
`odk_project` extends `project` fixture by generating project files through `project_crud` methods.
- 📖 Read …
=> Test coverage for projects mapping endpoints

src/frontend/src/components/createnewproject/SelectForm.tsx
Update select category description
This PR contains updated description for the `Select Category`.
=> Update Select Category Description

src/frontend/src/components/createnewproject/SelectForm.tsx, src/frontend/src/components/createnewproject/SplitTasks.tsx, src/frontend/src/components/createnewproject/UploadArea.tsx
- Related to #1639 
Currently in the steps `upload area`, `select category`, and `split tasks`, when the previous button is clicked after filling fields respectively, file states are being saved but the dropdowns, radiobuttons state is not saved leading to displaying misleading error messages. 
This PR contain the works to solve this by saving the state of the current step when the previous button is clicked.
Before Changes:
[Screencast from 11-7-24 09:48:44 पूर्वाह्न +0545.webm](https://github.com/hotosm/fmtm/assets/81785002/49f61a26-93d7-4da4-a141-b4037ee202b3)
After Changes:
[Screencast from 11-7-24 09:52:22 पूर्वाह्न +0545.webm](https://github.com/hotosm/fmtm/assets/81785002/0b7d5893-e0c0-4e0b-9df8-45f5b6ad05e6)
Removing the current selected state and files if previous btn was clicked …
=> Save current form step state on previous btn click

src/backend/app/db/postgis_utils.py, src/backend/app/projects/project_routes.py
- Issue #1640
This PR addresses issue of not supporting multipolygons to upload as a project aoi.
**Updates:**
- when multipolygons are uploaded as an aoi, those polygons gets dissolved to create a single aoi
- if we want to split task without dissolving those polygons we can pass dissolve_polygon = False since task-splitter can splits those separate polygons
- we can ask for a param (`dissolve_polygons = True/False`)from user if they want to dissolve those polygons while splitting it (not implemented yet)
Provided in the mentioned issue. …
=> Allow multipolygons to choose as task area

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/pdm.lock, src/backend/pyproject.toml, src/frontend/src/components/createnewproject/SplitTasks.tsx
- Issue  #1641
This PR now avoids creating tasks with no features in them when the AOI is split using the split_by_square algorithm.
Data extracts are now passed to the logic in order to check if a task has any features in it or not. In case a task does not have any features inside it, it won't be appended to the list of tasks generated by the algorithm.
AOI and data extracts used:
Before:
After:
This PR depends on the release of fmtm-splitter.
- 👷‍♀️ Create small PRs. In most cases, this will be …
=> Update split-by-square to avoid creating tasks with no features in it

src/backend/tests/conftest.py, src/backend/tests/test_organisation_routes.py
Related to Issue #1613
Added a test to get a list of all organisations from `GET /organisation/` endpoint.
Enhance with edge cases testing.
=> Test coverage for GET /organisation/ endpoint

src/frontend/src/views/ManageProject.tsx
The `USERS` tab containing `assign user` and `invite user` on `manage project` page is currently static leading to confusion among users.
This PR hides the USERS tab until API integration is done.
=> fix(manageProject): hide user tab until its api integration

src/backend/tests/test_central_routes.py
Added a test to get a list of all XLSForms available in FMTM through `GET /central/list-forms` endpoint.
=> Test coverage for GET /central/list-forms endpoint

src/backend/tests/conftest.py, src/backend/tests/test_projects_routes.py
Added a test for splitting a task into subtasks with POST /projects/task-split endpoint.
Organisation fixture have been refactored to avoid duplication.
=> Test coverage for POST projects/task-split endpoint

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py
- Issue #1705 
There was an issue due to latest upgrade in dependency resulted in db session expiry something related to sqlalchemy/async.
This PR updates `generate_project_data`  passing `project_id` instead of passing `DbProject` object to background task which fixed the issue.
- 📗 Update any related documentation and include …
=> Fix generating project files passing project id to background task

src/backend/tests/test_projects_routes.py
This pull request adds a failure test case for the POST /projects/create endpoint. The test verifies that the endpoint correctly handles attempts to create a duplicate project by returning an appropriate error response.
=> Test add failure test case for create project endpoint

src/frontend/src/components/createnewproject/UploadArea.tsx
- Related to #1707
This PR allows the user to reset the polygon (geojson file) on the draw selection without switching back to `upload file` and resetting the file over there.
[Screencast from 29-7-24 03:48:07 अपराह्न +0545.webm](https://github.com/user-attachments/assets/3537b636-4993-4cda-97db-d03417b2720a)
=> Allow reset polygon on draw selection even if geojson file upload

src/frontend/src/components/ProjectSubmissions/TaskSubmissionsMap.tsx, src/frontend/src/models/task/taskModel.ts
- Related to #1715
This PR fix submission map choropleth not reflecting based on the legend submission value range.
=> Fix submission map chloropeth

src/backend/app/central/central_crud.py, src/backend/app/central/central_deps.py, src/backend/app/db/postgis_utils.py, src/backend/app/helpers/helper_routes.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_schemas.py, src/backend/pdm.lock, src/backend/pyproject.toml, src/backend/tests/test_projects_routes.py
- Issue #1588 
This PR now allows to create entities via single api call without needing entity form creation.
- refactored `generate_project_files` shifting odk_contents to `generate_odk_central_project_content`
- created Data Class for the Fields in `project_schemas` required for entities
- removed `entity_creation_form`
- created functions to create dataset , its properties(fields), bulk create entities via api calls in osm-fieldwork
- dependent to release of o`sm-fieldwork`
N/A
- 👷‍♀️ Create small …
=> Updated generate_project_files to bulk upload entities

src/backend/tests/conftest.py, src/backend/tests/test_projects_routes.py
This PR implements various tests and enhancements for GeoJSON configurations during project creation:
Added tests for different GeoJSON types during project creation
- Ensured support for `Polygon` and `MultiPolygon`, both as standalone and within `Feature` or `FeatureCollection`
- Added error responses for unsupported GeoJSON types: `LineString`, `MultiLineString`, `Point`, `MultiPoint`
- Included tests for rejecting unsupported CRS in GeoJSON
Refactored project creation tests
- Extracted sample project data to a fixture for reusability
Will cover separately:
- GeometryCollection type for GeoJSON
- Hashtags …
=> Add tests for various GeoJSON configurations and CRS validation

src/frontend/src/components/ProjectSubmissions/UpdateReviewStatusModal.tsx
- Related to #1720
This PR contains works to remove the display of error if review status is not chosen and update btn is clicked & disable update btn is not review status chosen.
=> Remove error msg on review status and disable update btn until review status is chosen

src/backend/app/projects/project_schemas.py, src/backend/tests/test_projects_routes.py
We accept a string input for hashtags, with some parsing to ensure they are always in hashtag format.
For example:
- `tag1, tag2, tag3`
- `tag1 tag2  tag3`
- `tag1   tag2    tag3`
- `tag1, tag2 tag3    tag4`
- `TAG1, tag2 TAG3`
Any other random assortment the user could provide!
In the end, the project details response should return an array of hashtags:
- `['#tag1', '#tag2', '#tag3']`
This PR tests hashtag parsing with various edge cases. Adjusts expected outputs in tests to reflect correct hashtag processing. …
=> Hashtag parsing tests for various inputs

src/backend/app/db/postgis_utils.py
There was an issue loading multiple conflict geometries having same `id` field in geojson.
This PR updates the conflation removing `id` from the geojson of conflated features.
=> Remove id from the conflated geojson

src/frontend/src/api/CreateProjectService.ts, src/frontend/src/api/HomeService.ts, src/frontend/src/api/Login.ts, src/frontend/src/api/OrganisationService.ts, src/frontend/src/api/Project.ts, src/frontend/src/api/ProjectTaskStatus.ts, src/frontend/src/api/Submission.ts, src/frontend/src/api/SubmissionService.ts, src/frontend/src/components/ProjectDetailsV2/ProjectOptions.tsx, src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx, src/frontend/src/components/common/Dropdown.tsx, src/frontend/src/store/types/ISubmissions.ts, src/frontend/src/views/ProjectDetailsV2.tsx, src/frontend/src/views/ProjectSubmissions.tsx, src/frontend/src/views/Submissions.tsx, src/frontend/src/views/Tasks.tsx
- Related to #1543
This PR contains works to add remaining TS types on services (API folder).
=> TS types add to services

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py
- issue : #1749 
This PR refactors an existing function to get project users to get the correct username of contributors instead of returning the username of logged-in users.
- refactored to use single sql to avoid multiple db calls.
=> Refactor correct username of contributors 

src/backend/app/central/central_crud.py
Fixes https://github.com/hotosm/fmtm/issues/1667
- The file extension type was not passed through to `pyxform` and `.xls` was hardcoded.
- Fixed to support `.xlsx` too.
Test uploading an xlsx file.
=> [HOTFIX] fix pyxform usage only allowing xls file extension

src/frontend/src/components/createnewproject/DataExtract.tsx, src/frontend/src/components/createnewproject/SplitTasks.tsx, src/frontend/src/store/slices/CreateProjectSlice.ts, src/frontend/src/store/types/ICreateProject.ts
- Related to #1754
This PR removes validation of lineString that checks if lineString is present in the geojson which solves the issue #1754. 
Now, since tasks split is possible without requiring lineString or multiLineString to be present on the geojson.
=> fix(createProject): lineString validation remove

src/backend/app/central/central_crud.py, src/backend/app/central/central_schemas.py, src/frontend/src/views/ProjectSubmissions.tsx
- Issue #1730 
- Issue #1711 
For newly created entity of geopoint of feature , there won't be `task_id` and `osm_id` in entity properties resulted into validation error.
This PR now allows the empty `task_id` and `osm_id` for new entity created when user locate new geopoint for a feature in field. It is dependent to `osm-fieldwork` where xls file is updated to allow to create new entity for the gps point of new feature recorded.
N/A
- Use the xlsx form updated in `osm-fieldwork`
- create submission recording geopoint for new feature
- check the entity status and submission count …
=> Allow empty task id and osm id for new geopoint

src/backend/app/auth/roles.py, src/backend/app/organisations/organisation_crud.py, src/backend/migrations/005-rename-public-beta.sql, src/backend/pdm.lock, src/backend/pyproject.toml, src/backend/tests/conftest.py, src/frontend/e2e/01-create-new-project.spec.ts
Fixes #1759
- Includes a migration to rename org name, slug, and description.
- Updates all references to public beta org --> hotosm
- Also includes an update to osm-fieldwork --> 0.16.1 with latest XLSForm updates.
- Test creating a project with the new org name.
- Test the org is displayed correctly for existing projects.
=> Rename public beta org  to `hotosm`

src/backend/app/central/central_crud.py, src/backend/pdm.lock, src/backend/pyproject.toml
Related to #1667
- `.xlsx` was working fine, but `.xls` caused and error for some reason.
- Upgraded `pyxform` to latest, which has a much simpler `convert` function for XLSForm --> XForm.
- It attempts to parse XLSX and XLS in order, so we no longer need to pass through the form type.
- Upgrading also fixed the issue using `.xls`.
=> Upgrade pyxform and fix xls extension usage

src/frontend/src/components/createnewproject/ProjectDetailsForm.tsx
- Related to #1739
Add description text about TMS URL on create project first step.
=> feat(projectDetailsForm): tms url description text add

src/backend/app/central/central_crud.py, src/backend/app/central/central_deps.py, src/backend/app/helpers/helper_routes.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/pdm.lock, src/backend/pyproject.toml, src/frontend/src/api/CreateProjectService.ts, src/frontend/src/components/ManageProject/EditTab/FormUpdateTab.tsx, src/frontend/src/components/ProjectDetailsV2/FeatureSelectionPopup.tsx
Fixes https://github.com/hotosm/fmtm/issues/1722
- PR https://github.com/hotosm/fmtm/pull/1763 added the osm-fieldwork update_xlsform work to the `validate-form` endpoint.
- This PR also adds the functionality during the project creation.
- Users can upload a custom form full of question and have the required FMTM fields injected automatically.
- Removes the custom XML manipulation that was difficult to understand / maintain, replaced with much easier Pandas-based XLSForm concatenation.
- Rebuild the docker image
- Run the API
- Create a new project using a custom form
- Also test using the default / bundled forms
- …
=> Use XLSForm injection during project creation

src/backend/app/submissions/submission_routes.py, src/frontend/src/views/SubmissionDetails.tsx
- Issue: #1701 
This PR creates a new endpoint that retrieves the submission photos using the `submission_id (instance_id)` of the particular submission. This endpoint can be used in submission detail page to visualize the submission images for example user uploaded images in verification section (`digitisation_form`).
- endpoint example : `https://api.dev.fmtm.hotosm.org/submission/get-submission-photo?submission_id=uuid%3A55cd4d36-8cbc-47e0-b48d-d0846e268c21`
```
{
"s3_path": "http://s3.fmtm.localhost:7050/fmtm-data/1/24/uuid:55cd4d36-8cbc-47e0-b48d-d0846e268c21/1.jpeg"
}
``` …
=> Retrieve submission photo using its submission id in submission detail page

src/backend/app/central/central_crud.py, src/backend/app/central/central_schemas.py, src/backend/app/db/postgis_utils.py, src/backend/app/helpers/helper_routes.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py, src/backend/tests/test_projects_routes.py, src/frontend/e2e/02-mapper-flow.spec.ts, src/frontend/e2e/helpers.ts, src/frontend/src/api/Project.ts
Related to https://github.com/hotosm/fmtm/issues/1653
- Adds an endpoint: `/projects/{project_id}/additional-entity`
- The endpoint takes a single GeoJSON file for param `geojson`.
- The filename is used as the Entity list name, so ensure the user knows this.
- The endpoint should be called after task areas are created, but before the `/generate-project-files` endpoint is called during project creation.
- It can be called as many times as needed for the number of additional Entity lists required.
An example GeoJSON in Kathmandu to test with:
[roads.geojson.txt](https://github.com/user-attachments/files/17085533/roads.geojson.txt) …
=> Add endpoint to create additional Entity lists on a project

src/backend/app/auth/auth_routes.py, src/backend/app/central/central_crud.py, src/backend/app/central/central_routes.py, src/backend/app/db/db_models.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_deps.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py, src/backend/app/submissions/submission_crud.py, src/backend/app/submissions/submission_routes.py, src/backend/app/tasks/task_deps.py, src/backend/migrations/007-remove-xform-table.sql, src/backend/migrations/init/fmtm_base_schema.sql, src/backend/pdm.lock, src/backend/pyproject.toml
- Simplified logic during project creation.
- Added migration to remove `xforms` table, replacing with `projects.odk_form_id` an `projects.xlsform_content`.
- Previously I thought we might have multiple xlsforms per project, but it's become clear that this is not actually desirable. Instead we just want to map multiple features via the same form; functionality we have almost finished adding.
- I also removed all remaining XML manipulation, in favour of the new Pandas XLSX editing we have added in osm-fieldwork. I could remove the `defusedxml` dependency too.
- 👷‍♀️ Create small PRs. In most cases, this will be …
=> Remove xforms table from database, refactor project creation

src/backend/app/central/central_crud.py, src/backend/app/projects/project_routes.py, src/backend/pdm.lock, src/backend/pyproject.toml, src/frontend/src/components/DialogTaskActions.tsx, src/frontend/src/views/SubmissionDetails.tsx
- Simplify logic for digitisation and mandatory fields XLSForms based on field feedback.
- Remove the task_id and task_filter fields to simplify logic.
- They make it slightly easier to select a geometry by filtering down the available options, at the expense of complicating many things.
- Ideally the user just selects a geom via intent and doesn't even need to open the map anyway.
=> Remove task_id and task_filter params from XLSForm

src/backend/Dockerfile
N/A
This PR refactors the Dockerfile to avoid warning raised such as:
```
FROM docker.io/python:${PYTHON_IMG_TAG}-slim-bookworm as base
The 'as' keyword should match the case of the 'from' keyword
```
=> Fix dockerfile warning such as Casing and whitespace separator

src/backend/Dockerfile, src/backend/pdm.lock, src/backend/pyproject.toml
Required in https://github.com/hotosm/fmtm/pull/1822
Also bumps osm-rawdata and fmtm-splitter for minor fixes.
=> Update osm-fieldwork --> 0.16.9 for new entity creation fix

src/backend/app/central/central_crud.py, src/backend/app/central/central_schemas.py, src/backend/app/projects/project_crud.py
Whenever new geopoint is introduced it won't have task_id since we don't have task_id filter any more so there won't be task id for new feature which resulted into validation error in entity statuses endpoint.
- related issue #1711 
Unrelated to entity statuses , I encountered an issue in `preview_split_by_square` where aoi is changed when single polygon is uploaded.
Actual AOI:
After merge_polygons:
This PR updates the schema `EntityTaskID` and `EntityOsmID` in order to allow empty `task_id` and `osm_id` which likely occurs if new feature geopoint is introduced in submissions. This PR also updates the function `preview_split_by_square` where the length of polygon is checked before in order to apply `merge_polygons` only for multipolygon aoi.
This PR depends on the new release of …
=> Allow empty task id in entity statuses for new geopoint

src/backend/app/db/models.py, src/backend/app/submissions/submission_crud.py, src/backend/app/submissions/submission_routes.py, src/frontend/src/api/CreateProjectService.ts
Issues:-
- #1701 
- # 1837
This PR updates the missing parameter "db" for the background task to upload submission in s3 and the command to execute batch insertion of submission photos in db. It also fixes the get API of submission photos using `submission_id` making db `id` `Optional`. There is a slight change in the payload for the task split by square from `dimension` to `dimension_meters` which fixes the issue of splitting by square.
```
{
"image_urls": [
"http://s3.fmtm.localhost:7050/fmtm-data/1/2/uuid:7d485b1b-7b2c-4bf0-afcf-d5e0ab585070/1.jpeg"
]
}
```
- 📖 Read the HOT …
=> Fix s3 upload and db insertion for submission photos

src/backend/app/central/central_crud.py, src/backend/app/central/central_schemas.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py
- Issue #1800 
There were issues with custom additional entities `geojson` properties which weren't supported by odk-central failing the creation of entities and dataset properties. Some keywords of `odk-central` such as `uuid`, name, label are not supported by `odk-central` to avoid duplicate entries.
This PR fixes the mentioned issue where valid properties are prepared from the uploaded additional entity `geojson`.
**changes**
- Custom properties are filtered in one step to include only valid, sanitized properties free of reserved keywords. Invalid properties (having invalid characters such as ":") are excluded to prevent API errors.
- Any default property missing from the custom list is appended to ensure dataset requirements for fmtm in ODK Central.
N/A
Did you attempt any other …
=> Fix(additional-entity) allow custom properties to create entities list

src/backend/app/db/models.py, src/backend/app/users/user_routes.py, src/backend/migrations/010-delete-user.sql
Fixes #1661 
On user deletion, task history will retain username from user
and rest of the user data will be deleted.
=> feat: allow user deletion without deleting task references

src/frontend/vite.config.ts
- The caching from the PWA on the manager frontend prevents loading the `/mapnow/ID/` URLs for the mapper frontend.
- We don't actually need a PWA for the manager frontend anymore - this will eventually be transferred to the mapper frontend only.
- To facilitate this I added configure to create a dummy service worker that's purpose is to unregister the old service worker.
- Users that visit FMTM will have the PWA service worker removed, so they can correctly load the mapper frontend.
- Later on, the PWA can be removed entirely (once this is pushed through to prod and most users have unregistered the old service worker / or had it expire).
@manjitapandey hopefully the fix for your demo tomorrow 👍  …
=> Replace pwa in manager frontend with dummy service worker (prep for removal)

src/backend/app/projects/project_routes.py, src/frontend/src/api/CreateProjectService.ts
- Issue #1864
This PR fixes the mentioned issue. 
**changes**
- Changed `Insert` command to `Update` command to update the form of the existing project
- Added new field `author_id` (`NOT NULL` constraints)
- Changed return response from project data to simple success message
- Update response in Frontend
N/A
- 📗 Update any related documentation and include any …
=> Fix update project xlsform SQL after backend refactor

src/mapper/src/lib/components/dialog-task-actions.svelte, src/mapper/src/routes/[projectId]/+page.svelte, src/mapper/static/assets/icons/new-window.svg
- Related to #1764
This PR adds `Add New Feature` that opens ODK with no features selected.
=> Mapper Frontend: Map new feature in odk btn

src/backend/app/config.py, src/backend/app/projects/project_routes.py
- I didn't realise we didn't have roles set on some project endpoints.
- This PR ensures login is required for all endpoints, to prevent spamming of the API by scrapers etc.
- I also ordered the large `projects_routes` file into sections, for `mapper`, `manager`, and `org admin` roles.
- Also adds a fix for the `fmtm.dev.test` domain in the updated CORS orgins logic: allows Playwright tests to succeed & deployment to happen.
- 📗 Update …
=> Update permissions for backend project routes

src/backend/app/auth/auth_routes.py, src/backend/app/auth/osm.py, src/backend/app/auth/roles.py, src/backend/app/central/central_crud.py, src/backend/app/central/central_routes.py, src/backend/app/projects/project_crud.py, src/backend/app/s3.py
Resolves #1756 
Replaced log.error with log.exception and included traceback information where exceptions are raised.
=> refactor(logging): enhance error logging with stack information across multiple modules

src/backend/app/auth/auth_routes.py, src/frontend/.gitignore, src/frontend/e2e/01-create-new-project.spec.ts, src/frontend/e2e/02-mapper-flow.spec.ts, src/frontend/e2e/auth.setup.ts, src/frontend/e2e/helpers.ts, src/frontend/playwright.config.ts, src/frontend/src/routes.jsx, src/frontend/src/views/PlaywrightTempLogin.tsx
#1903 as the PR where this issue was discussed
- Didn't get a chance to finish this due to my flight, but hopefully you get the idea here @NSUWAL123 
- If I don't get to look at this until Monday, we could go over it together in person 😄
- The context should probably be set just after the OSM login succeeds, then waiting for the redirect will allow the cookie to be set for the subsequent test. 
- The context wont save the cookie as it's httpOnly, but should save the OSM login part hopefully, to avoid having to do the Oauth flow for OSM again - let's see!
- In the end the main goal is automated OSM login. To do that we need to make a test OSM account and can just hardcode the creds to this repo. If we optimise by reducing calls to OSM via the auth context, this is a bonus, but not …
=> Persist osm login across playwright tests (temp login removed)

src/frontend/src/api/CreateProjectService.ts
- Issue: #1897 
This PR fixes the parsing of  `null` value of additional entities as a string in `form-data` when no additional entities are uploaded. It updates the body of generate-project-data by parsing null as a JSON instead of form data.
N/A
=> Fix null value of additional entity when no additional entities are uploaded

src/backend/tests/.pyodk_config.toml, src/backend/tests/conftest.py, src/backend/tests/test_submission_routes.py
Example: Resolves #1913
A fixture for submission has been created and some tests have been added for submission routes.
=> Add tests for submission routes

src/backend/app/tasks/task_routes.py, src/frontend/src/views/ProjectSubmissions.tsx
- Issue: #1923
```python
{
"errors": [
{
"loc": [
"path",
"task_id"
],
"msg": "Input should be a valid integer, unable to parse string as an integer",
"error": "Input should be a valid integer, unable to parse string as an integer['path', 'task_id']"
}
]
}
```
This PR resolves a routing issue in the `/tasks/activity` endpoint. A trailing slash (/) was added to the endpoint definition to ensure unambiguous route matching.
Previously, the `/tasks/activity` route conflicted with the dynamic route` /tasks/{task_id}`, causing the framework to misinterpret activity as a task_id, resulting in validation errors.
N/A …
=> Resolve route ambiguity for /tasks/activity endpoint

src/frontend/src/api/CreateProjectService.ts
If multiple additional entities are uploaded only the first filename of additional entities is edited to remove space with '_'. This feature is yet to be implemented in UI to allow the uploading of multiple additional entities. Only a single file can be uploaded as an additional entity.
This PR updates the frontend code to update the filename for multiple additional entities. Some changes have been made to refactor some repeated code and fix the issue of not passing additional entities list when no custom form is uploaded. If `additional_entities` or custom form is uploaded then it passes payload as a multipart/form-data content type else JSON body.
N/A
- 📖 Read the FMTM …
=> Edit multi additional entities names replacing space with '_'

src/backend/app/organisations/organisation_deps.py, src/backend/app/organisations/organisation_schemas.py
- Issue #1944 
This PR updates the `parse_organisation_input` passing odk credentials directly without calling `OdkCentralIn`. Calling OdkCentralIn will encrypt password which is called again in the `OrganisationUpdate` (schema) pydantic model.
N/A
=> Avoid double encryption of odk creds while creating organisation

src/frontend/src/api/Project.ts, src/frontend/src/api/Submission.ts, src/frontend/src/components/ProjectDetailsV2/ProjectInfo.tsx, src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx, src/frontend/src/components/createnewproject/UploadArea.tsx, src/frontend/src/models/project/projectModel.ts, src/frontend/src/views/CreateNewProject.tsx
- Related to #1954
- Fix showing of previously rendered submission geometries on the submission instance page
- Create project: fix uploaded, drawn, splitted, dataExtract geojson state being persisted even if geojson file being reset
This PR contains following works: 
- Fix task undefined issue on project instact page updating task_id accessor key
- Fix previously fetched submission geometries appearing to submission instance page
- Create project geojson state fix
=> Fix: Submission Instance Page, Create Project

src/backend/app/db/postgis_utils.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py
- Issue:  #1904 
This PR updates the postgis utils to clean the polygon geojson before any operations such as split by square , split by algorithm, create project outline, generate data extracts. It includes:
- `remove_holes`: It checks for any holes present in the polygon and removes it using exterior ring
- `ensure_right_hand_rule`: It ensures each polygon follows right hand rule
- `create_single_polygon`: It creates a single polygon, mostly a project outline case, while creating projects or generating data extracts. Here, if the geojson has disjoint multipolygons, then it applies a convex hull to create a single AOI, or else it will use an exterior ring to create a single AOI. During data extracts, it won't apply convex hull; we will get data extracts in individual polygons inside …
=> Clean polygon geometries; remove holes, fix right hand rule

src/backend/app/auth/auth_routes.py, src/backend/app/auth/osm.py, src/backend/app/config.py, src/backend/app/helpers/helper_routes.py
- Related to: #1911 
- created two seperate refresh endpoint for management and mapper frontends.
- enforced osm login only for management
- preferred osm login for mapper but also allowed temp login
=> Feat/OSM login enforced for management, additional temp login option for mappers

src/backend/app/projects/project_routes.py
- Unable to generate data extract when user draws AOI instead of uploading geojson
When AOI is drawn manually, it passes geojson as:
```json
{'type': 'Feature', 'geometry': {'type': 'Polygon', 'coordinates': [[[85.32623169895389, 27.708784900093008], [85.32627350543834, 27.706972399316967], [85.32879582999944, 27.7056900676549], [85.33067712179916, 27.707860158561616], [85.3296319596882, 27.70986992016195], [85.32766705491962, 27.710054865688036], [85.32623169895389, 27.708784900093008]]]}, 'properties': None}
```
It is fixed by simply parsing geojson to `FeatureCollection`.
N/A …
=> Parse AOI geojson to featcol in generate data extract

src/mapper/src/lib/components/header.svelte
- Added a small prompt on first load to show the user where to download custom ODK Collect:
- This is done via tooltip and a svelte snippet.
- It is linked to the localStorage status where we show the QR Code tab by default too.
=> Prompt user to download custom ODK Collect on first load

src/mapper/src/lib/components/offline/basemaps.svelte, src/mapper/src/lib/utils/basemaps.ts
- Related to #1940
- Fix offline mode button visibility on specific browsers
- Fix basemap component TS type
=> Fix: Offline mode button visibility & Basemap component TS type error

src/backend/app/db/models.py
- Related to: #1976 
Added a field "organisation_name" to minimal project api for mapper frontend
=> fix/Include organisation name in mapper frontend's project api

src/mapper/src/lib/components/more/index.svelte, src/mapper/src/lib/components/more/project-info.svelte, src/mapper/src/styles/page.css
- Related to #1976
- Add project information section to mapper frontend more -> bottom sheet
=> Project details section add to mapper frontend bottom sheet

src/backend/pyproject.toml, src/backend/uv.lock
- Issue: #1960 
Changes have been made to the fmtm splitter to merge the smaller tasks generated by square splitting. Smaller tasks are determined if their area is less than 35% of the perfect square task. Their closet neighbouring tasks who share a greater boundary to smaller tasks are considered while merging.
N/A
=> Update the version of fmtm-splitter 2.0.0

src/mapper/src/lib/components/dialog-task-actions.svelte, src/mapper/src/lib/components/map/main.svelte, src/mapper/src/lib/components/more/activities.svelte, src/mapper/src/lib/components/more/comment.svelte, src/mapper/src/routes/[projectId]/+page.svelte, src/mapper/src/store/tasks.svelte.ts
- Related to #1982
- Mapper Frontend: Replace usage of task ID with task index on UI
=> Replace project id with index on mapper frontend 

src/backend/app/central/central_schemas.py, src/backend/app/db/postgis_utils.py, src/backend/app/projects/project_crud.py
- Issue: #1946
- new property submission_ids is added to dataset and entity properties in order to link each submissions with their respective entity.
response of `entity/status` endpoint:
```json
{
"id": "8b3508c8-5ac5-4983-8e4a-d67c6ab51eb9",
"task_id": 3,
"osm_id": 954555442,
"status": 2,
"submission_id": "uuid:5db29b57-c104-4b74-a49d-a4ad042bc015,uuid:1cdf791b-285b-4bca-8c89-578d7cf71e48, uuid:f3c8a289-4bbc-4671-a780-c0111b374e7c",
"updated_at": "2024-12-19T08:26:45.065Z"
}
```
- 👷‍♀️ Create small …
=> Add submission ids as a dataset property for the entities

.github/workflows/build_and_deploy.yml, docs/manuals/field-mapping-examples.md
- Build failed due to versioning issue of golang/crypto in minio tag
Turn off scan image for temporary fix and build development changes.
N/A
=> Pass scan_image as false for temporary fix of minio tag

.github/workflows/build_and_deploy.yml
=> fix: compose file name for backend test stage

src/backend/app/projects/project_schemas.py
- Related to: #1950 
changed a field in pydantic model of project summary from description to short_description
=> Rename 'description' to 'short_description' in ProjectSummary model

src/frontend/e2e/01-create-new-project.spec.ts, src/frontend/src/components/createnewproject/DataExtract.tsx, src/frontend/src/components/createnewproject/Description.tsx, src/frontend/src/components/createnewproject/SelectForm.tsx, src/frontend/src/components/createnewproject/SplitTasks.tsx, src/frontend/src/components/createnewproject/UploadArea.tsx
- Related to #1950
- Related to #1964
- Update project creation step 2 description
- Show reset button after AOI is drawn
- Upload a Geojson --> Upload
- Shift additional feature count from Split tasks to Map data
- Other terminologies update
=> Update manager workflows terminologies

docs/manuals/field-mapping-examples.md, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/tests/test_projects_routes.py
- Resolves: #1573 
Refactored add manager endpoint to only allow organisation admins to assign managers
added code to send osm message and email to the new manager upon assignment
Verify project url would work on production.
=> Send notification message to new project manager upon assignment and refactor assignment code

src/backend/app/auth/providers/osm.py, src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py
- Related to: #1199
Added an endpoint that will take a project id and username, check if an osm user with such username exists and then sends them an invite with a link to the project.
=> Implement user invitation functionality for projects via OSM messages

src/mapper/src/lib/components/map/main.svelte, src/mapper/src/routes/[projectId]/+page.svelte
- Related to #1980
Addition of latest task activity on mobile screens too + minor style change
=> Latest task event container minor style change + Addition of latest task event on mobile screen

src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py
- Added extra option to tile source of BasemapGenerate pydantic model.
- Added tms basemap generation during project data generation if tms url was present during project creation.
=> Auto basemap generation if tms url is input during project creation

src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx
- Related to #1928
- Reorder SubmissionTable component imports
- Refine Submission columns (decided to show important columns and columns related to `survey_questions` group)
=> Refine submission table

src/mapper/src/lib/components/dialog-entities-actions.svelte, src/mapper/src/lib/components/map/geolocation.svelte
- Related to #1888
- When navigation mode is enabled, fetch directions API in every 10 seconds rather than fetching on every user geolocation coordinate change (as geolocation coordinates change in every milliseconds)
N/A
=> Mapper Navigation: Limit routing API call 

src/frontend/src/components/GenerateBasemap.tsx, src/frontend/src/environment.ts
- Related to #2025
- Update tile source option value: `tms` --> `custom`
N/A
=> fix(generateBasemap): update tile source option value

src/backend/app/db/enums.py, src/backend/app/db/models.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py, src/backend/migrations/002-create-geometry-log.sql, src/backend/migrations/init/fmtm_base_schema.sql, src/backend/migrations/revert/002-create-geometry-log.sql
- Issue: #1986 
This PR creates a table to store geometry with status 'BAD' or 'NEW'.
```json
{
"geom": {
"type": "Polygon",
"coordinates": [
[
[
85.333952,
27.699157
],
[
85.333892,
27.699038
],
[
85.33404,
27.699001
],
[
85.334109,
27.699095
],
[
85.333952,
27.699157
]
]
]
},
"status": "NEW",
"project_id": 3,
"task_id": 1
}
```
`/projects/{project_id}/geometries`
- 📗 …
=> create a table to store bad and new geoms

src/backend/app/db/models.py, src/backend/app/projects/project_routes.py, src/backend/migrations/003-jsonb-geom-geometry-log.sql, src/backend/migrations/init/fmtm_base_schema.sql, src/backend/migrations/revert/003-jsonb-geom-geometry-log.sql
- Issue:  #1986
This PR updates the existing table geometry log to have geometry field as jsonb type and id as UUID type. It is required as pglite doesn't support postgis; it may be in the near future. Now, using electric sql we can retrive geom as geojson without any functional support.
N/A
=> Update geom type to jsonb, int id to uuid in geometrylog table

src/backend/app/db/enums.py, src/backend/app/db/models.py, src/backend/app/organisations/organisation_crud.py, src/backend/app/organisations/organisation_schemas.py, src/backend/migrations/002-create-geometry-log.sql, src/backend/migrations/003-jsonb-geom-geometry-log.sql, src/backend/migrations/004-project-extra-fields.sql, src/backend/migrations/init/fmtm_base_schema.sql, src/backend/migrations/revert/004-project-extra-fields.sql
https://github.com/hotosm/fmtm/issues/2066
https://github.com/hotosm/fmtm/issues/1979
https://github.com/hotosm/fmtm/issues/1985
- Tweaks the idempotence of some previous migrations.
- Added extra fields:
- organisation.associated_email
- project.geo_restrict_distance_meters (default 50) and geo_restrict_force_error (default false)
- project.new_geom_type with enum options 'POINT', 'POLYGON', 'LINESTRING'
- Also added these fields to the backend API models: the are returned in responses + allowed during creation POST.
- 👷‍♀️ Create small PRs. In most cases, this will be …
=> Update migration idempotence, add org email field, extra project fields

scripts/1-environment/gen-env.sh
enables running gen-env.sh on MacOS
None
Converts random bytes from /dev/urandom to base64 to avoid passing non-ascii characters to tr and avoiding this error being thrown by tr `tr: Illegal byte sequence`
I considered looking for a native uuid or crypto library that could generate random characters, but I think the way proposed most directly fixes the issue.
Follow instructions here: https://docs.fmtm.dev/INSTALL/#2-create-an-env-file
If you are on MacOS, this will test if the bug is fixed.
If you are on Linux, this will test to make sure we don't introduce a regression.
If you already have a .env file created, you'll have to rename it while you test this PR. …
=> fixed running gen-env.sh on MacOS

src/backend/app/central/central_crud.py, src/backend/app/projects/project_routes.py, src/backend/pyproject.toml, src/frontend/src/components/createnewproject/SplitTasks.tsx, src/frontend/src/models/project/projectModel.ts, src/frontend/src/store/types/ICreateProject.ts, src/frontend/src/types/enums.ts, src/mapper/package.json, src/mapper/pnpm-lock.yaml, src/mapper/src/constants/enums.ts, src/mapper/src/lib/components/map/main.svelte, src/mapper/src/lib/odk/javarosa.ts, src/mapper/src/lib/types.ts, src/mapper/src/routes/[projectId]/+page.svelte
Related to #1979
- We should be able to collect new polygon and linestring geoms with this update.
- By default all new projects are type 'polygon' / 'geoshape'.
- The type of geometry to draw needs to be configured at project creation.
- Setting the `new_geom_type` param will also modify the XLSForm as needed to the correct geometry type.
Future todo:
- They seem to complete on the third vertice being drawn.
- It's possible to draw more by holding the click, dragging the map slightly, then releasing the click.
- Probably some conflict with the default MapLibre click handler?
- Note that I didn't add any extra toolbar buttons to the map. It's not possible to edit verticies, as this is probably done on a phone and that would be too fiddly. The user will just have to create a new geom if …
=> Add capability to draw new polygon and linestring geoms

src/backend/app/db/models.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py
- Following issue: #2011 and #1986
New get api to retrieve all the geometry logs stored for bad and new geom.
Endpoint: `GET /project/{project_id}/geometry/records`
```json
[
{
"status": "NEW",
"geojson": {
"type": "Feature",
"geometry": {
"type": "Polygon",
"coordinates": [
[
[
85.318679,
27.702891
],
[
85.31865,
27.70259
],
[
85.318824,
27.70256
],
[
85.318853,
27.702873
],
[
85.318679,
27.702891
]
]
]
},
"properties": {}
},
"project_id": 7,
"task_id": null
},
{
"status": "NEW",
"geojson": {
"type": "Feature",
"geometry": {
"type": "Polygon",
"coordinates": [
[
[
83.982313,
28.233884
],
[
83.982358,
28.233839
],
[
83.98244,
28.233964
],
[
83.98239,
28.233994
],
[
83.982313,
28.233884
]
]
]
},
"properties": {
"instance_id": "8sveg3348gjlafbrk54ohag5han8"
}
},
"project_id": 7,
"task_id": …
```
=> Create get api for project's geometry log

src/mapper/src/routes/[projectId]/+page.svelte
- Related to #1975
Remove unnecessary/irrelevant `subscribeToEntityStatusUpdates` call potentially causing electric SQL to update entity status.
N/A
=> Fix entity status color vanish

src/backend/app/submissions/submission_routes.py
Related to: #2036 
Fixes the review state filter when received is applied.
This happened because odk filter does not have `received` review state
=> fix review state for received on submission table

src/backend/app/db/models.py
- There was an issue while deleting projects that have photos in the submissions, throwing an error of foreignkey constraint, as we do have a separate table to store image urls linking with projects. 
This PR adds a sql to delete submission photos linked to that particular project from table before deleting project.
N/A
- 📗 Update any related documentation and include …
=> Delete submission photos while deleting project to avoid foreign key constraint

src/Dockerfile.ui.debug, src/Dockerfile.ui.prod
I was running into a Segmentation Fault issue when I was trying to run `docker compose up --build ui-mapper`.
Basically just upgrades from Node 20 to Node 23
Screenshot of it working on a MacOS
Tried installing pnpm with `npm install -g pnpm@version` which seemed to help a little but still ran into seg fault issues when running vite.  I think the issue is a fundamental issue with older versions of NodeJS. 
I ran the docker compose command and the application seemed to run.  I haven't done any further testing. …
=> fixed running docker compose up ui-mapper on MacOS by upgrading node version

src/backend/app/auth/auth_deps.py, src/backend/app/db/models.py, src/backend/app/integrations/__init__.py, src/backend/app/integrations/integration_crud.py, src/backend/app/integrations/integration_deps.py, src/backend/app/integrations/integration_routes.py, src/backend/app/main.py, src/backend/app/projects/project_routes.py, src/backend/migrations/005-api-key.sql, src/backend/migrations/init/fmtm_base_schema.sql
Fixes #2109
- Adds the concept of API keys to FMTM, as an alternative access method outside of oauth tokens.
- A minimal number of endpoints should accept API keys.
- For now this is to faciliate https://github.com/hotosm/fmtm/issues/1841, where we POST a new entity status.
- In future, we could use this for external app integrations, such as EveryDoor.
=> Add `integrations` router with API key functionality (external apps)

src/frontend/src/components/createnewproject/ProjectDetailsForm.tsx
- Issue: #2140 
Whenever users select an organisation without any default ODK credentials, they are suggested to provide credentials input. But if they wish to use default ODK credentials, they should be allowed to use the default from HOTOSM. So there was an issue when they checked the box to use default ODK credentials; the custom ODK fields input was still shown.
So I removed the logic tied with the organisation in order to show custom ODK fields; this PR only checks if the user has checked the box or not. Based on that, the custom fields to provide credentials are shown.
I. When no org is selected:
II. When org without default odk creds is selected:
III. When user checks to box to use default creds:
IV. When org with default odk creds is selected:
check box is auto checked
V. When …
=> Allow users to select default odk credentials irrespective of organisation

src/backend/app/central/central_crud.py, src/backend/app/db/enums.py, src/backend/app/tasks/task_crud.py, src/backend/app/tasks/task_routes.py, src/backend/migrations/008-add-taskevent-enumtype.sql, src/backend/migrations/init/fmtm_base_schema.sql
- Related to: #1603 
A new function has been created here that will unlock stale tasks.
There is also an endpoint that will help us test it manually.
Is there a better way to do this without disabling `task_event_state_trigger`?
Is the logic implemented here correct?
=> Auto unlock locked tasks after 3 days

src/backend/app/projects/project_crud.py
- Issue: #2152
There was issue of tiles not being cleared from disk after successfully generating tiles, consequently consuming larger volume. This PR adds a line of code that removes the tile directory from disk `/opt/tiles` after generating it.
N/A
=> Clear tiles from disk after generation

compose.yaml, contrib/basemaps/Dockerfile, contrib/basemaps/README.md, contrib/basemaps/build.sh, deploy/compose.development.yaml, deploy/compose.main.yaml, src/backend/Dockerfile, src/backend/app/projects/project_crud.py
Work for #2157
- Fixes the TMS issues once and for all!
- `go-tilepacks` is much better than basemapper.py at generating mbtiles - so much faster and better at handling different formats.
- I also fixed an issue where the encoding is gzipped from servers: this was a problem for the Tokha TMS server (perhaps relay this info to devops, as it's useful to know! TMS server responses **can** be gzipped, but the receiving software needs to be able to decode the data). In some cases, it might be good to simply remove the gzip encoding from the responses.
- Also includes `go-pmtiles` to do the conversion to pmtile format.
- osm_fieldwork.basemapper.py is no longer used.
- I'm sure this is probably quite CPU and memory intensive - I haven't tested thoroughly.
- It might lock up the worker / thread …
=> Fix TMS issues by using go-tilepacks and go-pmtiles

src/backend/app/submissions/submission_routes.py
- Related to: #2165 
Added date range filter for submission geojson download in api.
=> Add date range filter for geojson download

src/frontend/src/components/DialogTaskActions.tsx, src/frontend/src/components/ProjectDetailsV2/TaskSelectionPopup.tsx
- Related to #1870
- Fix logic of checking actioned by username and logged in username (allow anyone to lock the task if the task is in ready state)
- Update `Locked By` to `Actioned By` since in ready state the `Locked By` term doesn't make sense
=> Fix task lock logic

src/backend/app/projects/project_routes.py
Fast API was assuming the return for the `/{project_id}/form-xml` endpoint was JSON, so it stringified/quoted the xml string like it was a JSON string.
Force Fast API to recognize that the output isn't JSON and doesn't need to be quoted.
Please see this reference page: https://fastapi.tiangolo.com/advanced/custom-response/
And search for "application/xml" on the reference page:
N/A
N/A
Go to http://api.fmtm.localhost:7050/projects/1/form-xml and see that the return doesn't have any `\"` anymore
- ✅ Provide …
=> make sure route /{project_id}/form-xml returns plain xml string

compose.yaml, contrib/tunnel/button/index.html, deploy/compose.development.yaml, src/backend/app/central/central_crud.py, src/backend/app/db/enums.py, src/backend/app/db/postgis_utils.py, src/backend/app/helpers/helper_routes.py, src/backend/app/submissions/submission_routes.py, src/backend/pyproject.toml, src/backend/tests/test_submission_routes.py, src/backend/uv.lock, src/frontend/src/api/Project.ts, src/frontend/src/api/SubmissionService.ts, src/frontend/src/api/task.ts, src/frontend/src/components/DialogTaskActions.tsx, src/frontend/src/components/ProjectDetailsV2/ProjectOptions.tsx, src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx, src/frontend/src/store/slices/ProjectSlice.ts, src/frontend/src/store/slices/SubmissionSlice.ts, src/frontend/src/store/slices/TaskSlice.ts, src/frontend/src/store/types/ISubmissions.ts, src/frontend/src/store/types/ITask.ts, src/frontend/src/utilities/CustomDrawer.tsx, src/frontend/src/utilities/PrimaryAppBar.tsx, src/mapper/src/lib/odk/collect.ts, src/mapper/src/routes/[projectId]/+page.svelte
Related to #2165
- I refactored the submission download endpoint to be a single endpoint, with option `csv`, `json`, or `geojson`.
- When downloading geojson, I also extract the additional geometry fields (that should always end in `_geom` as a Feature in the final FeatureCollection).
- The extra feature is like this:
```json
{"type": "Feature", "id": "65bfe40a-df0f-4f51-9257-e341c9515b87", "geometry": {"type": "Point", "coordinates": [85.302801, 27.712952]}, "properties": {"is_additional_geom": true, "id_field": "kathmandu_point_extract", "geom_field": "kathmandu_point_extract_geom"}}]}
```
- As you can see:
- The "id" field is the entity id.
- The "is_additional_geom": true property is set.
- The "id_field" property is set to the submission json field that contained the ID (where the …
=> Extract additional geometries into submission geojson featurecollection

src/backend/app/users/user_routes.py
- Unable to see the user while assigning a project manager during project creation by the organisation admin.
This PR updates the user role of user list endpoint to Project manager, project manager as in they need to see user list to assign other user as a project admin or lower roles.
@NSUWAL123 
N/A
- 📗 Update any related documentation and include any relevant …
=> Update role to project admin to fetch user list

contrib/tunnel/button/pnpm-lock.yaml, src/backend/uv.lock, src/frontend/pnpm-lock.yaml, src/mapper/pnpm-lock.yaml
Reverts hotosm/fmtm#2202
Turned off renovate lockfile maintenance, else it's going to get annoying.
Lots of packages break SemVer - it can't be relied on entirely that a PATCH upgrade is going to be fine.
=> Revert "chore(deps): lock file maintenance"

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/frontend/src/api/CreateProjectService.ts, src/frontend/src/components/createnewproject/DataExtract.tsx, src/frontend/src/components/createnewproject/SplitTasks.tsx, src/frontend/src/hooks/useForm.tsx, src/frontend/src/store/slices/CreateProjectSlice.ts, src/frontend/src/store/types/ICreateProject.ts
Related to #2184
Also related to #2190, based on @Sujanadh's debugging 🙏 
Referenced in https://github.com/hotosm/fmtm/discussions/1732
A warning is displayed on the dataset upload / OSM fetch page if more than 10,000 features (the demo was set to 500 for testing in the screenshot):
An error is displayed on the dataset upload / OSM fetch page if more than 30,000 features (the demo was set to 500 for testing in the screenshot). The user is blocked from continuing:
During project creation, if there are more than 10,000 features, then the user receives a different prompt and the redirect takes 20 seconds to complete:
- …
=> Add project feature warning (10,000) and limit (30,000)

compose.yaml, deploy/compose.development.yaml, deploy/compose.main.yaml, deploy/compose.staging.yaml, src/backend/.dockerignore, src/backend/Dockerfile, src/backend/app/tasks/task_routes.py, src/backend/app/users/user_crud.py, src/backend/app/users/user_routes.py, src/backend/scheduler/inactive_users.py, src/backend/scheduler/unlock_tasks.py
- https://github.com/hotosm/fmtm/pull/1984
- https://github.com/hotosm/fmtm/issues/1603
- https://github.com/hotosm/fmtm/issues/1999
- https://github.com/hotosm/fmtm/issues/2181
- https://github.com/hotosm/fmtm/pull/2088
- Using cron in a container without root is actually really difficult. We need root to run the cron daemon.
- Instead I added supercronic, a go binary specifically built to replace cron in containers.
- This runs as part of the local development compose stack.
- As we don't build a specific container for this, it's much more flexible. We can replace the compose service with a Kubernetes CronJob as needed.
- The python scripts to run are under `/src/backend/scheduled/xxx.py`
- TODO:
- Unlock tasks / features
- Delete old user accounts
- Trigger ODK photo upload?
- I tried …
=> Add task scheduler to backend services (cron jobs)

src/backend/app/db/models.py
- Related to: #2223
Populate total tasks in the project after task creation.
=> feat(project): populate total task field after task creation

src/backend/app/db/postgis_utils.py
Fixes https://github.com/hotosm/osm-fieldwork/issues/344, as we no longer will create entities via XLSForm (moved to entity creation via API)
- Rob suggested this is a convention: negative numbers for geoms that come from outside OSM.
- Updated the mandatory fields check to reflect that.
- Hopefully doesn't break anywhere we use the `osm_id` in the code 🤞 
=> Set osm_id property to negative value if the geom is not from OSM

src/backend/app/central/central_crud.py, src/backend/app/central/central_deps.py, src/backend/app/central/central_routes.py
Work towards #2075
- Endpoint to upload media attachments for a form.
- They must be **predefined** in the form beforehand.
- Perhaps this can be refactored to work the same was as additional datasets code (where we receive the additional datasets from the user during project creation, then we inject the fields in the XLSForm automatically).
- This would be pretty tricky to implement though without knowing for which field the media is associated, what data type is it (image, video, audio), etc. Perhaps best left for when we have an interactive form builder?
- Example
- MDP form with `mdp.png` attachment defined on category selection field: [mdp_xlsform.xlsx](https://github.com/user-attachments/files/19234317/mdp_xlsform.xlsx)
- The png file to upload via this endpoint: …
=> Add endpoint to upload form media such as images, videos, audio

src/backend/app/db/models.py, src/backend/app/projects/project_deps.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py, src/backend/app/tasks/task_crud.py, src/backend/app/tasks/task_routes.py, src/backend/app/tasks/task_schemas.py, src/backend/migrations/009-task-assignments.sql, src/backend/migrations/init/fmtm_base_schema.sql
=> Assign users to tasks (+ project team integration)

src/mapper/src/lib/components/dialog-entities-actions.svelte, src/mapper/src/lib/components/forms/wrapper.svelte, src/mapper/src/routes/[projectId]/+page.svelte
Fixes issue where bottom footer was appearing when the web forms panel was open
Basically creates a bindable display variable at the page level that is passed down to the entity action buttons and the web forms drawer.  When changes are made, this percolates up to the top level variable which is then used in an if statement to hide the footer.
We could have set display to none, turn off the z-999 class, or manually set the z-index to 0.  However, I felt a simple if statement was the most intuitive.
- go to http://mapper.fmtm.localhost:7050/1?webforms=true
- click on an area
- click on a building
- click on "MAP IN ODK WEB FORMS"
- the web forms should slide in from the slide and the footer should disappear …
=> hide conflicting footer when web forms drawer is open

src/frontend/src/views/SubmissionDetails.tsx
Submission details page will crash when it attempts to render a null value, because it will try to call Object.values(null), which throws an error.
I specifically encountered this issue when working on web forms photo upload.  I'm thinking we probably want to gracefully handle errors, so an error in one part doesn't crash the whole page.  In theory, there could be a network issue and not a code issue, too.
N/A
I've been trying to fix a local issue I'm having with web forms and photo upload, but I'm thinking it would be a good idea to have this page be more resilient to random issues.
- go to a submission details page like http://fmtm.localhost:7050/project-submissions/1/tasks/3/submission/uuid:4b14699b-fd93-45b6-9aef-6a88ad217bb4 …
=> fix: Submission details page crashing when trying to render null value

src/frontend/package.json, src/frontend/pnpm-lock.yaml, src/frontend/src/utilfunctions/getTaskStatusStyle.ts
- Related to #2235
- Use `turf/centroid` to calculate the centroid of the task area. Previously it was calculated using task extent center that made irregularly shaped tasks lock icon to fall outside its area.
Before: 
After:
=> Align task lock icon within task area

src/backend/app-entrypoint.sh, src/backend/migrations/init/fmtm_base_schema.sql
- Project stats materialised view is not created in the first place; you have to wait for 10 minutes to initialise it. It should be created whenever service starts.
- Added command in entrypoint to initialise the project stats mv.
- Can you confirm if it works periodically every 10 minutes?
=> Initialize project stats materialized view

src/backend/app/projects/project_routes.py, src/frontend/src/views/Home.tsx
- There were two endpoints, unnecessarily for similar functionality (`/search` and `/summaries`)
- Removed search endpoint
- Used summaries endpoint in frontend in place of search
N/A
=> Use summary api instead of search api

src/frontend/src/store/slices/UserSlice.ts, src/frontend/src/views/ManageUsers.tsx
- UserId column in manage users tab was all empty
- Couldn't assign roles to user
- Replace userId with User sub id
=> Fix Assign user roles from manage users

src/mapper/src/lib/components/forms/wrapper.svelte, src/mapper/src/lib/utils/fetch.ts, src/mapper/static/web-forms.html
- [] 🍕 Feature
Fixes [#123](https://github.com/hotosm/fmtm/issues/2327)
Basically cache/proxy the ODK Web Forms library and forms xml by fetching and then passing along the response blob url.
no appearance changes
I tried a couple alternatives before finding this one.  I tried loading the OdkWebForm library in an isolated iframe and then injecting the OdkWebForm Web Component into the rendered iframe.  Technically, I successfully inject the web component into the iframe, but the issue is that the odk-web-forms.js (web component build without shadow dom) library presumes that  it will be used in the same frame as its loaded.  Unfortunately, this means that if you pass in the OdkWebForm object from another iframe (in the same origin) it won't carry with it the css styles that it loaded as a …
=> cache form xml and ODK Web Forms js library

src/backend/app/central/central_crud.py, src/backend/app/central/central_routes.py, src/backend/packages/osm-fieldwork/osm_fieldwork/OdkCentralAsync.py
Related #2337
Work in progress. @Anuj-Gupta4 could you look into this please 🙏 
- As described in the issue, we need a way to get the form attachments from ODK --> mapper frontend (display in web forms).
- There is a test implementation in this PR for osm-fieldwork, but what we probably actually need is a wrapper for these two endpoints:
- https://docs.getodk.org/central-api-form-management/#listing-form-version-attachments
- First, we need the version of the form.
- Next we call this API to get a list of attachments.
- We filter out the image attachments: JPG, PNG
- https://docs.getodk.org/central-api-form-management/#downloading-a-form-version-attachment
- Then for each attachment we are interested in, we get the data. HOWEVER, the docs state this is the blob data.
- After the S3 update …
=> Allow for download of form media/attachments as list of URLs pt1

src/backend/app/projects/project_routes.py, src/backend/tests/conftest.py, src/backend/tests/test_projects_routes.py, src/backend/tests/test_task_routes.py
- Related to: #2232 
Tests to:
- read project
- update project form
- download project form
- get contributors
- add new pm and get project user
- create entity
- download project boundary
- download task boundary
- create geometry log
- read geometry log
- delete geometry log
- read tasks
- get specific task
- more task events
- get task activity
=> Add some tests for project and task routes

src/backend/app/db/models.py, src/backend/app/organisations/organisation_routes.py, src/frontend/src/api/OrganisationService.ts
- Issue: #1572 
- Update organisation delete function:-
- Only allow users to delete organisation if no projects are present within organisation
- Create delete organisation admin api
-  Do not allow user or org admin to delete their own role
- They can remove other admins if they are organisation admin of same organisation
`/organisation/org-admin/{user_sub}?org_id=1`
```json
{
"detail": "You cannot remove your own admin role."
}
```
- ✅ …
=> Delete organisation only if there are no projects within it

src/mapper/src/lib/components/forms/wrapper.svelte
N/A
Basically take the geolocation if available and adds it to the submission xml.
No visible change, but here's an example output from submissions download from manager:
Tried to see if enabling geolocation in the iframe would have getodk/web-forms automatically inject the warmup/start-geopoint value, but that didn't seem to work.  My understanding is that this information will be added to odk in the future, at which point we can remove the lines added in this PR.
- 📝 Use …
=> added warmup latitude/longitude into form submission

src/mapper/src/lib/components/forms/wrapper.svelte
Fixed broken web forms appearance.
Basically hard-code the height of the web forms popup to 100%.  I don't think there's a need to make this height something someone can over-ride in a custom css variables file (css module).  However, this is meant just as a quick fix, so definitely open to better fixes in the future.
see below
Looked at over-riding --at-apply in css or adding it as a custom variable; however, being short on time, this was the most direct approach.
Try to submit a web form
- 📝 Use descriptive commit …
=> fix broken web forms appearance

src/frontend/src/components/createnewproject/DataExtract.tsx
- Generating polygon data extracts was failing
- Fixed the issue, only pass centroid param if primary geom type is "POINT"
N/A
=> Pass centroid param only if primary geom type is point

src/mapper/static/web-forms.html
Example: Fixes #2403 
Added code that adds canParse to URL object.  This is contained within the iframe.  [popover] is also not supported in older browsers, so basically hide it.  Unfortunately odk web-forms doesn't seem to have any other attributes it updates when error popover is updated, so css rules rely on pesudo-classes.  What this means in practice is that certain errors might not appear; however, in my testing the relevant errors (like not filling in a required field) still appear correctly.
URL.prototype.canParse didn't work for me, so that's why I use URL.canParse
adding support directly into xforms-engine or web-forms.  However, I want to minimize merge conflicts with upstream.
- 📖 Read the Field-TM Contributing Guide: …
=> fixing issue 2403

src/mapper/src/lib/odk/collect.ts, src/mapper/src/routes/[projectId]/+page.svelte
Example: Fixes #2393
Basically do the same things after you create an entity as you would do if you select an entity and click "Collect Data".  The main difference is we have to first select the entity, because the entity creation workflow doesn't automatically "select" an entity in the entities store before creation (because it doesn't exist yet).
Strongly considered adding the logic into openOdkCollectNewFeature function inside of src/mapper/src/lib/odk/collect.ts.  However, this functionality requires a lot of variables set up in +page.svelete and it would require passing in a lot of variables. …
=> auto-open web forms when entity created

src/backend/app/users/user_routes.py
The usernames api will be used to assign organisation admins. But non OSM users can't be an organisation admin. In that case, we should only list osm users to choose an organisation admin from that list.
Added a filter to usernames to retrieve only osm or google users as needed.
=> Add signin type filter to user list retrieval

src/backend/app/organisations/organisation_routes.py
The organisation detail page was giving a generic 403 error page when someone who is not an organisation admin would access it.
The organisation admins get api has been updated to allow any authenticated user to view it. It should be ok to do this.
=> Update list organisation admins permissions to allow authenticated users

src/backend/app/db/models.py
- Issue:  #2453 
- `LEFT JOIN` always has been tricky for me; it resulted in multiple repetitions of projects if `user_roles` table has multiple rows for same project, as it creates a row for every matching pair
- Instead of join I have now just checked if any row for that project exists on the `user_roles` with that user which avoids row multiplication
So:
- If it's public → included
- If it's private → check if the current user has a role in user_roles
- If such a role exists → include the project
N/A …
=> Remove user_roles join to avoid multiple projects result

src/backend/app/auth/auth_deps.py, src/backend/app/auth/auth_routes.py, src/backend/app/auth/auth_schemas.py, src/backend/app/integrations/integration_routes.py, src/backend/app/organisations/organisation_routes.py, src/backend/app/projects/project_routes.py, src/backend/app/users/user_crud.py, src/backend/tests/conftest.py
- New route `/integrations/new-user` to:
1. Create a new user.
2. Provide an auth cookie set in the users browser.
- If an external application has an org_admin API key, then can do this.
- Create the user and provide the cookie.
- When the user visits FieldTM mapper frontend, they will be automatically logged in.
=> Add capability to create new users via API key

src/backend/app/users/user_crud.py, src/backend/app/users/user_routes.py
- Related to: #2454 
Org admin can now access user list.
Also added a sign in type filter
=> Add signin_type filter to user retrieval endpoints and allow org admin access

src/backend/packages/osm-fieldwork/osm_fieldwork/update_xlsform.py
- Issue: By default `new_geom_type` is set `POINT`, and allowing `verification fields` results in invalid xlsform
- pytest failure
- Simply allows verification fields based on `need_verification_fields` bool
N/A
=> Allow verification questions for every geom type

src/backend/packages/osm-fieldwork/osm_fieldwork/update_xlsform.py
- Skip verification question if new feature is collected in both odk collect and web form
- Check `⁣status`; if it is '3', which `NEW_GEOM⁣`, then skip verification question
-  [x] If we map a new feature, then feature_exists and `digitisation_correct` questions should be omitted.
I checked all it is working, Still worth testing @spwoodcock @Anuj-Gupta4 
N/A
- 📗 …
=> Skip verification question if new feature

.github/labeler.yml, src/mapper/static/web-forms.html
- [] 🐛 Bug Fix
Users want to be able to customize their web forms look
Append css overrides link to the body instead of the head because ODK Web Forms injects css into the head after the web component loads, which over-rides the "over-rides" css file because it was appended later.  Placing the "over-rides" file in the body ensures it comes after the head css files and thus takes precedence.
could hard-code font loading in the static/web-forms.html, but requiring people to import fonts through the css file improves flexibility. …
=> add font and move css over-ride to bottom of web-forms iframe body

src/frontend/src/components/ProjectDetails/ProjectDetailsMap.tsx, src/mapper/src/lib/components/dialog-entities-actions.svelte, src/mapper/src/lib/components/map/main.svelte
- Related to #2352
After clicking on `Select this feature` button, directly show the `entity-modal` by skipping entity selection confirmation step
https://github.com/user-attachments/assets/8c58c315-a56c-4585-be90-26dd7d0adade
https://github.com/user-attachments/assets/e6b008bf-f885-4622-a870-3a5bc0a82fd2
=> Refactor: Skip polygon selection confirmation step

src/mapper/src/lib/components/forms/wrapper.svelte, src/mapper/src/lib/utils/device.ts
Example: Fixes #2507
Basically saves a deviceid to localStorage
N/A
Thought about using user agents, but that could have privacy issues and wouldn't necessarily be unique either.  Most people don't clear their cache on their phone, so the localstorage approach seemed like a good middle ground.
=> added deviceid

src/mapper/src/styles/dialog-entities-actions.css, src/mapper/src/styles/map-legend.css, src/mapper/src/styles/map.css
- Related to #2568
- Replace all existing CSS classes related to entity status where we are adding hardcoded CSS color classnames with defined CSS vars in the root
=> Use defined CSS var for entity status

src/backend/app/db/models.py, src/backend/app/organisations/organisation_crud.py, src/backend/app/organisations/organisation_routes.py
- Related to: #2563 
Sends an approval request email to the associated email of the primary organisation whenever a new organisation is created. The requesting user can also request odk server for usage.
=> Implement organisation approval request notification along with odk server request when applicable

src/backend/app/submissions/submission_crud.py, src/backend/app/submissions/submission_routes.py
- Related to: #2550
Include data from repeat groups by using pyodk in list submissions, submission table, submission json and geojson download.
Pyodk was found to be faster by at least 10 seconds on average on some rough local load testing.
We still need to work on repeat group on submission detail page as it is also not supported by pyodk.
- 📝 Use descriptive …
=> Update submission retrieval to use pyodk except in submission detail page

src/backend/app/config.py, src/backend/app/db/models.py, src/backend/app/organisations/organisation_crud.py, src/backend/app/organisations/organisation_routes.py, src/backend/app/users/user_crud.py, src/backend/tests/test_organisation_routes.py
- Related to: #2563 #2300 
Allow admins and primary organizations to assign an ODK server during organization approval, instead of manual-assigning it on request. Updated the organization approval request message to include an approval URL. Also added a role filter to the DbUser.all() method.
- 📗 Update any related …
=> Add option to set primary ODK server during approval

src/backend/app/central/central_schemas.py, src/backend/app/integrations/integration_crud.py, src/backend/app/projects/project_routes.py, src/mapper/src/lib/db/entities.ts, src/mapper/src/store/entities.svelte.ts
- Related to #2620
- add submission_ids to OdkEntitiesUpdate for webhook processing
- update submission_ids also when updating local db
- remove redundant status update on backend (status update is already handled during webhook processing)
- implement entity processing queue for efficient updates (the reason for implementing this is: 
```
for (const entity of rows) {
const updatedEntity = {
...entityMapClone.get(entity.entity_id), // fallback to existing data
...entity, // overwrite with new status
};
entityMapClone.set(entity.entity_id, updatedEntity);
// Store value in local db for persistence across restarts
await DbEntity.update(db, entity);
}
)
```
The await was here was making stale submission_ids data to be concatenated with the new submission_id, causing the final submission_ids …
=> Sync multiple submission id's

src/frontend/src/components/ProjectDetails/MapControlComponent.tsx, src/frontend/src/components/ProjectDetails/ProjectDetailsMap.tsx, src/frontend/src/components/ProjectDetails/ProjectOptions.tsx, src/frontend/src/components/ProjectSubmissions/SubmissionsTable.tsx, src/frontend/src/views/ProjectDetails.tsx
- Related to #2650
- Hide the download QR code option from project options if project uses webforms
- Remove conversion of integer entity status to string using enum mapping on submissions table (the page was crashing as a result of 3 being set to entity status when new feature is created on odk collect app. and after discussion, decided to remove conversion as the downloaded csv would also contain the status in integer format though the issue would be solved by adding an optional chaining)
=> Fix project qr option & submission table

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/backend/app/projects/project_schemas.py, src/backend/tests/test_projects_routes.py, src/frontend/src/components/ProjectSubmissions/SubmissionsInfographics.tsx
- Updated `get_project_users_plus_contributions` to fetch and count user submissions for a project.
- Introduced `ProjectContributor` schema for structured response.
- Modified API route to return contributors with submission counts.
- Updated frontend to reflect changes in submission terminology from "Contributions" to "Submissions".
Total contributions on infographics doesn't match with number of submissions by respective users #2304
Modified the total contributors table to show number of submissions per user including new features submissions.
Used the ODK Central API to fetch all form submissions for the project and counted them per user.
Modified the Frontend to display submissions in the table
- 📖 Read the Field-TM Contributing Guide: …
=> fix(projects): fix total contributions mismatch in infographics

src/backend/app/projects/project_crud.py
- Filename with folder structure is not allowed without providing access token
This PR refactors `generate_data_extracts` adding access token (`RAW_DATA_API_AUTH_TOKEN`).
=> Pass access token to generate osm extracts

src/backend/app/db/models.py, src/backend/app/projects/project_routes.py
- #2695 
This PR implements visibility filtering for draft projects in Field-TM with the following rules:
- Can only see public AND non-draft projects
- Full access to all projects including drafts
- No visibility restrictions
- Can see all projects in their organizations including drafts
- Can see all public projects
- Have full visibility within their organization scope
- Can see draft projects for projects they manage
- Can see public non-draft projects
- Regular visibility rules apply for other projects
- Can see public non-draft projects
- Cannot see draft projects unless they are a project manager
- 📖 Read the Field-TM …
=> Update visibility filter to projects based on access

src/backend/app/db/models.py
…ss organisation manager
- #2726 
Updated the _build_visibility_filter method to properly enforce organization-level privacy:
- Superadmins: Can see all projects (unchanged)
- All public non-draft projects
- All projects in their organizations (including private/draft)
- Public non-draft projects
- Private/draft projects ONLY if explicitly assigned as PROJECT_MANAGER
- Public non-draft projects they're assigned to
- ✅ Provide tests …
=> Fix project visibility to exclude draft projects for cross organiisation admins

src/mapper/src/routes/project/[projectId]/+page.svelte, src/mapper/src/store/common.svelte.ts, src/mapper/src/store/tasks.svelte.ts
- Related to #2737
- Fix task selection, task popup issue
- Display webforms or ODK app workflow based on `use_odk_collect` flag on project state
I guess the following logic was also causing issues on task selection if the events length was greater than 0. Also, looking at the code, we don't need to filter and map the rows because all the `taskEventData.rows` items had `value` and it was giving the same result as `taskEventRows = taskEventData.rows`
```
if (events.length > 0) {
// If we already have data, only append data changes made since last update
taskEventRows = taskEventData.rows
.filter((item): item is { value: TaskEventType } => 'value' in item && item.value !== null)
.map((item) => item.value);
} else {
taskEventRows = taskEventData.rows;
}
```
=> Fix mapper frontend issues

src/mapper/src/styles/dialog-entities-actions.css, src/mapper/src/styles/dialog-task-actions.css
- Related to #2745
- Make task and entity modal title bold and primary color
=> Update task and entity dialog styles 

src/backend/app/central/central_crud.py, src/backend/app/central/central_routes.py, src/backend/app/projects/project_routes.py, src/backend/packages/osm-fieldwork/osm_fieldwork/OdkCentralAsync.py, src/backend/tests/conftest.py, src/backend/tests/test_projects_routes.py, src/frontend/src/api/CreateProjectService.ts, src/frontend/src/components/CreateProject/03-UploadSurvey.tsx, src/frontend/src/components/CreateProject/constants/defaultValues.ts, src/frontend/src/components/CreateProject/validation.ts
Related to https://github.com/hotosm/field-tm/issues/2693
Backend part of https://github.com/hotosm/field-tm/issues/2342
- Moved the XLSForm upload from the end of project creation to the form upload page.
- The project creation `generate-project-files` doesn't do as much work now.
- The user gets immediate feedback on their form & we can now display the 'required media' specified in the form (taken from ODK Central validation endpoint).
- I also added an endpoint `/central/list-form-media` to allow us to get a list of required files to upload.
- We can implement a frontend dropzone next to allow users to POST to `/central/upload-form-media`. …
=> Backend part to allow listing of required media from uploaded XLSForm

src/backend/app/auth/roles.py, src/backend/app/db/enums.py, src/backend/app/submissions/submission_crud.py, src/migrations/001-remove-sensitive-visibility-enum.sql, src/migrations/init/shared/1-enums.sql
- #2659 
This PR removes deprecated SENSITIVE and INVITE_ONLY values from the ProjectVisibility enum and ensures the codebase reflects this change.
- Removed deprecated values: SENSITIVE and INVITE_ONLY
- Now handles only 'PUBLIC' and 'PRIVATE' visibility options
- Removed SENSITIVE and INVITE_ONLY from migrations/init/shared/1-enums.sql to keep new setups clean
- Converts existing SENSITIVE/INVITE_ONLY values to PRIVATE
- Replaces the enum type in the database
- Fully idempotent: safe for repeated execution.
- 👷‍♀️ Create small PRs. In most cases, this will be …
=> Refactor project visibility removing SENSITIVE and INVITE_ONLY.

src/backend/app/projects/project_crud.py, src/backend/app/projects/project_routes.py, src/frontend/src/components/CreateProject/04-MapData.tsx
- #2325 
- #1220 
This PR introduces support for selecting how OSM features are clipped to the Area of Interest (AOI), offering more flexibility in extract generation.
1. Backend Update
- Added a new parameter: use_st_within which Controls the clipping behavior during extract generation (ST_WITHIN True by default)
2. Clipping Mode Options
- ST_WITHIN: Includes only features completely inside the AOI
- ST_INTERSECTS: Includes features that touch or overlap the AOI boundary
3. UI Update
- When "Fetch data from OSM" is selected as the data source: A toggle is displayed allowing the user to switch between ST_WITHIN and ST_INTERSECTS modes
- 📖 Read the Field-TM Contributing …
=> Add 'use_st_within' option for OSM data extract generation
